### ISSUE TITLE
Please fork my AutoPkg repo

### ISSUE THREAD

**Issue by rtrouton** [autopkg/autopkg#133]
Would you please fork https://github.com/rtrouton/AutoPkg for the main AutoPkg repo? I've got a number of recipes which are currently not searchable via AutoPkg.

**Comment by rtrouton** [comment]
Now that AutoPkgr has been updated and is now showing the identifiers, I've updated the recipes in https://github.com/rtrouton/AutoPkg to remove the "_rtrouton" part from the recipe names.

**Comment by timsutton** [comment]
Thanks for updating the identifiers.

I'll set up the repo now, though you might also want to consider removing .download recipes which are duplicates (although they've got your unique identifiers) of those from autopkg/recipes, and instead use those as ParentRecipes. Most users probably already have autopkg/recipes in their search dirs.

**Comment by timsutton** [comment]
Created and available here:

https://github.com/autopkg/rtrouton-recipes
