### ISSUE TITLE
force_munkiimport does not seem to work?

### ISSUE THREAD

**Issue by vmule** [autopkg/autopkg#141]
Hello,
setting in the recipe:

<key>force_munkiimport</key>
<false/>

Does NOT STOP the dmg to be imported all the time the recipe is ran.
Any advice??

**Comment by vmule** [comment]
I just find out the solution.
I need to build the catalog after the import using:

https://github.com/autopkg/autopkg/wiki/Processor-MunkiCatalogBuilder

Thanks

**Comment by timsutton** [comment]
You got it - this is one of the FAQ:

https://github.com/autopkg/autopkg/wiki/FAQ#every-time-i-run-a-munki-recipe-it-keeps-importing-the-item-into-my-repo-why

You don't necessarily need to rebuild using the processor, you can also just run makecatalogs. But the processor is smarter, as long as you're always doing it within a run of other recipes.
