### ISSUE TITLE
Unable to pack a Flat pkg

### ISSUE THREAD

**Issue by vmule** [autopkg/autopkg#142]
Hello,

I tried to unpack a flat pkg, expand the payload, modified the folder and rebuild the payload and the bom file using this commands:

# recreate the payload  
```
os.remove(os.path.join(unpkg_path, 'Payload'))
cmd = ( '/usr/bin/ditto', '-z', '-c', pkgroot + '/', unpkg_path + '/Payload')
    subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```
# create new Bom
```
os.remove(unpkg_path + '/Bom')
    cmd = ('/usr/bin/mkbom', pkgroot + '/',  unpkg_path + '/Bom')
    subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```
# update the PakcageInfo file with the new data(number of files and dimension of the pkg)
```
pkg_file_num = str(sum([len(files+d) for r, d, files in os.walk(pkgroot)]) + 1)
pkg_size = str(int(subprocess.check_output(['du','-sk', pkgroot]).split()[0]) - 4)
pkg_line = "<payload numberOfFiles=\"" + pkg_file_num + "\" installKBytes=\"" + pkg_size +"\"/>"

for line in fileinput.input(unpkg_path + '/PackageInfo', inplace=True):
    line = re.sub(r"<payload numberOfFiles=\".*\" installKBytes=\".*\"/>", pkg_line, line.rstrip())
    print line
```

After all this if I run FlatPkgPacker.py Processor, I get a .pkg but it's broken, does not show the list file and does not install properly. It just install the folder hierarchy without the files.

But when I run the command manually to Repackage it:

``` pkgutil --flatten source dest.pkg ```
I get a working package, that installs correctly and all.

So I started to think that there must be something related to the tool itself that is causing the issue.
You can find my code here:

https://github.com/vmule/autopkg-recipes/tree/master/AdobeFlashDebugger

I hope you can help solve this strange behavior.
Let me know if you need more infos.

Many Thanks

**Comment by timsutton** [comment]
Something is wrong with the BOM you are making. The Installer complains (with BOMCopierFatalErro) that "The operation couldn’t be completed. cpio read error: Undefined error: 0"

`lsbom` says the Bom in your generated package is not a bom file.

It's a bit hard for me to see through your code as to what you're intending to achieve here, but it's not clear to me why if you're writing a recipe that's doing repackaging, why not use AutoPkg's existing package creation processor targeted to your payload directory and let it do the work, as opposed to calling `mkbom` and `pkgutil` yourself?

FWIW, two things I needed to modify in your recipe for them to work for me:

1. I had to set `MUNKI_REPO` explicitly on my system - normally you don't set this yourself, AutoPkg users have this already configured in their defaults or at the command-line.
2. AutoPkg can already tell you a recipe's cache directory using `self.env['RECIPE_CACHE_DIR']`

**Comment by vmule** [comment]
Hello,
to answer your question, is because I'm modifying the Payload, before rebuilding it.
Since I modify the Payload I need to adjust the mkbom and pkgutil.

In my tests the BOM seems fine, since I can build manually and successfully the pkg, and also I can lsbom it giving me the correct file list.

Did you try to build the pkg manually?
Using as source_dir the "Payload" in  ``` ~/Library/AutoPkg/$reciptname/Payload ? ```

Thanks

**Comment by timsutton** [comment]
I didn't try to build the package manually because I was having a hard time breaking down the lines between the steps in the recipe and what you were doing in your custom processor. You mentioned that you run the FlatPkgPacker processor which seems to cause the issue, but it's not in your recipe, so I'm confused.

Are you saying that if you run the recipe in its current state, it works for you?

**Comment by vmule** [comment]
Yes I removed the FlatPkgPacker processor from the recipe and I was trying to do it with my custom processor.

No the current state, i.e. without using PkgCreator.py was not working.
BUT (!!) I followed your advice and using PkgCreator.py in the recipe everything is working fine!!
Many Thanks!
