### ISSUE TITLE
Please fork my AutoPkg repo

### ISSUE THREAD

**Issue by vmule** [autopkg/autopkg#146]
Would you please add my AutoPkg repo to the main AutoPkg site?

https://github.com/vmule/autopkg-recipes

Many thanks!

**Comment by gregneagle** [comment]
Your repo appears to contain duplicates of other repo's recipes, for example: https://github.com/vmule/autopkg-recipes/tree/master/AdobeFlashPlayer

With changes limited to adding your name:
https://github.com/vmule/autopkg-recipes/commit/b73d0be95d4295ae21fb76b76b9b5a26958eb3ff

It's not clear what the purpose is here of the duplications.

We'd prefer recipe repos not duplicate existing "core" recipes unless they differentiate in some way (and then be sure to document the differences!)

**Comment by vmule** [comment]
Hello,
thanks for the reply.
Here some details on what the recipe is doing:

https://github.com/vmule/autopkg-recipes/blob/master/AdobeFlashPlayer/about.txt

I also made some change to that custom processor, not sure how to show that on github but doing a diff:

```
diff autopkg-recipes/AdobeFlashPlayer/AdobeFlashDmgUnpacker.py recipes/AdobeFlashPlayer/AdobeFlashDmgUnpacker.py
3c3
< # Copyright 2010 Per Olofsson, 2015 Vito Mule
---
> # Copyright 2010 Per Olofsson
18a19
> ### NOTE: this processor is no longer used as Adobe has fixed their package
22d22
< import fileinput
24c24
< import re
---
> import tempfile
27d26
< import tempfile
29c28,29
< from autopkglib import Processor, ProcessorError
---
> from autopkglib.PkgExtractor import PkgExtractor
> from autopkglib import ProcessorError
35c35
< class AdobeFlashDmgUnpacker(Processor):
---
> class AdobeFlashDmgUnpacker(PkgExtractor):
39c39
<         "finalize_script_path": {
---
>         "dmg_path": {
42c42
<                 "Path to folder containing the Flash player postflight script.",
---
>                 "Path to a dmg containing the Flash player installer.",
66c66
<     def decompress_plugin(self, finalize_script_path, pkgroot):
---
>     def decompress_plugin(self, pkg_path, pkgroot):
91,92c91,92
<             original_postflight_path = os.path.join(finalize_script_path,
<                                                     "finalize")
---
>             original_postflight_path = os.path.join(
>                 pkg_path, "Contents/Resources/postflight")
95c95
<             patched_postflight_path = os.path.join(temp_path, "finalize")
---
>             patched_postflight_path = os.path.join(temp_path, "postflight")
113,117d112
<
<             shutil.rmtree(os.path.join(pkgroot, 'Library/Application Support'))
<             shutil.rmtree(os.path.join(pkgroot, 'Library/LaunchDaemons'))
<             shutil.rmtree(os.path.join(pkgroot, 'Library/PreferencePanes'))
<
120a116,140
>     def copy_install_app(self, mount_point, pkgroot):
>         '''Copy installation app to pkgroot as Adobe Flash Player Install
>         Manager.app'''
>         #pylint: disable=no-self-use
>         source_app_path = os.path.join(
>             mount_point, "Install Adobe Flash Player.app")
>         dest_path = os.path.join(pkgroot, "Applications/Utilities")
>         dest_app_path = os.path.join(
>             dest_path, "Adobe Flash Player Install Manager.app")
>         try:
>             os.makedirs(dest_path, 0755)
>             shutil.copytree(source_app_path, dest_app_path)
>         except (OSError, IOError):
>             raise ProcessorError(
>                 "Couldn't copy Adobe Flash Player Install Manager.app")
>
>         # remove embedded pkg from copied app
>         embedded_pkg_path = os.path.join(
>             dest_app_path, "Contents/Resources/Adobe Flash Player.pkg")
>         try:
>             shutil.rmtree(embedded_pkg_path)
>         except (OSError, IOError):
>             raise ProcessorError(
>                 "Couldn't clean up Adobe Flash Player Install Manager.app")
>
121a142,145
>         # Mount the image.
>         mount_point = self.mount(self.env["dmg_path"])
>         # Wrap all other actions in a try/finally so the image is always
>         # unmounted.
124c148,154
<             finalize_script_path = self.env['finalize_script_path']
---
>
>             # extract package payload
>             pkg_path = os.path.join(
>                 mount_point,
>                 "Install Adobe Flash Player.app",
>                 "Contents/Resources/Adobe Flash Player.pkg")
>             self.extract_payload(pkg_path, pkgroot)
127c157,160
<             self.decompress_plugin(finalize_script_path, pkgroot)
---
>             self.decompress_plugin(pkg_path, pkgroot)
>
>             # copy app to pkgroot as Adobe Flash Player Install Manager.app
>             self.copy_install_app(mount_point, pkgroot)
136a170,172
>         finally:
>             self.unmount(self.env["dmg_path"])
>

```

Thanks

**Comment by timsutton** [comment]
Ok, so what I'd propose is you rename the recipe to something that makes it clear as to what it is doing, which differentiates it from the other existing FlashPlayer recipes. The "name" is the filename without the `.munki` extension, and the `Identifier` usually includes this name in some form, as you've seen.

Rather than include an 'about.txt' file in the repo, please use the `Description` keys in the recipe files themselves. This is what is user-visible when someone would inspect a recipe or run `autopkg info`.

**Comment by bryanzak** [comment]
Curious, why not just go with the standard flash install and add a munki post install script to delete what you don't want?

Bryan

**Comment by vmule** [comment]
My approch here is that is better to run more stuff one time (on the build machine with autopkg) that running a script on all the machine that will install flash.

**Comment by timsutton** [comment]
@vmule Ping! We can still add your repo if you'd like to make the changes to more clearly document your Flash recipes.

Just doing another quick check of the others, the Wireshark, MacVim and MplayerX recipes seem like they duplicate jleggat and hjuutilainen - not verbatim but do the same things. So you may want to take another look and see whether there's any functional differences between yours and the existing recipes for these applications.

**Comment by vmule** [comment]
Thanks for contacting me, I've been busy with other stuff.
I'll take a look this weekend and we decide if it makes sense to add or
close the request.
Thanks

**Comment by vmule** [comment]
Hello I made the requested changes to the Flash Recipes and removed the non unique recipes (Wireshark, MacVim and MplayerX)
Thanks

**Comment by timsutton** [comment]
Thanks for your patience! Added here:

https://github.com/autopkg/vmule-recipes
