### ISSUE TITLE
Please fork my repo

### ISSUE THREAD

**Issue by grahamgilbert** [autopkg/autopkg#152]
Hi guys,

I've got a couple of recipes that might be useful: https://github.com/grahamgilbert/autopkg-recipes

Cheers
G

**Comment by timsutton** [comment]
Looks good, just a couple things:

Typo: Sal and outset Descriptions are still left over from the AutoDMG recipe.

I'd recommend adding a brief explanation to the AutoPkgr setup recipe, just to explain what it's for and how it supports AutoPkg(r?) If you want to support others being able to use it, you could support an environment script in the user's overrides directory that would also be a part of the built package, which would allow you to let things like `autopkg_user` in `AutoPkgrSetup.sh` be overridable.

Adding support for customization is up to you whether you want to bother, but either way it would be good if you can document it so it's clear how one would use it, and how/where one would need to make modifications to customize it.

**Comment by grahamgilbert** [comment]
Argh, the AutoPkgr setup is a leftover. I'll move it to a separate repo. I'll fix up the descriptions and update here.

**Comment by grahamgilbert** [comment]
I've removed the AutoPkgrSetup (for now, I'll decide later if it's something that should be here) and corrected the leftover from the recipe I based them from.

**Comment by timsutton** [comment]
Done. Available here:

https://github.com/autopkg/grahamgilbert-recipes
