### ISSUE TITLE
Please fork my repo

### ISSUE THREAD

**Issue by golbiga** [autopkg/autopkg#153]
Hi,

Can you please fork my repo? https://github.com/golbiga/recipes

Thanks
Allen

**Comment by timsutton** [comment]
Yes, but we'd like if you can remove recipes which are just duplicates of existing recipes with a modified identifier. Quite a few of the non-JSS recipes are mostly copies of existing recipes from autopkg/recipes or other repos.

Alternate "versions" of known recipes are fine if they document how they differ and why. The idea is to keep down the amount of duplication across the various community repos.

**Comment by golbiga** [comment]
To confirm before making any changes. 

Remove CoRD download & pkg and use io.github.hjuutilainen.pkg.CoRD as the parent for com.github.golbiga.jss.CoRD

For TextMate2 remove the download recipe and use com.github.autopkg.download.TextMate2 as the parent for com.github.golbiga.pkg.TextMate2

I'll remove Papers 2, it's not being updated at this point.

Allen

**Comment by timsutton** [comment]
Yes, I think that's it.

**Comment by golbiga** [comment]
Changes have been made.

Thanks
Allen

**Comment by timsutton** [comment]
Done:

https://github.com/autopkg/golbiga-recipes
