### ISSUE TITLE
Add Sonos Repo

### ISSUE THREAD

**Issue by ssimone** [autopkg/autopkg#156]
Hi,

I started using autopkg about one month ago. I noticed that the recipe lists did not contain the Sonos app and decided to create my own. I would like to share it incase there are other people that would find the need for it. From what I can tell I'm the only person using it, so once the repo is duplicated I will delete it from my account.

Thanks,

Seymour Simone

**Comment by gregneagle** [comment]
Hello ssimone:

https://github.com/autopkg/autopkg/wiki/Sharing-Recipes

has some information on sharing your autopkg recipes. Take a look; if you have any follow-up questions, just ask.

**Comment by arubdesu** [comment]
[I got this one](https://github.com/autopkg/arubdesu-recipes/commit/22e75a6af28c8dc16b336c0d4951fcaade1d023d). 
@ssimone, you can check with the autopkg [search](https://github.com/autopkg/autopkg/wiki/Finding-Recipes) verb in the future to check if someone's already made a recipe that has been committed to the autopkg organization. 
Also, your download recipe hard-coded one specific URL/version, which would require constant maintenance. I had figured out the way to follow a URL they publish on their support page, and have tested all the permutations I like to have included in the recipes for a product, please consider using mine.
Recommending close.

**Comment by ssimone** [comment]
@arubdesu, Thank you. At the time of my search there were no Sonos recipes available. But I'm glad you were able to create a better recipe than mine. I will use your recipe from now on.

@gregneagle, Thank you as well.
