### ISSUE TITLE
Stop being reckless, use "autopkg repo-update-check all"

### ISSUE THREAD

**Issue by eahrold** [autopkg/autopkg#159]
@timsutton, @gregneagle 
As per the discussion about blindly doing `repo-update all` being a bit reckless,  do you think there would be a benefit of adding an invocation such as `autopkg repo-update-check all`  to do the equivalent of 
```
git fetch
git diff FETCH_HEAD
```
And log the output. 
Basically just a autopkg native way to show any changes to the repos.

I did a rough out, and it was nearly identical to repo-update code.
If you have any interest in this feature I'd be happy to put up a PR with what I have.

Thanks.

**Comment by arubdesu** [comment]
Pardon the +1, but dooooo waaant

**Comment by timsutton** [comment]
I like the idea. I also like the idea of being able to see what changes have just been merged. Using `git log` you'll get hopefully more meaningful and concise descriptions and with `git log --patch` you can still get the full diff. Homebrew has some similar functionality (try `brew log git` and `brew log --patch git`), but this fetches the changes live.

There's a couple ways this might work with AutoPkg:

`autopkg repo-log <repo>` that would just do a `git log` on the local repos for fetching what the user already has (or has just pulled).

But I agree you also want a convenient way to show the changes against `FETCH_HEAD` before you merge them. Logically it would make sense to me for this to be available under the same command (like `repo-log`), but semantically having something like `repo-update --check` makes more sense to me immediately.

Thoughts?

**Comment by eahrold** [comment]
Overnight I had the exact same thought, it makes much more sense putting `--check` into `repo-update` as an arg, my original suggestion required a lot of code duplication. 

We could set it up so `--check` would do `git log -1 FETCH_HEAD` and `--show-change` would do `git log -1 FETCH_HEAD --patch`

I also like the idea of having `repo-log` to show the entire history.
Do you think `autopkg repo-log <repo>` should also take `git log` args, or just keep it simple?

**Comment by eahrold** [comment]
Actually I think `diff` is what we should use, so it actually shows what is new, not just the last commit.

**Comment by timsutton** [comment]
Agreed about not assuming one commit. The point is you want to see everything that's fetched but not merged. I believe Git has more efficient ways you can check the HEAD sha-1 on the server rather than blindly calling `fetch`, but `fetch` is simple.

So basically a fetch, then `git log --patch HEAD..FETCH_HEAD`, which would be non-empty if there's anything more recent fetched but not merged.

There might need to be some sanity checking if the Git repo is in a state we don't expect, but we don't currently do that with `repo-update` either, it's a blind pull. Sanity-checking for this is a rabbit-hole of its own..

(If I run `brew update` and log new processes with `newproc.d`, `git` gets called _268 times!!_)


I kind of like the idea of keeping all this behaviour under a single command like `repo-log`, since it all has to do with showing you logs of the changes to the repo, and not actually performing the update. I'm definitely in favour of simplicity rather than supporting arbitrary Git options.

**Comment by timsutton** [comment]
I think a non-diff output (ie. plain `git log`) is the better default also. A diff of a recipe could easily mean not much to a lot of people and buries the actual commit message.

**Comment by eahrold** [comment]
After some more fooling around, it looks like `git log master..origin/master` may work to show what hasn't been pulled and somewhat handle an unknown state since it at least specifies a particular branch. It still requires a fetch.

I still think that `repo-update --check`makes sense in that you just see what's changed and then update if it looks good, a sort of future event. Where `repo-log` reads to me as events that have already happened. But I won't get hung up on that as long as the feature is there.

You're right about the non-diff as default, but we should probably put in `--name-only` so at least the changed files are listed.

You're talking about comparing the SHA-1 from ` git ls-remote --heads ./ master` to `git rev-parse master` to see if somethings new right? Or is there a better way to do that?

**Comment by timsutton** [comment]
Agreed about showing the changed files. You could use some different formatting options (or potentially additional calls) to perhaps collect this info.

I was talking about `ls-remote`, yes. `git ls-remote --heads ./ master` just gives me the head of my local checkout though. Adding the remote name `origin` gives me what I want:

```
➜  com.github.autopkg.hansen-m-recipes git:(master) git ls-remote --heads ./ master
cb66f40c335ee1debee6c2b978ec6fe4e77c1755	refs/heads/master

➜  com.github.autopkg.hansen-m-recipes git:(master) git ls-remote --heads origin ./. master
c11c0e885b479ab0d914389afda4757023747eb8	refs/heads/master
```

I think there could be some sensible way to put the logs from both the checkout and "new on the remote" into a single command like `repo-log`.

Perhaps the default view is always the remote log (which would include anything newer than your checkout), and there are options for showing only what's 1) new and not pulled, and 2) local only. A fetch could be done as needed. Full patch data is only given if a `--diff` option is given.

Calling `subprocess.call()` on git commands like `log` seems to preserve the behaviour of paging the output, which I'm not sure is what we want. No other part of AutoPkg does paging and I'm not sure it's obvious to people how to quit (though most of us have probably used manpages..).

We also don't have to implement this all at once, but I think we should strive to have better semantics than Git and cover the case of "what does the user want 80% of the time" as the default. Specific options can be added when you want more specific behaviour, for example for use in AutoPkgr.

**Comment by gregneagle** [comment]
"We also don't have to implement this all at once, but I think we should strive to have better semantics than Git and cover the case of "what does the user want 80% of the time" as the default"

...or only, as advanced users who want more information can get it other ways -- like by using the git commands directly, or visiting the GitHub pages for the recipe repos. I don't think this should be terribly complex or detailed.

**Comment by eahrold** [comment]
I've got a sketch out out for this, do you want me to submit a PR to master, or would you like to create feature branch?

**Comment by timsutton** [comment]
Great! A dedicated branch is always preferable, it keeps things cleaner.

**Comment by eahrold** [comment]
@timsutton I just put up the commit to my fork https://github.com/eahrold/autopkg/tree/repo-log
If you make a branch here, I'll open up a PR to that branch.
Thanks.

**Comment by timsutton** [comment]
Sorry, when I said a branch I just meant on your side. Merging it into autopkg master is fine.

Looks good! Let's discuss further in the PR.

**Comment by eahrold** [comment]
I'm not sure what to do with this so I'll close this for now. @timsutton I'll keep the branch alive if you're so inclined to  do anything with it.

**Comment by timsutton** [comment]
I definitely intend to merge this soon, things have just been preventing me from spending much time with AutoPkg's core functionality as of late. The PR is still open, so that's good.
