### ISSUE TITLE
Apparent issue with Flash

### ISSUE THREAD

**Issue by jwzg** [autopkg/autopkg#161]
Error running recipes
/Users/XXXXX/Library/AutoPkg/Cache/com.github.autopkg.pkg.FlashPlayerExtractPackage/downloads/AdobeFlashPlayer.dmg is not mounted
/Users/XXXXX/Library/AutoPkg/Cache/com.github.autopkg.jss.FlashPlayerExtractPackage/downloads/AdobeFlashPlayer.dmg is not mounted

Has anyone had this issue?  If so, how did you resolve?  Thanks!

**Comment by gregneagle** [comment]
Consider posting on autopkg-discuss as this is not a general forum monitored by autopkg users.
This is a place to report issues with the core Autopkg tool itself and not any specific recipe,

**Comment by jwzg** [comment]
Thanks Greg.  Sorry about that.

**Comment by gregneagle** [comment]
Not a problem -- you are most likely to get a useful/helpful response on the autopkg-discuss list.
