### ISSUE TITLE
Add support for .tar.xz to unarchiver

### ISSUE THREAD

**Issue by thenikola** [autopkg/autopkg#162]
tar.xz files are beginning to be more common, for example opera's update mechanism uses them.  It would be great if AutoPkg could handle this format.

On 10.10.1 "tar -xf" successfully decompresses the archive.  Unfortunately, this command does not work on 10.6.8.  These are the only 2 OSX versions that I currently have available currently so I was not able to find when tar.xz support was added to OSX.

**Comment by gregneagle** [comment]
So then the current Unarchiver should be able to unarchive these files, at least on 10.10.1, since it is calling `tar -xf`:

https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/Unarchiver.py#L125-L131

**Comment by thenikola** [comment]
Predictably, Greg is correct.  Unarchiver does not look for the tar.xz extension, but if you tell unarchiver to use tar as the archive_format unarchiver handles the file appropriately.

Thanks Greg
