### ISSUE TITLE
mode fails for chown in pkg creation

### ISSUE THREAD

**Issue by charliwest** [autopkg/autopkg#177]
Have created a recipe for TogglDesktop

https://github.com/charliwest/jss-recipes/blob/master/TogglDesktop.pkg.recipe

chown to 0755 fails when the recipe is run with the error
```Caught exception: AttributeError("'str' object has no attribute 'mode'",)
Failed.
The following recipes failed:
TogglDesktop.pkg.recipe
Error in com.github.autopkg.pkg.TogglDesktop: Processor: PkgCreator: Error: Caught exception: AttributeError("'str' object has no attribute 'mode'",)```

**Comment by timsutton** [comment]
Thanks! This was a hidden bug that looks like it was never triggered by any recipes, as it only affected changing permissions on a directory rather than a file.
