### ISSUE TITLE
List of all Keys available in pkginfo ?

### ISSUE THREAD

**Issue by Lotusshaney** [autopkg/autopkg#178]
Not really an Issue but is there a list of all the keys that are available for use in pkginfo ?

Managed to guess a few but a list of them would be good.

**Comment by timsutton** [comment]
This is a Munki-specific question, for which you can find the answer here:

https://github.com/munki/munki/wiki/Supported-Pkginfo-Keys

Note that when you use the MunkiImporter processor in AutoPkg, more of the pkginfo keys will be automatically generated based on the content of the item you give it, but taking your `pkginfo` input variable as a starting point.

**Comment by poundbangbash** [comment]
Not to reopen a closed issue but I have a LanguageModule for munki to use in TextWrangler/BBEdit to syntax highlight the approved keys in pkginfo if you go the route of hand editing the plists. Information on that can be found at https://github.com/poundbangbash/munki-language-module

**Comment by timsutton** [comment]
Munki's got a new "contrib" repo.. might be worth contributing this there: https://github.com/munki/contrib

**Comment by poundbangbash** [comment]
Interesting, is there a way to tie my repo to that one so I don't have to remember to update on the contrib  repo?
