### ISSUE TITLE
autopkg run reports wrong file in error message

### ISSUE THREAD

**Issue by jazzace** [autopkg/autopkg#179]
I was testing a new recipe and the following occurred:

````

$ autopkg run /Users/tech/Library/AutoPkg/Recipes/x.pkg.recipe 
WARNING: plist error for /Users/tech/Library/AutoPkg/Recipes/AdobeFlashPlayerDLA.install.recipe: 
Error Domain=NSCocoaErrorDomain Code=3840 "The data couldn’t be read because it isn’t in the correct format." (Close tag on line 40 does not match open tag array) UserInfo=0x7fe34ea29bc0 {NSDebugDescription=Close tag on line 40 does not match open tag array, kCFPropertyListOldStyleParsingError=The data couldn’t be read because it isn’t in the correct format.}
[…]

````

Notice the disconnect here: the recipe I am running is _not_ AdobeFlashPlayerDLA.install, nor does it ever refer to it.

Just as a debug check, I re-ran the same recipe by copying and pasting it into a new file and received the same result, just in case it was caching the path of the previous script that threw an error. I tried a bunch of other things that had no material effect.

I then checked the AdobeFlashPlayerDLA.install recipe and it did indeed have an error that should get flagged at line 40. When I fixed that and ran x.pkg.recipe, it did not throw an error.

Is this the expected behaviour?

(Erroneous) AdobeFlashPlayerDLA.install.recipe:
https://gist.github.com/jazzace/a0162070add3b82e4910#file-adobeflashplayerdla-install-recipe

**Comment by gregneagle** [comment]
"Is this the expected behaviour?"

Yes.

When looking for ParentRecipes, etc. AutoPkg has to scan all recipes in its search paths. If any of them have errors, you'll see WARNINGs for them.

Did /Users/tech/Library/AutoPkg/Recipes/x.pkg.recipe run as expected even if you saw a WARNING about /Users/tech/Library/AutoPkg/Recipes/AdobeFlashPlayerDLA.install.recipe ?

**Comment by jazzace** [comment]
Yes, it did.

I'm guessing it didn't show up before this because I took ~/Library/AutoPkg/Recipes out of the search path list (rightly or wrongly), so when I specified the full path for the recipe, it checked the entire directory and found the error. Does that sound about right?
