### ISSUE TITLE
Request to add recipes

### ISSUE THREAD

**Issue by robperc** [autopkg/autopkg#183]
I have a recipe repo I'd like to add to the community pool.
https://github.com/robperc/autopkg-recipes
Cheers!

---Rob

**Comment by timsutton** [comment]
Looks good. Just added them here:

https://github.com/autopkg/robperc-recipes

You may want to add .DS_Store to your .gitignore to keep it the repo tidy. Also, if you'd like to avoid duplicating your `KyngChaosURLProvider.py` you can also share it between recipes, as per https://github.com/autopkg/autopkg/wiki/Processor-Locations#shared-recipe-processors.
