### ISSUE TITLE
Request to share recipes

### ISSUE THREAD

**Issue by aysiu** [autopkg/autopkg#191]
I'm just a beginner with this recipe-writing business, but I created a few I didn't see in other repos.

**Comment by gregneagle** [comment]
Great! Could you give us a URL for the recipe repo you wish to share?

**Comment by aysiu** [comment]
Sure thing. Here it is:
https://github.com/aysiu/autopkg-recipes

**Comment by arubdesu** [comment]
Hey there, first and foremost 👍. However, pardon my 2¢:
- Would you rather send PR's to @sheagcraig and @hansen-m with the munki recipes? If not, it's usually recommended as a courtesy to make any other-repo dependencies explicit in your README
- It's up to you as to wether you'd find it worthwhile, but the [CodeSignatureVerification](https://github.com/autopkg/autopkg/wiki/Processor-CodeSignatureVerifier) processor helps check if installer pkgs or the app itself are signed, to help verify the implied safety of the software that's been downloaded. Note you'd need to bump the autopkg minimum version in the recipe if so.
- ...It's also totally up to you if you want to make pkg recipes for the folks in the community who use tools that would benefit from it being an option
And wow, LegoMindStorms writes a kernel extension to root /Sys AND bundles Silverlight? That must be fun to support!

Grain of salt with all the above, working recipes are greater than ideal recipes are greater than many recipes. Thanks! Allister

**Comment by sheagcraig** [comment]
Yeah-feel free to send me the Jin recipe. I don't support munki at work, so I usually don't write munki recipes, as I can't really test them.

**Comment by aysiu** [comment]
I'm kind of a novice here. What's a PR?

sheagcraig, the Jin recipe is right here:
https://github.com/aysiu/autopkg-recipes/blob/master/Jin/Jin.munki.recipe

I'll look into CodeSignatureVerification and .pkg recipes. For now, I'm just doing what's most helpful to my organization and then sharing it out. As I get more advanced, I may be able to just volunteer other stuff.

**Comment by arubdesu** [comment]
Pardon me, PR stands for pull request, which is like the currency of Github in the fact you'd be wrapping your code up in a bow like a present for the person on the receiving end to accept (and hopefully integrate).

**Comment by aysiu** [comment]
Thanks, arubdesu. I'm still figuring things out a bit. I tried to create a pull request for sheagcraig, but I wasn't quite sure what to put in to compare (pasting my URL in didn't work), and my repo isn't a fork of an existing repo.

**Comment by timsutton** [comment]
Finally added, here:

https://github.com/autopkg/aysiu-recipes

Allister's point about submitting changes for Jin and Kindle munki recipes in other repos is valid, although since Shea and Matt don't themselves use Munki, I'm not sure whether they would want to accept maintenance of Munki recipes. Sometimes people include other maintainers for recipes in their own repo, while others prefer to keep only recipes they feel they can support directly.

**Comment by aysiu** [comment]
Thanks, Tim. I think as I get more and more comfortable with the parameters of these AutoPkg recipes, I'll eventually fall more in line with established norms and protocols. We'll see how it goes.
