### ISSUE TITLE
Error with Unicode characters

### ISSUE THREAD

**Issue by ChrOst** [autopkg/autopkg#198]
Hi,

Sometimes, while editing/writing recipes you will get an error like this
```UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 202: ordinal not in range(128)```
which is the line 125 in autopkglib/__init__.py ... see the snippet below.
```"WARNING: plist error for %s: %s" % (filename, unicode(err)))```

Now I wanted to know where my error is inside the recipe, but the error message itsself which should tell me this, crashes. 
After fiddelin around a bit (I'm not a Python programmer (yet)) i found out that this snippet would atleast output the real error
```"WARNING: plist error for %s: %s" % (filename, unicode(err).encode('ascii', 'ignore')))```

After that atleast the good output can be seen and you can fix your recipe.
Today I was missing the closing dict-tag (</dict>) :-(

Since I dont really now if this is a proper fix - have a look at it and fix it please :)

**Comment by gregneagle** [comment]
This is the same issue as #111 -- closing it and following up in that issue.
