### ISSUE TITLE
RECIPE_SEARCH_DIRS

### ISSUE THREAD

**Issue by eahrold** [autopkg/autopkg#199]
in the RECIPE_SEARCH_DIRS default the first entry is always `'.'`. I'm guessing that the idea is users could just CD into a recipe directory without the need to ever do any repo-add (i.e no need to have git installed) and run recipes.

I was wondering if there was any other underlying reason for it being there that I'm missing?

Thanks.

**Comment by gregneagle** [comment]
Nope - that's it.
Typical unix tool call:

vi somefile.txt

opens "somefile.txt" in the current working directory.

Originally autopkg _only_ opened recipes by filename/pathname.  Later recipe search paths were added. So this preserves the original behavior when search paths were added.

**Comment by eahrold** [comment]
Great, thanks.

**Comment by gregneagle** [comment]
Ah -- so there is some file in the current directory that autopkg is trying to parse that is causing the above referenced issue?

I'm open to the ideas of modifying behaviors around this sort of thing, but think that's an excellent topic for the autopkg-discuss list.
