### ISSUE TITLE
PathDeleter is hyper-aggressive if run as root

### ISSUE THREAD

**Issue by nmcspadden** [autopkg/autopkg#200]
Yes, there's a warning not to run Autopkg as root.

Yes, running AutoPkg as root is dangerous.

However, PathDeleter goes **off the rails**.  Consider a recipe that does this:
```
<dict>
    <key>Processor</key>
    <string>PathDeleter</string>
    <key>Arguments</key>
    <dict>
        <key>path_list</key>
        <string>%RECIPE_CACHE_DIR%/%NAME%</string>
    </dict>
</dict>
```

When run as root, shutil.rmtree() decides to delete the *entire path*.

You get a result like this:
```
PathDeleter
{'Input': {'path_list': u'/Users/admin/Library/AutoPkg/Cache/local.munki.android_ndk/android_ndk'}}
Could not remove /: [Errno 66] Directory not empty: '/Applications'
Failed.
Receipt written to /Users/admin/Library/AutoPkg/Cache/local.munki.android_ndk/receipts/android_ndk-receipt-20150722-140003.plist

The following recipes failed:
    android_ndk.munki
        Error in local.munki.android_ndk: Processor: PathDeleter: Error: Could not remove /: [Errno 66] Directory not empty: '/Applications'
```

`Could not remove /:` is never something you want to see, ever, as part of recipe output.

While AutoPkg 0.5 does explicitly warn you not to run as root, the possibility that someone could just write a recipe and run as root that would nuke your whole drive is a very dangerous one.  Perhaps some safeguards should be put in to prevent this from happening?

**Comment by nmcspadden** [comment]
Perhaps AutoPkg should explicitly deny running as root?

**Comment by gregneagle** [comment]
What actually happened here? This looks like a malformed recipe. path_list above is _not_ a list of paths, you have a string.

**Comment by nmcspadden** [comment]
That seems to be the problem - the path list is a string and not an array.  While it is indeed a user error, the penalty for such an error seems rather severe.  Should that be guarded against / detected for?

**Comment by gregneagle** [comment]
A list looks like ['/path/to/foo', '/path/to/bar/', '/yet/another/path']

**Comment by gregneagle** [comment]
We should fix the processor first. Then we should discuss on autopkg-discuss your suggestion of making autopkg refuse to run if it is root. I don't know who that might break (or why)

**Comment by gregneagle** [comment]
So here's what PathDeleter is trying to delete in your case:
/
U
s
e
r
s
/
(etc)

**Comment by nmcspadden** [comment]
The docstring/variable description for for "path_list" in PathDeleter could also be made more explicit that an array is required.

**Comment by gregneagle** [comment]
So a PR fixing that would almost certainly be merged. Too bad your current job makes that so difficult.

**Comment by gregneagle** [comment]
"list" _is_ the Python term for what you are calling "array", but I get your point.

**Comment by gregneagle** [comment]
Addressed here: https://github.com/autopkg/autopkg/commit/6ed45b2ae0ee88e0b41aeef00783cbc6e7d1e14f

If you want to bring up the idea of preventing autopkg from running as root, please open a discussion on autopkg-discuss.

**Comment by gregneagle** [comment]
Changed the title since root really is not related to what is going on.

**Comment by gregneagle** [comment]
For future spelunkers, the recipe segment should have read:

```
<dict>
    <key>Processor</key>
    <string>PathDeleter</string>
    <key>Arguments</key>
    <dict>
        <key>path_list</key>
        <array>
            <string>%RECIPE_CACHE_DIR%/%NAME%</string>
        </array>
    </dict>
</dict>
```
