### ISSUE TITLE
Specify recipe in report-plist when items are imported into Munki

### ISSUE THREAD

**Issue by nmcspadden** [autopkg/autopkg#203]
Currently, the --report-plist option creates a useful summary.

Items that are downloaded contain the full path to the downloaded item, which includes the recipe cache name.

Items are fail contain the name of the recipe that failed.

Munki import items only contain the name of the item that was imported into Munki - which doesn't include the name of the recipe that succeeded.  In most cases, this can be deduced from the item name, but there can easily be situations where a recipe names something completely different from what the recipe title is/says, and this link is not intuitive.  

I think it would be ideal if all built in --report-plist options for fails, munki imports, and URL downloads were normalized to all include a key specifically naming the recipe that fulfills each option.

**Comment by gregneagle** [comment]
Sounds reasonable. A pull request that implemented this would probably be accepted...

**Comment by nmcspadden** [comment]
I'll see if I can crank that out in the next few days, thanks.

On Sun, Jul 26, 2015 at 1:00 PM, Greg Neagle <notifications@github.com>
wrote:

> Sounds reasonable. A pull request that implemented this would probably be
> accepted...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autopkg/autopkg/issues/203#issuecomment-125033681>.
>



-- 
--
Nick McSpadden
nmcspadden@gmail.com
