### ISSUE TITLE
Add patgmac-recipes repo

### ISSUE THREAD

**Issue by patgmac** [autopkg/autopkg#211]
Please fork my repo: https://github.com/patgmac/autopkg-recipes
Currently only AM recipes, but hope to add more non-AM, too.

Thanks

**Comment by arubdesu** [comment]
Hey Pat! You may want to call out the repo's that these recipes inherit from, e.g. @jleggat, @sheagcraig, @rtrouton, etc. 
autopkg will be helpful when it fails at the command line, but it won't necessarily be obvious in AutoPkgr.

**Comment by patgmac** [comment]
Sure thing, Allister. Should I put that in each recipe description, or just a list of credits in the README?

**Comment by arubdesu** [comment]
Just links in the readme would be a good idea, then if anyone opens an issue or asks you a question you can point them there.

**Comment by patgmac** [comment]
Got it. See updated readme.

**Comment by timsutton** [comment]
Done! Available here:

https://github.com/autopkg/patgmac-recipes
