### ISSUE TITLE
Installer Daemon won't run in El Capitan Beta 6 (or earlier)

### ISSUE THREAD

**Issue by grahampugh** [autopkg/autopkg#213]
When a recipe requires installation (e.g. a .install recipe), autopkg hangs. The reason appears to be that the com.github.autopkg.autopkginstalld launch daemon fails to run:

```
12/08/2015 17:54:51.090 com.apple.xpc.launchd[1]: (com.github.autopkg.autopkginstalld[4800]) Service exited with abnormal code: 1
12/08/2015 17:54:51.090 com.apple.xpc.launchd[1]: (com.github.autopkg.autopkginstalld) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
```

**Comment by gregneagle** [comment]
Please give the current GitHub code a whirl. You should be able to make yourself an installer package:

autopkg run AutoPkgGitMaster.pkg

Then install that package.

**Comment by grahampugh** [comment]
That fails too because com.github.autopkg.autopkgserver also fails to run:

```
12/08/2015 18:02:39.599 com.apple.xpc.launchd[1]: (com.github.autopkgserver[4875]) Service exited with abnormal code: 1
12/08/2015 18:02:39.599 com.apple.xpc.launchd[1]: (com.github.autopkgserver) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
```

**Comment by gregneagle** [comment]
You'll need to run the recipe on a machine where autopkg isn't broken.

**Comment by tbridge** [comment]
I have installed the latest build. I am getting a different, yet still unsatisfactory, result:

Antipodes:~ tom$ autopkg install AdobeReader
Processing AdobeReader.install...
/Users/tom/Library/AutoPkg/Cache/com.github.autopkg.install.AdobeReader/downloads/AdobeReader.dmg is not mounted
Failed.

The following recipes failed:
    AdobeReader.install
        Error in com.github.autopkg.install.AdobeReader: Processor: CodeSignatureVerifier: Error: /Users/tom/Library/AutoPkg/Cache/com.github.autopkg.install.AdobeReader/downloads/AdobeReader.dmg is not mounted

Nothing downloaded, packaged or imported.

In the logs I see:

8/12/15 6:25:43.000 PM kernel[0]: Sandbox: Python(51643) System Policy: deny(1) file-write-unlink /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/platform.pyc
8/12/15 6:25:43.000 PM kernel[0]: Sandbox: Python(51643) System Policy: deny(1) file-write-unlink /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/string.pyc
8/12/15 6:25:43.000 PM kernel[0]: Sandbox: Python(51643) System Policy: deny(1) file-write-unlink /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.pyc
8/12/15 6:25:43.000 PM kernel[0]: Sandbox: Python(51643) System Policy: deny(1) file-write-unlink /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.pyc
8/12/15 6:25:43.000 PM kernel[0]: Sandbox: Python(51643) System Policy: deny(1) file-write-unlink /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/struct.pyc
8/12/15 6:25:43.000 PM kernel[0]: Sandbox: Python(51643) System Policy: deny(1) file-write-unlink /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.pyc
8/12/15 6:25:43.000 PM kernel[0]: Sandbox: Python(51643) System Policy: deny(1) file-write-unlink /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.pyc
8/12/15 6:25:43.000 PM kernel[0]: Sandbox: Python(51643) System Policy: deny(1) file-write-unlink /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.pyc
8/12/15 6:25:43.000 PM kernel[0]: Sandbox: Python(51643) System Policy: deny(1) file-write-unlink /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/__future__.pyc
8/12/15 6:25:43.000 PM kernel[0]: Sandbox: Python(51643) System Policy: deny(1) file-write-unlink /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.pyc
8/12/15 6:25:43.000 PM kernel[0]: Sandbox: Python(51643) System Policy: deny(1) file-write-unlink /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.pyc
8/12/15 6:25:43.000 PM kernel[0]: Sandbox: Python(51643) System Policy: deny(1) file-write-unlink /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.pyc
8/12/15 6:25:43.000 PM kernel[0]: Sandbox: Python(51643) System Policy: deny(1) file-write-unlink /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.pyc
8/12/15 6:25:43.000 PM kernel[0]: Sandbox: Python(51643) System Policy: deny(1) file-write-unlink /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.pyc
8/12/15 6:25:43.000 PM kernel[0]: Sandbox: Python(51643) System Policy: deny(1) file-write-unlink /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.pyc
8/12/15 6:25:43.000 PM kernel[0]: Sandbox: Python(51643) System Policy: deny(1) file-write-unlink /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urlparse.pyc
8/12/15 6:25:43.000 PM kernel[0]: Sandbox: Python(51643) System Policy: deny(1) file-write-unlink /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/mimetools.pyc
8/12/15 6:25:43.000 PM kernel[0]: Sandbox: Python(51643) System Policy: deny(1) file-write-unlink /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/rfc822.pyc
8/12/15 6:25:43.000 PM kernel[0]: Sandbox: Python(51643) System Policy: deny(1) file-write-unlink /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.pyc
8/12/15 6:25:43.000 PM kernel[0]: Sandbox: Python(51643) System Policy: deny(1) file-write-unlink /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/textwrap.pyc
8/12/15 6:25:43.000 PM kernel[0]: Sandbox: Python(51643) System Policy: deny(1) file-write-unlink /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.pyc
8/12/15 6:25:43.000 PM kernel[0]: Sandbox: Python(51643) System Policy: deny(1) file-write-unlink /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/bisect.pyc
8/12/15 6:25:43.000 PM kernel[0]: Sandbox: Python(51643) System Policy: deny(1) file-write-unlink /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.pyc
8/12/15 6:25:44.000 PM kernel[0]: Sandbox: Python(51643) System Policy: deny(1) file-write-unlink /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_strptime.pyc
8/12/15 6:25:44.000 PM kernel[0]: Sandbox: Python(51643) System Policy: deny(1) file-write-unlink /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.pyc
8/12/15 6:25:44.000 PM kernel[0]: Sandbox: Python(51643) System Policy: deny(1) file-write-unlink /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/calendar.pyc

**Comment by grahampugh** [comment]
OK, works fine with 0.5.1.

**Comment by gregneagle** [comment]
Can this be closed, then?

**Comment by grahampugh** [comment]
Closed, assuming Tom's issue was resolved (I think I saw it was in Slack).
