### ISSUE TITLE
`autopkg info recipe-name` doesn't show parent information, running doesn't provide helpful output

### ISSUE THREAD

**Issue by arubdesu** [autopkg/autopkg#217]
For times that the README doesn't mention repo's that have parent recipes for a particular product, being able to inspect the recipe with the `autopkg info` verb would help. In addition, debug output when running the recipe is insufficient to explain why it is happening or how to correct:
```
autopkg info OracleJava8JDK.munki.recipe
Could not find parent recipe for OracleJava8JDK.munki.recipe
Can't find recipe OracleJava8JDK.munki.recipe, or it is invalid.
```
Propose adding `required parent recipe identifier: com.github.somebody.foo.bar`

**Comment by gregneagle** [comment]
? `autopkg info recipename` does show parent info!

**Comment by nmcspadden** [comment]
@gregneagle: The issue is that if the recipe is malformed in some way, or the parent recipe is missing, `autopkg info` doesn't show you any information about the recipe at all.  While it makes sense if the recipe is malformed that you probably shouldn't trust it, a missing parent recipe requires you to actually open up the recipe in a text editor to see what the issue might be.

**Comment by gregneagle** [comment]
A specific demo of the issue might prove helpful.
If a recipe is malformed to the point that FoundationPlist can't read it, autopkg isn't going to be able to help you much.

**Comment by nmcspadden** [comment]
@arubdesu provided an example.  In my recipe repo, OracleJava8JDK.munki requires hansen-m's OracleJava8JDK.download recipe.  If you do not have hansen-m's recipe repo added in your search path and you try to run `autopkg info OracleJava8JDK.munki`, you get the message @arubdesu showed.

**Comment by arubdesu** [comment]
Nothing to see here, old version of `autopkg`. My apologies for bother/confusion.
```
autopkg info OracleJava8JDK.munki.recipe
Didn't find a recipe for com.github.hansen-m.download.OracleJava8JDK.
Search GitHub AutoPkg repos for a com.github.hansen-m.download.OracleJava8JDK recipe? [y/n]: y

Name                               Repo                   Path                                    
----                               ----                   ----                                    
OracleJava8JDK.install.recipe      hansen-m-recipes       Oracle/OracleJava8JDK.install.recipe    
OracleJava8JDK.download.recipe     hansen-m-recipes       Oracle/OracleJava8JDK.download.recipe   
OracleJava8JDK.munki.recipe        nmcspadden-recipes     Oracle/OracleJava8JDK.munki.recipe      
OracleJava8JDK.pkg.recipe          novaksam-recipes       Recipes - pkg/OracleJava8JDK.pkg.recipe 

To add a new recipe repo, use 'autopkg repo-add <repo name>'
Could not find parent recipe for com.github.nmcspadden.OracleJava8JDK.munki
Could not find parent recipe for OracleJava8JDK.munki.recipe
```
