### ISSUE TITLE
UnicodeEncodeError - AutoPKG completely broken

### ISSUE THREAD

**Issue by jshirle2** [autopkg/autopkg#218]
Getting an error message **"[ERROR] UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 196: ordinal not in range(128)"** when I run the recipes. I use JSSImporter and all of my recipes are .jss recipes. I recently updated several versions up for AutoPKGR, JSS Importer and GIT. I didn't get these errors before. 

Here is the full log from console: 

```
  File "/usr/local/bin/autopkg", line 1651, in <module>

    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1645, in main

    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1419, in run_recipes

    search_github=make_suggestions)
  File "/usr/local/bin/autopkg", line 331, in load_recipe

    search_github=search_github)
  File "/usr/local/bin/autopkg", line 235, in locate_recipe

    recipe_file = find_recipe(name, override_dirs + recipe_dirs)
  File "/usr/local/bin/autopkg", line 190, in find_recipe

    return (find_recipe_by_identifier(id_or_name, search_dirs) or
  File "/Library/AutoPkg/autopkglib/__init__.py", line 142, in find_recipe_by_identifier

    if get_identifer_from_recipe_file(match) == identifier:
  File "/Library/AutoPkg/autopkglib/__init__.py", line 125, in get_identifer_from_recipe_file

    "WARNING: plist error for %s: %s" % (filename, unicode(err)))

UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 196: ordinal not in          range(128)
Aug 21 15:32:58 jss-server AutoPkgr[90185]: Error [1] Error running recipes 
 A Python exception occurred during the execution of autopkg, see the system log for more    details.

[ERROR] UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 196: ordinal not in range(128)
Aug 21 15:33:02 jss-server AutoPkgr[90185]: [DEBUG] Completed AutoPkg Task:
  /usr/bin/python /usr/local/bin/autopkg run Adobe DNG Converter.jss --report-plist   /var/folders/4z/myx02ftx79l7g711_3dp745m0000gn/T/com.lindegroup.AutoPkgr/20150821153258 -v
Aug 21 15:33:05 jss-server mdmclient[58]: *** ERROR *** [Daemon:0] Sending request to server (<NSURLErrorDomain:-1202> The certificate for this server is invalid. You might be connecting to a    server that is pretending to be “alias-server” which could put your confidential information at risk."
```

These erorrs happen when running **any** recipe. Whether I created an override for it or not. Anyone have any ideas?

**Comment by gregneagle** [comment]
This looks like autopkg is not properly handling a "smart quote" in an error message when trying report an error in the recipe plist.

% python -c "print u'\u2019'"
’

The bug needs to be fixed, but in the meantime you need to check all your recipes (I'd start with your overrides) for plist validation errors.

**Comment by jessepeterson** [comment]
One way to check recipes (or any plist file) for validation is to to `plutil -lint [plist file] [...]`. [plutil(1) man page](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/plutil.1.html)

**Comment by monosodium** [comment]
I'm sorry but I don't really know what you mean by plist validation errors.

**Comment by jessepeterson** [comment]
A property list (plist) is usually an XML document. An [XML document](https://en.wikipedia.org/wiki/XML) has a very rigid structure in how it can be formatted and what type of characters can be present or not. On top of a XML document a Property List XML file has a specific structure that it must be in as well. The `plutil` command will check that property lists are correctly structured.

**Comment by gregneagle** [comment]
Then do this: 
1 )rename your RecipeOverrides folder to RecipeOverrides.old. Create a new RecipeOverrides folder (leave it empty).

2) Run an autopkg recipe. Works? Great.

3) Move one recipe from RecipeOverrides.old to RecipeOverrides.

4) Run an autopkg recipe. Works? Return to step 3. Fails? The recipe you just moved is bad.

**Comment by arubdesu** [comment]
We know which it is, https://github.com/autopkg/jss-recipes/blob/master/Adobe%20DNG%20Converter/Adobe%20DNG%20Converter.jss.recipe
Fix the override, @homebysix and @sheagcraig aren't going to ship recipes that don't work, so

**Comment by homebysix** [comment]
@arubdesu Not sure what you mean. I don't see any `’` in that recipe, and it passes `plutil -lint`. Am I missing the error?

**Comment by monosodium** [comment]
Thanks for the suggestions guys!

@gregneagle Renaming the Recipes folder made all my recipes disappear. 

@jessepeterson Going to try Plist validation and will respond back here with results.

**Comment by gregneagle** [comment]
"@gregneagle Renaming the Recipes folder made all my recipes disappear."

That was the point.
This then would allow you to move recipes back one at a time or in small groups so you could tell which one was the culprit.

**Comment by eahrold** [comment]
@monosodium Also only rename the `RecipeOverrides` folder, not the `RecipeRepos` folder.

**Comment by monosodium** [comment]
Ah, I'm dense. Let me try that now.

**Comment by MIOResNet** [comment]
Hello,

We are running into the exact same error. 

<img width="426" alt="screen shot 2016-04-13 at 12 18 07 pm" src="https://cloud.githubusercontent.com/assets/15675845/14502626/cff85c6c-0171-11e6-9ff5-67ad3e830106.png">

We have tried

- Manually removing all AutoPkgr from the machine (all caches, laungedaemons, library files)
-Renaming the folders
-Recreating the folders
-Updating Git
-Updating MunkiCore

When you run the recipes on another computer with a fresh install of AutoPkg it works perfectly fine which leads me to believe it is not the recipes themselves but a problem with AutoPkg. 

Does anyone have a solution? Or perhaps can someone provide some insight into how to fully uninstall AutoPkgr and start from scratch.

**Comment by gregneagle** [comment]
You keep alternately referring to Autopkgr and AutoPkg, which are two different products/pkgs/installs.

Which are you looking for help with? If you need help with Autopkgr, this is not the place for that.

Did you look at the system.log for more details as indicated in the error message?

Do have a similar issue without using Autopkgr -- that is, when running autopkg from the command line?

**Comment by MIOResNet** [comment]
You are completely correct. I apologize. The issue is with AutoPkgr.

**Comment by macmule** [comment]
Adding a me too.

From AutoPKGr verbose:
```
 14/01/2017 22:36:41.335 AutoPkgr[17061]: [DEBUG] Completed AutoPkg Task:
  /usr/bin/python /usr/local/bin/autopkg run local.munki.AutoImagrNBI-dataJAR MakeCatalogs.munki --report-plist /var/folders/by/w61t5tks6j50k_wf53wyh9pr0000gp/T/com.lindegroup.AutoPkgr/20170114223153 -v --post io.github.hjuutilainen.VirusTotalAnalyzer/VirusTotalAnalyzer
14/01/2017 22:36:45.362 AutoPkgr[17061]: Processing local.munki.AutoImagrNBI-dataJAR...
14/01/2017 22:36:45.362 AutoPkgr[17061]: Run status: Processing local.munki.AutoImagrNBI-dataJAR...
14/01/2017 22:36:48.085 AutoPkgr[17061]: [DEBUG] Found app and version: AutoImagrNBI-1.3.4:1.3.4
14/01/2017 22:37:23.377 AutoPkgr[17061]: (FULL AUTOPKG TRACEBACK) 
  File "/usr/local/bin/autopkg", line 2407, in <module>
    
sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2401, in main
exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1939, in run_recipes
search_github=make_suggestions)
  File "/usr/local/bin/autopkg", line 342, in load_recipe
    search_github=search_github)
  File "/usr/local/bin/autopkg", line 242, in locate_recipe
    recipe_file = find_recipe(name, override_dirs + recipe_dirs)
  File "/usr/local/bin/autopkg", line 197, in find_recipe
return (find_recipe_by_identifier(id_or_name, search_dirs) or
  File "/Library/AutoPkg/autopkglib/__init__.py", line 141, in find_recipe_by_identifier
    if get_identifier_from_recipe_file(match) == identifier:
  File "/Library/AutoPkg/autopkglib/__init__.py", line 124, in get_identifier_from_recipe_file
    "WARNING: plist error for %s: %s" % (filename, unicode(err)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 196: ordinal not in range(128)
14/01/2017 22:37:23.377 AutoPkgr[17061]: Error [1] Error running recipes 
 A Python exception occurred during the execution of autopkg, see the system log for more details.
[ERROR] UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 196: ordinal not in range(128)
```

At times, running the recipe via ```autopkg run -vvv`` would fail with:
```
The following recipes failed:
    /Users/sadmin/Library/AutoPkg/RecipeOverrides/AutoImagrNBI-dataJAR.munki.recipe
        Error in local.munki.AutoImagrNBI-dataJAR: Processor: Unarchiver: Error: Unarchiving /Users/sadmin/Library/AutoPkg/Cache/local.munki.AutoImagrNBI-dataJAR/downloads/AutoImagrNBI-1.3.4.zip with ditto failed: ditto: Couldn't read PKZip signature
```

But re-running via command line would work... however recipe errors everytime via AutoPKGr as per:
<img width="406" alt="screenshot 2017-01-14 22 25 25" src="https://cloud.githubusercontent.com/assets/2464974/21958919/935bbce0-dab0-11e6-8595-c8c929c06927.png">

**Comment by macmule** [comment]
ok.. i removed the com.github.autopkg.dataJAR-recipes repo.. re-added (keeping original override).. & all is well

**Comment by homebysix** [comment]
@macmule: Why removing and re-adding the repo would solve anything is a mystery to me. Was the repo already up to date prior to being removed?

That is the most detailed traceback I've seen with regard to the "ordinal not in range" error:
```
  File "/Library/AutoPkg/autopkglib/__init__.py", line 124, in get_identifier_from_recipe_file
    "WARNING: plist error for %s: %s" % (filename, unicode(err)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 196: ordinal not in range(128)
```

Would be interesting to see the value of `err` at the time this happens.

**Comment by macmule** [comment]
@homebysix Sorry for the delay, created an issue over at AutoPKGr: https://github.com/lindegroup/autopkgr/issues/582

Looks like the removing & re-adding must have been a red herring.

**Comment by Moisie2000** [comment]
Hello:

I've been suffering this issue too, since updating to AutoPkg 1.0.1 and dealing with the trust issues therein. Please excuse my noobness - I'm a sys admin, with only novice-grade coding abilities...

From what I can see this issue is due to AutoPkgr not handling an error report from AutoPkg. Obviously AutoPkgr should be able to handle the error - but AutoPkg shouldn't be the source of the error in the first place... Here are my summarised findings:

I have an override for Keynote, based on Nick McSpadden's AppStore recipe. This worked fine before AutoPkg 1.0.1 - but I then added trust to it by running:

`autopkg update-trust-info AppStore-Keynote.munki`

After doing this, I verified trust with:

`autopkg verify-trust-info AppStore-Keynote.munki`

And got the response:

```
macserver:~ server_admin$ autopkg verify-trust-info AppStore-Keynote.munki
WARNING: plist error for /Users/server_admin/Library/AutoPkg/RecipeOverrides/AppStore-GarageBand.munki.recipe: Error Domain=NSCocoaErrorDomain Code=3840 "The data couldn’t be read because it isn’t in the correct format." (Encountered unexpected character w on line 24 while looking for open tag) UserInfo=0x7f830bd71f80 {NSDebugDescription=Encountered unexpected character w on line 24 while looking for open tag, kCFPropertyListOldStyleParsingError=The data couldn’t be read because it isn’t in the correct format.}
WARNING: plist error for /Users/server_admin/Library/AutoPkg/RecipeOverrides/AppStore-GarageBand.munki.recipe: Error Domain=NSCocoaErrorDomain Code=3840 "The data couldn’t be read because it isn’t in the correct format." (Encountered unexpected character w on line 24 while looking for open tag) UserInfo=0x7f830e428990 {NSDebugDescription=Encountered unexpected character w on line 24 while looking for open tag, kCFPropertyListOldStyleParsingError=The data couldn’t be read because it isn’t in the correct format.}
AppStore-Keynote.munki: OK
```

So two things of note here:

1. This command appears to be referencing the AppStore-GarageBand recipe - not the Keynote one;
2. The output contains "couldn’t" etc - which is the source of the Unicode characters which are throwing AutoPkgr out.

At present, I can't see why the Keynote recipe should be trying to reference the GarageBand file - happy to dig out any information that might help to indicate why.

I've just tried creating a brand new override for AppStoreApp.munki in AutoPkgr 1.4.2 - and that too is referencing the GarageBand override file - and failing verify-trust-info similarly.

So I've also tried making a new override (and one using a different parent recipe) using

`autopkg make-override VLC.munki`

...and using verify-trust-info, this is still trying to reference the GarageBand override file, and consequently failing.

So this is now where I'm out of my depth - but I hope it helps someone more skilled than I to find the issue!

Thanks.

**Comment by Moisie2000** [comment]
Just tried with autopkg 1.0.2 - same outcome: making an override for VLC resulted in it still trying to reference the GarageBand override file.

**Comment by gregneagle** [comment]
Fix your GarageBand override so that it is a valid plist. Since overrides and parent-child recipe relationships are tracked by recipe identifier and not filenames, autopkg must read every single recipe in its recipe search directories to parse them for recipe identifiers. Any invalid recipe file will cause errors or warnings, even if they are not directly related to the recipe you are currently working with/interested in.

**Comment by Moisie2000** [comment]
Hi Greg:

Many thanks for chiming in here. I wasn't sure if this was a generic issue or a system-specific issue - your explanation makes sense to me, so I'll go and fix the GarageBand override as you suggest!
