### ISSUE TITLE
URLDownloader use Last-Modified header?

### ISSUE THREAD

**Issue by jessepeterson** [autopkg/autopkg#219]
Over in autopkg/jessepeterson-recipes#19 it seems we found a webserver that responds with legitimate-looking `Last-Modified` headers but doesn't appear to respect a provided `If-Modified-Since` header (i.e. doesn't respond with a 304 response).

Would folks be open to some `Last-Modified` header-based detection? The URLDownloader processor already stores the last modified header in an extended attribute so we could simply read that and compare it to the newly given one.

**Comment by jessepeterson** [comment]
It appears the web server here is behaving as it should with regard to `If-Modified-Since` and `If-None-Match` headers. I believe the problem actually lies with The URLDownloader processor assuming that any matching file size is the same file (which it very appropriately does warn about) [here](https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/URLDownloader.py#L172).

However shouldn't this only be the assumption if there was no `Last-Modified` nor `ETag` on the download (because otherwise it should use those)? This diff makes that change:

```diff
diff --git a/Code/autopkglib/URLDownloader.py b/Code/autopkglib/URLDownloader.py
index bd76654..030bf6d 100755
--- a/Code/autopkglib/URLDownloader.py
+++ b/Code/autopkglib/URLDownloader.py
@@ -169,7 +169,7 @@ class URLDownloader(Processor):
             # Useful for webservers that don't provide Last-Modified
             # and ETag headers.
             size_header = url_handle.info().get("Content-Length")
-            if url_handle.info().get("Content-Length"):
+            if url_handle.info().get("Content-Length") and not url_handle.info().get('etag') and not url_handle.info().get("last-modified"):
                 if int(size_header) == existing_file_length:
                     self.env["download_changed"] = False
                     self.output("File size returned by webserver matches that "
```

Thoughts? This correctly downloads the file for me in the recipe.

**Comment by timsutton** [comment]
Thanks! This filesize check was originally added by me to support a Dropbox recipe, and all this time we've been falling back to checking filesize in every case regardless of whether ETags or Last-Modified was supplied properly.

I re-worked the if statements slightly for neatness, but if you can give it another look over and test master with this updated URLDownloader code that would be good.

**Comment by jessepeterson** [comment]
I ran it over my package collection without problems. I notice a couple items from SourceForge re-downloaded despite being the same previously downloaded packages. When I re-ran them a second time they correctly recognized as unchanged. Thanks!

**Comment by jessepeterson** [comment]
I just wanted to add that it looks like since the change a few of the recipes I use are needlessly re-downloading files that, in fact, have not changed. Culprits include OpenOffice, FileZilla, CUDA-Z, ProjectLibre. The three are hosted from SourceForge.

I haven't had time to investigate but I suspect that different mirrors or CDNs or whatever have different ETags or Last-Modifieds and as they get handed out (in round robin or whatever) it's luck of the draw which headers one gets and so URLDownloader assumes the package has changed and re-downloads.

**Comment by timsutton** [comment]
I've noticed this as well with a KomodoEdit recipe I have.

For cases where there are mirrors in play, maybe what's needed is for a recipe author to be able to _prefer_ the use of the filesize as the "is most recent download" check. Seems kind of ugly, but in cases where mirrors are involved the use of ETags and Last-Modified seem to be less useful for what they were intended.

**Comment by jessepeterson** [comment]
Yeah, good idea. Perhaps an array that you could combine to specify which comparators you want. A processor Argument something like:

```xml
<key>FileCompare</key>
<array>
	<!-- <string>Last-Modified</string> -->
	<string>ETag</string>
	<string>Size</string>
</array>
```

**Comment by timsutton** [comment]
Seems reasonable. I was thinking these would be processor args for URLDownloader/CURLDownloader. Currently Content-Length is the last resort, so I think if someone wants to ignore ETag and Last-Modified (like for the SF mirror situation) they can make the array contain only Content-Length (as long as we're using header names, may as well be consistent IMO).

**Comment by jessepeterson** [comment]
Agreed on all accounts.
