### ISSUE TITLE
directory not found for option

### ISSUE THREAD

**Issue by hac** [autopkg/autopkg#221]
Hello, I have downloaded the source code, changed the certificates and installed the cocoapods. When I try to install I get these two errors:

ld: warning: directory not found for option '-L/Users/scoobs/Library/Developer/Xcode/DerivedData/AutoPkgr-gvffmulnnaejibfmmwfptzyobmbb/Build/Products/Debug'
ld: library not found for -lMailCore
clang: error: linker command failed with exit code 1 (use -v to see invocation)

when building AutoPkgr.helper

Thank you!

**Comment by eahrold** [comment]
@hac This is an AutoPkgr issue not AutoPkg issue, go ahead and close it here and open the issue over there https://github.com/lindegroup/autopkgr thanks.
