### ISSUE TITLE
.install recipes fail on Mac OS X 10.8.5 and AutoPkg 0.5.1

### ISSUE THREAD

**Issue by homebysix** [autopkg/autopkg#226]
Running any .install recipe fails on 10.8.5 and AutoPkg 0.5.1. Verbose mode reveals that the recipe gets stuck on "InstallFromDMG: Sending installation request"

@gregneagle Found that 0.4.2 and 0.5.0 both work as expected, and theorized that the issue might be in here: https://github.com/autopkg/autopkg/commit/68f43663cb20f125b438a35638e108d9b8878ff7#diff-4ab93402efa62e08572ea68e027d227a

More details if needed, but I think Greg is working on a fix.

**Comment by gregneagle** [comment]
Fixed here: https://github.com/autopkg/autopkg/commit/f77d5bd3a0c77869fde1a67a9453cbef31d12bc1

**Comment by homebysix** [comment]
Confirmed, this fixed it for me in 10.8.5.
