### ISSUE TITLE
add/fork my repo

### ISSUE THREAD

**Issue by gilbertpalau** [autopkg/autopkg#227]
https://github.com/gilbertpalau/recipes.git

**Comment by timsutton** [comment]
Done, and available here:

https://github.com/autopkg/gilbertpalau-recipes

One suggestion: I know that Lightning gets updated infrequently, but you might try using a processor like URLTextSearcher to automatically fetch the DMG download link from [this url](https://www.filewave.com/products/imaging/lightning-thunderbolt), as opposed to hardcoding the 1.6 version download link in the recipe.

**Comment by gilbertpalau** [comment]
I'm going to read about that and update accordingly.  Thanks for the tip!

Sent from Outlook




On Thu, Sep 24, 2015 at 5:27 AM -0700, "Timothy Sutton" <notifications@github.com> wrote:












Done, and available here:



https://github.com/autopkg/gilbertpalau-recipes



One suggestion: I know that Lightning gets updated infrequently, but you might try using a processor like URLTextSearcher to automatically fetch the DMG download link from this url, as opposed to hardcoding the 1.6 version download link in the recipe.
