### ISSUE TITLE
bundles get re-imported

### ISSUE THREAD

**Issue by zordanarres** [autopkg/autopkg#230]
Using `<key>type</key><string>bundle</string>` in the installs array causes MunkiImporter to re-import the item during every run.

This seems to be caused by [235 MunkiImporter.py]
`applist = [item for item in pkginfo.get('installs', []) 
                   if item.get('type') in ('application', 'bundle') and 'path' in item]`

which tries to look for bundles in the to-be-imported item, but the `pkgdb` of the repo it performs the checks against is being built by only selecting applications according to [173 MunkiImporter.py]  
`if install.get('type') == 'application':`

**Comment by arubdesu** [comment]
Thank you for reporting this and digging in to what you think is the probable cause, do you have a recipe/product in specific the issue can be replicated with?

**Comment by zordanarres** [comment]
I had this issue with the attached recipe for a simple color picker extension.
As Github does not permit .recipe files, I had to add .txt as an extension

**Comment by zordanarres** [comment]
As Github's attachment function does not work for whatever reason, please find an example on [gist](https://gist.github.com/zordanarres/663db34c50c13ea1b5af) - please let me know if you have issues accessing the file

Obviously, any repo specific variables would need to be updated to reflect your test environment.

**Comment by timsutton** [comment]
Thanks - this would have been caused by a recent addition to the code. I'm not able to look closer at the moment, but will soon. If you feel like digging in and are able to test adding a check of bundles to the `pkgdb` in the meantime that might help.

**Comment by zordanarres** [comment]
I finally found some more time to look into this. I guess architecturally there are probably two options to get it resolved. Either bundles become part of the application list or they are being treated separately.

If a bundle is about to be matched, it ends up in [244 MunkiImporter.py] 
`match = pkgdb['applications'].get(app_path, {}).get(app_version)`
This comparison always returns false for bundles as they are currently not part of the application list.

A quick fix would be to add them to the application list like inserting
                    `if install.get('type') == 'application' or install.get('type') == 'bundle':`
to [173 MunkiImporter.py], although I'm not sure whether this approach makes sense in the grand schema of things or whether a dedicated if-statement just for bundles should be inserted into the make_catalog_db function. Thus, [244 MunkiImporter.py] would need to be changed too to also look into the list of bundles when performing the matching.

**Comment by zordanarres** [comment]
Unfortunately this issue still seems to persist in the latest version. Is there anything I can help with to move this forward?
