### ISSUE TITLE
SparkleUpdateInfoProvider encodes download links even if they're already encoded

### ISSUE THREAD

**Issue by homebysix** [autopkg/autopkg#231]
When presented with this Sparkle URL:
http://www.macbartender.com/B2/updates/Appcast.xml

Which includes this item:

```
<item>
<title>Version 2.0.3</title>
<sparkle:releaseNotesLink>
http://macbartender.com/B2/updates/2-0-3/rnotes.html
</sparkle:releaseNotesLink>
<pubDate>October 09, 2015 09:45:00 +0000</pubDate>
<enclosure url="http://macbartender.com/B2/updates/2-0-3/Bartender%202.zip" sparkle:version="213" sparkle:shortVersionString="2.0.3" length="2578993" type="application/octet-stream" sparkle:dsaSignature="MCwCFEeymrE8my28kSoGhVRIxpUscOPfAhRhlgDgkLMsTM3e0yXx3Oz1ABKOEg=="/>
</item>
```

SparkleUpdateInfoProvider passes a double-encoded URL to URLDownloader, which results in a 404 error.

```
SparkleUpdateInfoProvider
{'Input': {'appcast_request_headers': {
    "user-agent" = "Mozilla/5.0";
},
           'appcast_url': u'http://www.macbartender.com/B2/updates/Appcast.xml'}}
SparkleUpdateInfoProvider: Version retrieved from appcast: 213
SparkleUpdateInfoProvider: User-facing version retrieved from appcast: 2.0.3
SparkleUpdateInfoProvider: Found URL http://macbartender.com/B2/updates/2-0-3/Bartender%25202.zip
{'Output': {'url': 'http://macbartender.com/B2/updates/2-0-3/Bartender%25202.zip',
            'version': '2.0.3'}}
URLDownloader
{'Input': {'filename': u'Bartender.zip',
           'request_headers': {
    "user-agent" = "Mozilla/5.0";
},
           'url': 'http://macbartender.com/B2/updates/2-0-3/Bartender%25202.zip'}}
Couldn't download http://macbartender.com/B2/updates/2-0-3/Bartender%25202.zip (HTTP Error 404: Not Found)
```

Would it be possible for SparkleUpdateInfoProvider to notice that the download URL is already encoded and pass it along as-is if so?

**Comment by timsutton** [comment]
When I last looked into how Sparkle was handling URL quoting (probably at least a year ago), it was automatically url-quoting enclosure URLs, and I think I modified the Sparkle AutoPkg processor to do the same.

But, perhaps Sparkle is being smarter about it and trying to detect something that was already quoted so as to avoid doing it twice. Could you look into how Sparkle would handle a URL like this?

**Comment by homebysix** [comment]
@timsutton Does [this](https://github.com/sparkle-project/Sparkle/issues/659#issuecomment-148861104) help?

Would removing the quoting and re-adding it (as Sparkle currently does) help with the Bartender example above?

**Comment by timsutton** [comment]
That does help, yes - a simple way to do roughly the equivalent of what Sparkle is doing there would be probably just to first `urllib.unquote()` before the `urllib.quote()`, and then test against the Bartender download recipe (and then other Sparkle-based recipes).

**Comment by timsutton** [comment]
One could also probably use the NS methods via PyObjC, but for something like this it would be nice to keep it OS-agnostic (even though I'm not sure anything besides OS X apps can use Sparkle feeds...)

**Comment by futureimperfect** [comment]
There is a Sparkle port for Windows, although I'm not sure that matters in this case.

http://winsparkle.org

-- 
James Barclay

**Comment by pornel** [comment]
Sparkle 1.5 (a very old version, but still in use) always quotes, so the only way to be compatible with all versions of Sparkle is not to have any "%" in the URL (only use URL-safe filenames, no spaces).

In Sparkle I'd like to eventually move away from trying to "fix" the URLs and use them as-is. Would that cause any problems for you? I might be able to add some extra XML attribute to control this behavior.

**Comment by timsutton** [comment]
When I first wrote AutoPkg's Sparkle "provider" I also thought that in some cases Sparkle was being too forgiving, though that was partly to do with how it would attempt to guess versions from an enclosure's URL if the version-related attributes didn't exist - I'm not sure that's still the case.

But yes, I think with a system like this it's preferable to be more strict. It's always possible to also ship a script or binary that developers can use to audit their feed to make sure the expected attributes are there and in the correct format, whether there are any issues with the URLs, etc. Homebrew has done this sort of thing for a while for accepting PRs to formulae and it seems to have made their definitions much more consistent and reliable.

**Comment by timsutton** [comment]
@homebysix Given what @pornel said, have you contacted Bartender to mention their feed stands out as non-standard? I'm thinking the implications of a change to SparkleUpdateInfoProvider that affects potentially hundreds of recipes (half of which may be probably yours) - which seems like it may be safe - is maybe not worth doing for a single oddly-configured feed.

**Comment by homebysix** [comment]
@timsutton Agreed, and I've contacted the Bartender team to let them know.
