### ISSUE TITLE
Filewave recipe / importer repo request

### ISSUE THREAD

**Issue by johncclayton** [autopkg/autopkg#232]
Hi

I'd like to have my personal repo that contains the Filewave importer copied into the autopkg repo - making it more official. 

My repo is at: https://github.com/johncclayton/filewave-recipes

Let me know if there's anything I need to do. 

Thanks.

**Comment by gregneagle** [comment]
What should the repo name be?

"filewave-recipes" might be too generic (people might assume _all_ Filewave recipes will be here, or that this is the "official" Filewave corporate repo

'johncclayton-recipes' is more in keeping with other repos, but you may not want to tie it tightly to your name.

Either is fine (or some third name) -- just looking for confirmation.

**Comment by johncclayton** [comment]
I don’t really want to be famous - so removal of the name is fine. 

I was thinking to provide a focus that this is filewave specific stuff, the name would be: 
	autopkg/filewave

Maybe a quick question first - the recipes folder contains the “officlal” filewave processor - so is that something that stays in this repo or should it be folded into something else?  I assume it stays as that makes it easier for me to apply fixes or upgrades as I see fit on our own schedule. 

Thank you,






John Clayton
CTO
---------------------------
FileWave (Europe) GmbH
St. Gallerstrasse 1
CH - 9500 Wil
 
Phone: +41 71 914 30 80
Fax: +41 71 914 30 81
Web: www.filewave.com <http://www.filewave.com/>
Skype: johncclayton

**Comment by gregneagle** [comment]
Forked here: https://github.com/autopkg/filewave

**Comment by homebysix** [comment]
That makes the "filewave" repo the only one in the autopkg organization that doesn't end with "-recipes," besides the actual AutoPkg project repo. Setting a precedent?

If that doesn't bother @gregneagle, then I'll get over it.

**Comment by gregneagle** [comment]
It doesn't bother @gregneagle.

**Comment by gregneagle** [comment]
autopkg/recipes doesn't end in -recipes :-)

**Comment by timsutton** [comment]
No problems here either. We always considered there may be some other purpose-built repos that house more specific things like a set of shared processors or some otherwise special sets of recipes.

**Comment by homebysix** [comment]
Cool. Over it.

**Comment by johncclayton** [comment]
Ok, cool - thanks guys.  Appreciate the fast turnaround too.
