### ISSUE TITLE
Please fork my autopkg recipe repo.

### ISSUE THREAD

**Issue by jbaker10** [autopkg/autopkg#233]
https://github.com/jbaker10/recipes.git

**Comment by timsutton** [comment]
Thanks! A couple small things:

* The descriptions for EndNoteX7 and EndNoteX7Updates recipes are identical. I can take a guess as to when I'd want one or the other, but if one is only used to get the base application and the other's only for the updates, this should be grok-able by someone who runs `autopkg info` on your recipes.
* I'd recommend changing the filenames of the AcronisAccess recipes to match the same naming convention of other .download, .pkg, and .absolute recipes. Identifiers look fine (and there are no hard and fast style rules about those anyway, so long as they don't change once in the wild).

**Comment by jbaker10** [comment]
Thanks @timsutton, excellent point on the description differences. I have made changes to try and distinguish better, please feel free to read over and advise on further changes.

I have also made the recipe name changes for the Acronis recipes, as well as updated those descriptions as well.

Thanks for taking a look!

**Comment by timsutton** [comment]
Sorry, I forgot about this one. Done, and available here:

https://github.com/autopkg/jbaker10-recipes

Thanks!
