### ISSUE TITLE
Autopkg Failing after JSS Importer Install

### ISSUE THREAD

**Issue by 17-5** [autopkg/autopkg#234]
Have managed to reduce the number of fails I get from about 20 down to 4 but haven't been able to get past these.
`  File "/usr/local/bin/autopkg", line 44, in <module>
    import autopkglib.github`
`  File "/Library/AutoPkg/autopkglib/__init__.py", line 622, in <module>
    import_processors()`
`  File "/Library/AutoPkg/autopkglib/__init__.py", line 530, in import_processors
    mydirname + '.' + name, fromlist=[name]), name)`
`  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 28, in <module>
    import jss`

Originally installed from the AutoPkgr utility and ran into many more errors outside of this. Reinstalled everything via pip and easy_install and now I'm down to this.
Using Python 2.7.10, AutoPKG 0.5.1 and JSSImporter 1.4.0 -- Couldn't decide if this was an Autopkg issue or a JSS Importer issue.

Thanks.

**Comment by gregneagle** [comment]
Looks like JSSImporter is complaining it cannot do `import jss`.

Looks like it's not a core autopkg issue.

**Comment by 17-5** [comment]
You are quick sir! That's what I figured, I'll check with them and see what I can find out.

Thank you!
