### ISSUE TITLE
Recipe fork request

### ISSUE THREAD

**Issue by flammable** [autopkg/autopkg#239]
I started a recipe repository here:

https://github.com/flammable/flammable-recipes

Any chance you'd be willing to fork that?  It's just the one recipe now, but my intention is to make more.

Thanks!

Mike

**Comment by timsutton** [comment]
Thanks Mike, my only concern is the icons also included in the repo - I know Recipe Robot outputs these for you, although that doesn't mean we also have the rights to redistribute them.

**Comment by flammable** [comment]
Thanks, Tim!  That totally makes sense - I just removed them.

**Comment by timsutton** [comment]
Done, and available here:

https://github.com/autopkg/flammable-recipes

**Comment by flammable** [comment]
Thanks, Tim! :)
