### ISSUE TITLE
Request for repo

### ISSUE THREAD

**Issue by ygini** [autopkg/autopkg#240]
Hi folks

I would like to publish my repo on the official list, the original repo is here https://github.com/ygini/ygini-recipes

**Comment by timsutton** [comment]
Just added a new team for you but had an authentication failure midway on pushing the new repo - bear with me, I'll need to try this again..

**Comment by timsutton** [comment]
Looks like all that failed was the final push, and after a few minutes it worked:

https://github.com/autopkg/ygini-recipes
