### ISSUE TITLE
Java 8 Recipe only seeing u65 and not u66

### ISSUE THREAD

**Issue by majorsl** [autopkg/autopkg#242]
It looks like Oracle is now keeping two versions posted instead of just the one release:

http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

I don't recall them doing this before.  If so, it looks like the Java8 download recipe is only downloading the first one listed.

**Comment by gregneagle** [comment]
`autopkg info OracleJava8.download`

**Comment by gregneagle** [comment]
See also:
https://github.com/autopkg/recipes/issues/124
http://www.oracle.com/technetwork/java/javase/terms/license/index.html
https://groups.google.com/d/topic/autopkg-discuss/7GOxCocZPak/discussion

Closing.

**Comment by timsutton** [comment]
They've never done this before, no. It may have been not planned to have happened this way, but I'm not sure how we would know.

A workaround for this case is to download u66 yourself and pass it directly:

`autopkg run --pkg /path/to/download.dmg OracleJava8.munki`

**Comment by gregneagle** [comment]
It's hard for autopkg (and us!) to tell the difference between a current mistake or oversight and an official change in policy or pattern. Right now I elect to assume Oracle's documentation here (http://www.oracle.com/technetwork/java/javase/downloads/cpu-psu-explained-2331472.html) is still accurate. We can re-evaluate if updated documentation is published or a new pattern becomes apparent over time.
