### ISSUE TITLE
Repo fork/add request

### ISSUE THREAD

**Issue by andrewvalentine** [autopkg/autopkg#246]
https://github.com/andrewvalentine/autopkg-recipes

**Comment by arubdesu** [comment]
Hey there, thanks for adding these! I can see you have a hardcoded URL in the chromecast recipe, would you like assistance with maybe finding a more permanent way to get the latest release?
Also, while it's totally up to you to add, many folks use [CodeSignatureVerification](https://github.com/autopkg/autopkg/wiki/Using-CodeSignatureVerification) on pkgs or app bundles, especially for when they're (1. available, 2. the newer signature version, and 3.) being fetched over http, as it is with chromecast. That app's signature is the following, for instance:
```
anchor apple generic and identifier "com.google.chromecast.setup" and (certificate leaf[field.1.2.840.113635.100.6.1.9] /* exists */ or certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = EQHXZ8M8AV)
```
Cheers, see you around in Slack!

**Comment by andrewvalentine** [comment]
Hello!

Thanks for the info. Not used CodeSignatureVerification before, so gave it a go. Now added verification to Panoply, Twitterrific and Ghostlab download recipes. LastFM doesn't support it (still using "Sealed Resources" v.1).

Checked, and Chromecast isn't actually available as a Mac app at the moment - mobile and Chrome extension only. Removed Chromecast repo. Will revisit (maybe) if Google release a revised app.

Thanks again!

Andrew

**Comment by timsutton** [comment]
Looks good, although I'd recommend removing the Twitterrific recipes as they already exist in a [public recipe repo](https://github.com/autopkg/homebysix-recipes/blob/master/Iconfactory/Twitterrific.download.recipe), unless they are in some way different than Elliot's?

**Comment by andrewvalentine** [comment]
Ah, didn't notice there were Twitterrific recipes already available. Removed mine now.

**Comment by timsutton** [comment]
Great. Done, ready here:

https://github.com/autopkg/andrewvalentine-recipes
