### ISSUE TITLE
Please add my repo

### ISSUE THREAD

**Issue by kitzy** [autopkg/autopkg#249]
https://github.com/kitzy/kitzy-recipes

**Comment by timsutton** [comment]
The ChefDK.pkg recipe plist is invalid:

```
WARNING: plist error for /Users/tsutton/Library/AutoPkg/RecipeRepos/com.github.kitzy.kitzy-recipes/ChefDK/ChefDK.pkg.recipe: Error Domain=NSCocoaErrorDomain Code=3840 "Found non-key inside <dict> at line 11" UserInfo={NSDebugDescription=Found non-key inside <dict> at line 11, kCFPropertyListOldStyleParsingError=Error Domain=NSCocoaErrorDomain Code=3840 "Malformed data byte group at line 1; invalid hex" UserInfo={NSDebugDescription=Malformed data byte group at line 1; invalid hex}}
```

Because this recipe depends on Nick's recipes, you should probably include a note in the README or recipe `Description` to that effect. (Or alternatively, seeing if Nick wants to take a PR to add the pkg recipe to his repo instead)

**Comment by kitzy** [comment]
The plist has been fixed, and the description has been updated.

**Comment by timsutton** [comment]
Thanks, and sorry for the long delay in adding your repo!

Available here:

https://github.com/autopkg/kitzy-recipes
