### ISSUE TITLE
weird issue: TypeError: string indices must be integers

### ISSUE THREAD

**Issue by andreweo** [autopkg/autopkg#253]
I try to run autopkg run -v ~/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/Mozilla/Firefox.install.recipe 

but get:

Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 1662, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1656, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1422, in run_recipes
    search_github=make_suggestions)
  File "/usr/local/bin/autopkg", line 348, in load_recipe
    search_github=search_github)
  File "/usr/local/bin/autopkg", line 332, in load_recipe
    search_github=search_github)
  File "/usr/local/bin/autopkg", line 236, in locate_recipe
    recipe_file = find_recipe(name, override_dirs + recipe_dirs)
  File "/usr/local/bin/autopkg", line 191, in find_recipe
    return (find_recipe_by_identifier(id_or_name, search_dirs) or
  File "/Library/AutoPkg/autopkglib/__init__.py", line 141, in find_recipe_by_identifier
    if get_identifier_from_recipe_file(match) == identifier:
  File "/Library/AutoPkg/autopkglib/__init__.py", line 126, in get_identifier_from_recipe_file
    return get_identifier(recipe_plist)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 108, in get_identifier
    return recipe["Identifier"]
TypeError: string indices must be integers

I have retried reinstalling autopkg and autopkgr by removing the following files, and reinstalling it again, but it didn't help...

/Library/Autopkg
/Applications/AutoPkgr.app
4 plists in /Library/LaunchDaemons

The prefs in ~/Library/Preferences/com.github.autopkg.plist
and in ~/Library/Preferences/com.lindegroup/AutoPkgr
and ~/Library/Application Support/AutoPkgr

and of course ~/Library/AutoPkg

Does anyone have a solution.
It has worked for me on this machine, and on a virtual machine I have it working (for now)
but I want it to work again on this machine

Help would be much appreciated

**Comment by gregneagle** [comment]
> On Mar 1, 2016, at 10:20 AM, andreweo <notifications@github.com> wrote:
> 
> I try to run autopkg run -v ~/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/Mozilla/Firefox.install.recipe
> 
> but get:
> 
> Traceback (most recent call last):
> File "/usr/local/bin/autopkg", line 1662, in 
> sys.exit(main(sys.argv))
> File "/usr/local/bin/autopkg", line 1656, in main
> exit(subcommands[verb]'function' <x-msg://257/argv>)
> File "/usr/local/bin/autopkg", line 1422, in run_recipes
> search_github=make_suggestions)
> File "/usr/local/bin/autopkg", line 348, in load_recipe
> search_github=search_github)
> File "/usr/local/bin/autopkg", line 332, in load_recipe
> search_github=search_github)
> File "/usr/local/bin/autopkg", line 236, in locate_recipe
> recipe_file = find_recipe(name, override_dirs + recipe_dirs)
> File "/usr/local/bin/autopkg", line 191, in find_recipe
> return (find_recipe_by_identifier(id_or_name, search_dirs) or
> File "/Library/AutoPkg/autopkglib/init.py", line 141, in find_recipe_by_identifier
> if get_identifier_from_recipe_file(match) == identifier:
> File "/Library/AutoPkg/autopkglib/init.py", line 126, in get_identifier_from_recipe_file
> return get_identifier(recipe_plist)
> File "/Library/AutoPkg/autopkglib/init.py", line 108, in get_identifier
> return recipe["Identifier"]
> TypeError: string indices must be integers
> 
You have a bad recipe in your recipe search paths.

**Comment by homebysix** [comment]
@andreweo Assuming your recipes are in ~/Library/AutoPkg, you could run this to lint all of them in one shot:
```
find ~/Library/AutoPkg -iname "*.recipe" -type f -exec plutil -lint "{}" \;
```

Of course the current working directory (`.`) is also in the autopkg search path, so check wherever you're executing autopkg from to see whether you have any stray recipes there. Sometimes I forget about the recipes on my ~/Desktop for example.

**Comment by andreweo** [comment]
> Of course the current working directory (.) is also in the autopkg search path, so check wherever you're executing autopkg from to see whether you have any stray recipes there
I didn't realise that!
Hours of work troubleshooting....
Solution: going to cd ~/Library/AutoPkg/ in stead of ~

Thank you sooooo much for the help! and answer!

p.s: what does linting do?

**Comment by andreweo** [comment]
I also found out which (junk) recipes (which I had stored in the home-directory) I needed to throw away.
Thanks.

**Comment by homebysix** [comment]
[`plutil -lint`](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/plutil.1.html) checks for syntax errors in plist files.

**Comment by andreweo** [comment]
Thanks!!
