### ISSUE TITLE
Microsoft-Recipes repo is ready for forking, please add

### ISSUE THREAD

**Issue by arubdesu** [autopkg/autopkg#255]
Between myself, @ftiff, @patgmac, @jbaker10, @jazzace and @rtrouton, we've collaborated on many permutations for the many flavors of microsoft updates. I've tested all of these and their major input options up through the munki flavors, and am ready to remove the Lync, MAU, and SKUless recipes from my repo once accepted. 
https://github.com/arubdesu/microsoft-recipes
Sounds good?

**Comment by ftiff** [comment]
Thanks a lot Allister for your hard work!

**Comment by arubdesu** [comment]
Currently we're discussing if identifiers should retain the unique labels I've assigned - My take is that the original recipes should be considered deprecated, but not removed. The identifier becomes a signifier of the fact it uses the forked version @ftiff and I collaborated on if an issue occurs, and it also signifies to users that there are different capabilities (in specific the standalone override variant) which aren't available in the core version. Can other folks like @jbaker10 and co. weigh in?

**Comment by rtrouton** [comment]
Are we discussing keeping the `com.github.autopkg.microsoft-recipes` IDs in the https://github.com/arubdesu/microsoft-recipes repo? If so, I'm in favor of doing so.

**Comment by jbaker10** [comment]
I'm in agreement with @rtrouton, I like the idea of keeping the `microsoft-recipes` in the identifier. Is the plan to keep them in a separate repo called `microsoft-recipes` as they are on your github @arubdesu, or merge with `MSOfficeUpdates`?

**Comment by arubdesu** [comment]
Getting the repo forked under the autopkg org is the intent of this issue, with everyone who's contributed so far added with commit access. Perhaps @ftiff doesn't want to be included at the moment and leave the steering of the jss recipe flavors to someone (@rtrouton? @homebysix?), but otherwise it's probably fine whoever gets to needed updates first.

**Comment by homebysix** [comment]
If the JSS flavors of these recipes match the [expected behavior](https://github.com/autopkg/jss-recipes#standard-workflow-for-jss-recipes) of [jss-recipes](https://github.com/autopkg/jss-recipes), I'd be happy to host them there.

**Comment by arubdesu** [comment]
@homebysix make it so, number one

**Comment by timsutton** [comment]
The idea was to put all the different "flavors" of Office 2016 recipes (since there are different updates/installers, and different systems to send them to) all in one place. For consistency's sake I'd also move the 2016 recipes that are currently in `autopkg/recipes` over to this new repo.

I was going to argue that putting the .jss recipes again off in their own repo that this seems confusing again, but if [jss-recipes](https://github.com/autopkg/jss-recipes) is the de facto place for all .jss recipes to live...

**Comment by arubdesu** [comment]
@timsutton pardon, we chatted it out in Slack and are all leaning towards keeping it in here is indeed easier from a support perspective, PR's can address bringing the existing ones in line with the documented standard .jss recipe workflow.

**Comment by ftiff** [comment]
@homebysix they don't match the expected behaviour of jss-recipes. I believe they should, even if we host them outside of jss-recipes repo for the reasons stated above. I'm incredibly busy these days, but I  might be able to squeeze an hour to do this this week.

**Comment by homebysix** [comment]
After the fork is created, I'll submit a PR that makes them behave like jss-recipes (create a Self Service policy scoped to a group called Testing).

**Comment by arubdesu** [comment]
ok, changed the name and updated, trying this request again: https://github.com/arubdesu/office-recipes

**Comment by arubdesu** [comment]
Pardon the bump...

**Comment by nmcspadden** [comment]
*coughs politely*

**Comment by gregneagle** [comment]
_offers throat lozenge_
