### ISSUE TITLE
Download permissions on most DMGs are incorrect

### ISSUE THREAD

**Issue by ahaupt11** [autopkg/autopkg#258]
Most DMGs that are downloaded are being downloaded with incorrect permissions. Specifically, they're getting 600, which when imported into Munki leaves it unable to download as an update do to being "Forbidden". Confirmed with two fresh installs that this does not occur with the same recipe in v0.5.2. For your reference, I was using com.github.hansen-m.download.RStudio.

Thanks in advance!

**Comment by timsutton** [comment]
Thanks! Fixed in https://github.com/autopkg/autopkg/commit/6e078114ff6ec65ac5c0aa615f499bf0b7f865e5, released as 0.6.1.
