### ISSUE TITLE
Some recipes

### ISSUE THREAD

**Issue by prochat** [autopkg/autopkg#259]
Hello,

I've made some recipes ... some are for internal use, but some of them could be of public interest like LeJOS and FreeMind:
https://github.com/prochat/autopkg-recipes

(Eclipse GyMo is a recipe that force eclipse to download plugins for LeJos, and it's calling another recipe as parent ...)

Ph.R.

**Comment by timsutton** [comment]
Thanks, sorry for the delay getting to this.

Looks good, though I'd recommend documenting the repo that the Eclipse GyMo .pkg recipe depends on, at least via the recipe's `Description` key.

Repo available here:

https://github.com/autopkg/prochat-recipes

**Comment by prochat** [comment]
Hello,

Sure, I’ll document it as you suggest. I’ll re-clone the repo and work on that asap.

Regards,
Ph.R.

**Comment by prochat** [comment]
Hello,

I’m trying to do some documentation, but I cannot push … 
What’s the procedure for contributing ?

Regards,
Ph.R.

**Comment by prochat** [comment]
Stupid question … sorry. I just had to accept the invitation.
Everything is ok.

Regards,
Ph.R.
