### ISSUE TITLE
Please add my repo

### ISSUE THREAD

**Issue by nzmacgeek** [autopkg/autopkg#260]
Hi there,

I have the single recipe right now, but I am writing all sorts of recipes for my work.
My repo: https://github.com/nzmacgeek/nzmacgeek-recipes

Let me know what may need extra consideration.

William

**Comment by gregneagle** [comment]
Some comments:

1) Filemaker.download.recipe says "Downloads latest FileMaker Pro disk image and extracts the package." when it actually downloads the latest Filemaker _update_, and not a full installer..  Consider updating the description.

2) This: https://github.com/nzmacgeek/nzmacgeek-recipes/blob/master/FileMaker/FilemakerUpdateURLProcessor.py#L157 sprays a lot of output to the terminal. Consider getting rid of this line and just relying on the -v, -vv and -vvv flags to see this information when desired.

But generally -- looks good!

**Comment by nzmacgeek** [comment]
Thanks for your feedback @gregneagle. I've taken those into account and included them in the latest commits.

**Comment by nzmacgeek** [comment]
Just so you are aware, further recipes have now been published:
- NVivo for Mac
- Osculator

More are being added as I automate most of our packaging for UoA.

**Comment by timsutton** [comment]
Thanks! Your repo can be found at:

https://github.com/autopkg/nzmacgeek-recipes
