### ISSUE TITLE
source_item instead of source_path on InstallFromDMG wiki page

### ISSUE THREAD

**Issue by MichalMMac** [autopkg/autopkg#261]
I think there is an error on InstallFromDMG documentation page

> description: Array of dictionaries describing what is to be copied. Each item should contain 'source_path' and 'destination_path', and may optionally include: 

There should be probably source_item instead of source_path. Path is already defined by dmg_path variable. I was not able to get it working with source_path. 

Existing recipes use source_item:
https://github.com/autopkg/recipes/blob/master/Mozilla/Firefox.install.recipe
https://github.com/autopkg/recipes/blob/master/Skype/Skype.install.recipe

**Comment by gregneagle** [comment]
Fixed: https://github.com/autopkg/autopkg/commit/094fbb34578e8a2cd9cfa3ed858ca49520d34628

**Comment by gregneagle** [comment]
Note: the wiki processor docs are auto-generated from the descriptions in the actual processors, and are tied to official releases, so the wiki documentation will lag here until there is a release.
