### ISSUE TITLE
Request to add recipe repo

### ISSUE THREAD

**Issue by MichalMMac** [autopkg/autopkg#262]
Please add my recipes located at https://github.com/MichalMMac/autopkg-recipes

**Comment by timsutton** [comment]
Thanks, and great work documenting the details of the recipes in the READMEs!

We recommend authors put any pertinent info (for example, your details about [Mira](https://github.com/MichalMMac/autopkg-recipes/blob/master/Mira/README.md)) in the recipe's `Description` key. It doesn't need to be exhaustive, but it should point out anything the recipe does that's not completely self-explanatory. The expectation is that someone should be able to do `autopkg info <recipe name>` and have available any important details.

Available here:

https://github.com/autopkg/MichalMMac-recipes

**Comment by MichalMMac** [comment]
Thank you.
I updated  description in recipes where it made sense.
