### ISSUE TITLE
.pkg recipe PkgCreator Error: Invalid package name when name string contains a + sign.

### ISSUE THREAD

**Issue by goobersmooch** [autopkg/autopkg#271]
When creating a app.pkg.recipe, if the app name contains '+', it fails with Error Processor: PkgCreator: Error: Invalid package name

Example excerpt from pkg.recipe that fails with the error:
	`<key>Input</key>`
	`<dict>`
		`<key>BUNDLE_ID</key>`
		`<string>app.name</string>`
		`<key>NAME</key>`
		`<string>App.Name+</string>`
	`</dict>`

Example excerpt from pkg.recipe that builds correctly:
	`<key>Input</key>`
	`<dict>`
		`<key>BUNDLE_ID</key>`
		`<string>app.name</string>`
		`<key>NAME</key>`
		`<string>App.Name</string>`
	`</dict>`

**Comment by gregneagle** [comment]
That's expected, if undocumented behavior.

https://github.com/autopkg/autopkg/blob/master/Code/autopkgserver/packager.py#L44

The packaging script has a pretty narrow definition of a "legal" package name, and there are many characters that will trigger this error. When MagerValp wrote it, he might have been trying to enforce a strict package naming convention in his organization. (I haven't asked for clarification)

If you think this should be changed, consider opening a new issue with an enhancement request; or consider opening a new issue with a request for improved documentation on this point (or better --  add the documentation yourself).

You might also want to bring the topic up for discussion on the autopkg-discuss mailing list.

**Comment by goobersmooch** [comment]
Thank you very much @gregneagle for the explanation. I had a feeling thats what it was. I'll open an enhancement request.
