### ISSUE TITLE
[Wiki/Docs] Processors should list required version

### ISSUE THREAD

**Issue by nmcspadden** [autopkg/autopkg#274]
Several processors have been added in the last few updates, and it's currently somewhat awkward to know what the correct `MinimumVersion` value should be in order to utilize these processors.  Since the wiki is the ideal Source of Truth on these, it would be great if the processors could list the Version they were added (or last modified).

**Comment by gregneagle** [comment]
That is an excellent idea. I nominate you to go through the Git logs and change the doc string for each processor to contain the version in which that processor was added. Wiki documentation for the processors is auto-generated from the Processors themselves. Adding the info to the doc string also makes that information available from `autopkg processor-info fooprocessor`

**Comment by gregneagle** [comment]
Examples of where you'd add the info:
https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/AppDmgVersioner.py#L39
https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/FileMover.py#L24
https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/PackageRequired.py#L24

Note in some cases the info is in `description`, and then `__doc__ = description`

**Comment by nmcspadden** [comment]
Closed by 868fb4f.

**Comment by gregneagle** [comment]
You didn't put versions on them all!

**Comment by gregneagle** [comment]
I wonder if "Added in autopkg version 0.6.0" would be easier to understand...
