### ISSUE TITLE
MunkiImporter NSInvalidArgumentException - data parameter is nil

### ISSUE THREAD

**Issue by jimmybaeyens** [autopkg/autopkg#278]
Hi i have an issue when i want to run a recipe, for example with GoogleChrome

the following recipes failed:
GoogleChrome.munki
Error in com.github.autopkg.munki.google-chrome: Processor: MunkiImporter: Error: NSInvalidArgumentException - data parameter is nil.

can anyone help me out here?

thanks in advance
Jimmy

**Comment by timsutton** [comment]
Can you paste your override for your Google Chrome recipe? It also may help if you can show full verbose output of your run using `autopkg run -vvv`.

**Comment by jimmybaeyens** [comment]
Hi Tim, 

im pretty new here, what do you mean with override ? here's the full verbose output:

andromeda:~ gsadmin$ autopkg run -vvv GoogleChrome.munki
Processing GoogleChrome.munki...
{'AUTOPKG_VERSION': u'0.6.1',
 u'DOWNLOAD_URL': u'https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg',
 u'GIT_PATH': u'/usr/local/git/bin/git',
 u'MUNKI_REPO': u'/Library/Server/Web/Data/Sites/munki.andromeda.galaxystudios.com',
 u'MUNKI_REPO_SUBDIR': u'apps',
 u'NAME': u'GoogleChrome',
 'PARENT_RECIPES': [u'/Users/gsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/GoogleChrome/GoogleChrome.download.recipe'],
 'RECIPE_CACHE_DIR': u'/Users/gsadmin/Library/AutoPkg/Cache/com.github.autopkg.munki.google-chrome',
 'RECIPE_DIR': u'/Users/gsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/GoogleChrome',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': u'/Users/gsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/GoogleChrome/GoogleChrome.munki.recipe',
 u'RECIPE_REPOS': {u'/Library/Server/Web/Data/Sites/munki.andromeda.galaxystudios.com/com.github.autopkg.hjuutilainen-recipes': {
    URL = "https://github.com/autopkg/hjuutilainen-recipes.git";
},
                   u'/Library/Server/Web/Data/Sites/munki.andromeda.galaxystudios.com/com.github.autopkg.homebysix-recipes': {
    URL = "https://github.com/autopkg/homebysix-recipes.git";
},
                   u'/Library/Server/Web/Data/Sites/munki.andromeda.galaxystudios.com/com.github.autopkg.nmcspadden-recipes': {
    URL = "https://github.com/autopkg/nmcspadden-recipes.git";
},
                   u'/Library/Server/Web/Data/Sites/munki.andromeda.galaxystudios.com/com.github.autopkg.recipes': {
    URL = "https://github.com/autopkg/recipes";
},
                   u'/Users/gsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes': {
    URL = "https://github.com/autopkg/recipes.git";
}},
 u'RECIPE_REPO_DIR': u'/Library/Server/Web/Data/Sites/munki.andromeda.galaxystudios.com',
 u'RECIPE_SEARCH_DIRS': [u'.',
                         u'~/Library/AutoPkg/Recipes',
                         u'/Library/AutoPkg/Recipes',
                         u'/Users/gsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes',
                         u'/Library/Server/Web/Data/Sites/munki.andromeda.galaxystudios.com/com.github.autopkg.hjuutilainen-recipes',
                         u'/Library/Server/Web/Data/Sites/munki.andromeda.galaxystudios.com/com.github.autopkg.homebysix-recipes',
                         u'/Library/Server/Web/Data/Sites/munki.andromeda.galaxystudios.com/com.github.autopkg.nmcspadden-recipes',
                         u'/Library/Server/Web/Data/Sites/munki.andromeda.galaxystudios.com/com.github.autopkg.recipes',
                         u'/Users/gsadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/GoogleChrome'],
 u'pkginfo': {
    catalogs =     (
        testing
    );
    description = "Chrome is a fast, simple, and secure web browser, built for the modern web.";
    "display_name" = "Google Chrome";
    name = GoogleChrome;
    "unattended_install" = 1;
},
 'verbose': 3}
URLDownloader
{'Input': {'filename': u'GoogleChrome.dmg',
           'url': u'https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg'}}
URLDownloader: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/gsadmin/Library/AutoPkg/Cache/com.github.autopkg.munki.google-chrome/downloads/GoogleChrome.dmg
{'Output': {'pathname': u'/Users/gsadmin/Library/AutoPkg/Cache/com.github.autopkg.munki.google-chrome/downloads/GoogleChrome.dmg'}}
EndOfCheckPhase
{'Input': {}}
{'Output': {}}
MunkiImporter
{'Input': {'MUNKI_REPO': u'/Library/Server/Web/Data/Sites/munki.andromeda.galaxystudios.com',
           'pkg_path': u'/Users/gsadmin/Library/AutoPkg/Cache/com.github.autopkg.munki.google-chrome/downloads/GoogleChrome.dmg',
           'pkginfo': {
    catalogs =     (
        testing
    );
    description = "Chrome is a fast, simple, and secure web browser, built for the modern web.";
    "display_name" = "Google Chrome";
    name = GoogleChrome;
    "unattended_install" = 1;
},
           'repo_subdirectory': u'apps'}}
NSInvalidArgumentException - data parameter is nil
Failed.
Receipt written to /Users/gsadmin/Library/AutoPkg/Cache/com.github.autopkg.munki.google-chrome/receipts/GoogleChrome-receipt-20160510-141448.plist

The following recipes failed:
    GoogleChrome.munki
        Error in com.github.autopkg.munki.google-chrome: Processor: MunkiImporter: Error: NSInvalidArgumentException - data parameter is nil

Nothing downloaded, packaged or imported.
andromeda:~ gsadmin$

**Comment by jimmybaeyens** [comment]
one thing i do see when i search for the override ...

autopkg info googlechrome.munki 
...
input values:
download url is ok
but 
"MUNKI_REPO_SUBDIR" = apps;

if i go to my server and go search the directory it is pkgs/apps

does that make sense? or am i wrong here?

**Comment by timsutton** [comment]
That part makes sense - whatever you have for `MUNKI_REPO_SUBDIR` will have that directory structure mirrored in both `pkgs` and `pkgsinfo` directories on your repo.

It looks like you're not using an override, and that's fine. Most people usually are for Munki recipes.

It sounds from what you said like Chrome is not the only recipe failing for you, is that true? What happens when you use the regular `makepkginfo` Munki tool at the command line with the download?

```
makepkginfo /Users/gsadmin/Library/AutoPkg/Cache/com.github.autopkg.munki.google-chrome/downloads/GoogleChrome.dmg
```

**Comment by jimmybaeyens** [comment]
Hi Tim, 
yes i have that issue on all the recipes .... 

if i run your command it goes flawless without an error.  You need the output?

anyway i can change the MUNKI_REPO_SUBDIR from the command line?

**Comment by timsutton** [comment]
No, I just wanted to try and understand what exactly is triggering that error for you.

You can change any Input key from the command-line as a one-time change, but your use case is why overrides exist, so you may want to familiarize yourself with this, and set up an override for your Chrome recipe (and perhaps others):

https://github.com/autopkg/autopkg/wiki/Recipe-Overrides

Just to rule out the possibility of there being an issue with AutoPkg copying to your Munki repo, you can also try running it with an alternate `MUNKI_REPO` location:

```
autopkg run -vvv -k MUNKI_REPO=/tmp GoogleChrome.munki
```

**Comment by gregneagle** [comment]
"anyway i can change the MUNKI_REPO_SUBDIR from the command line?'

Yes, with -k MUNKI_REPO_SUBDIR=foo, or the preferred method, which is to create a recipe override: 
https://github.com/autopkg/autopkg/wiki/Recipe-Overrides

This discussion is drifting away from reporting an issue with autopkg to general support, which is better done on autopkg-discuss: http://groups.google.com/group/autopkg-discuss

See also https://github.com/autopkg/autopkg/wiki
