### ISSUE TITLE
New repo : AJA System Test and Flycut recipes

### ISSUE THREAD

**Issue by Darkomen78** [autopkg/autopkg#279]
Repo : https://github.com/Darkomen78/darkomen78-recipes/

If anyone find something wrong, tell me :)

**Comment by timsutton** [comment]
Sorry for the long delay getting to this. Once you accept the team invitation you should be able to push updates here:

https://github.com/autopkg/Darkomen78-recipes

**Comment by Darkomen78** [comment]
No problem, thanks for the team invitation.
