### ISSUE TITLE
Implement pkg options

### ISSUE THREAD

**Issue by timsutton** [autopkg/autopkg#28]
(migrated from TODO.md)

**Comment by cgerke** [comment]
Not sure if it's the right place to ask this. Wondering if you are planning to implement a distribution style pkg processor. I've made one here https://github.com/autopkg/cgerke-recipes/blob/master/SharedProcessors/PkgDistributionCreator.py

And here is a sample recipe that uses it:
https://github.com/autopkg/cgerke-recipes/tree/master/Configurations/ConfigGatekeeper

The main reason I created it, is so I can add resources to my pkg file (welcome.html) that explain what my payload free pkgs are doing to assist level 1 guys learning about mac support etc. Not sure of other uses yet. And I guess a place where these descriptions can go is in Munki, Sccm, Casper descriptions etc so probably doubling up.

**Comment by arubdesu** [comment]
Pardon me inserting my opinions, but this is about where we bleed into 'autopkg as luggage/continuous build tool replacement'. (See also [here](https://github.com/autopkg/autopkg/pull/88)). Which is not necessarily a bad thing, and is obviously helpful for your use case. As an aside, I probably would've picked another example 😅, but looking at the other recipes it's awesome you're making it work for your environment and sharing things that are probably non-site-specific, I applaud you for that. 
I believe there's been the concern expressed in the past about support for processors that aren't currently used by the core devs, just throwing it out there that this may be another instance that's met with reluctance, but I can't speak for the devs or speak to the original intention of this TODO placeholder.

**Comment by cgerke** [comment]
Valid points. I'll take it over to the list.
