### ISSUE TITLE
icon support in MunkiImporter

### ISSUE THREAD

**Issue by ygini** [autopkg/autopkg#280]
It could be great to add support for icon with MunkiImporter processor.

I've seen post telling to not include app icon in the recipe folder to avoid any copyright issues, however it's not impossible to also script the icon detection via the processor. It could have two settings: it's an app so the processor look by default for icon in info.plist, it's something else so the recipe writer has to provide the full path by one way or an other. An optional key can be set to true to disable the icon detection per recipe or at the global scale if sys admin want to manage it by their-self.

I can write this extension but before doing it I would like to see the point of view of mains maintainers.

**Comment by gregneagle** [comment]
I don't feel strongly about it as long as I don't have to answer support requests like "Every time I import Firefox it tries to import the icon over and over. Can this be stopped?" Followed by "Hey Mozilla just updated the Firefox icon and the recipe didn't import the new one -- shouldn't it check every time if the icon is different?" If it generally does the right thing and doesn't cause too much support noise, go for it.

Most of the icon-getting code can be directly lifted from Munki.

**Comment by scriptingosx** [comment]
Since other actions, such as JSSImporter might want to use an icon as well, wouldn't it make more sense to write an IconExtractor processor?

**Comment by ygini** [comment]
You're right, but maybe we can work on the whole importer things.

IMHO it could be usefull to create a standard and generic PayloadImporter and use a preference key to let the IT chose which implementation to chose. That would avoid the wast of time and ressource linked to manage .munki, .jss, .etc version of each packages.

Nevertheless, implemeting this feature via a variable + a default extractor is the good software design here. It will allow usage of custom extractor.

**Comment by gregneagle** [comment]
A generic IconExtractor might be useful, but Munki doesn't actually want an _icon_ imported, it wants a png file of a certain resolution, Casper might want a jpg; LANrev might want icns; etc, etc. So such a processor would need overridable input variables to tell it what format and size to output.

**Comment by gregneagle** [comment]
"IMHO it could be usefull to create a standard and generic PayloadImporter and use a preference key to let the IT chose which implementation to chose."

I think this in practice would be an unworkable idea. For example, Munki has no problem working with "drag-n-drop" disk images, yet Casper requires those be converted into a package.

More importantly, the people working on the various import processors actually have knowledge and experience with the specific system they wrote an import processor _for_. The JSSImporter is an order of magnitude more complex than is the MunkiImporter. I don't know anything about, nor do I care to learn about the intricacies of the JSS -- I only want to work on Munki-related recipes.

**Comment by ygini** [comment]
@gregneagle, this is exactly why I think it would be more useful to abstract the importer. Recipe creator don't necessary care about all system in the wild (I write my recipes for Munki and I don't care at all about JSS, and I don't want to hear anything about it).

However, some people take bad decision and use things like JSS. So it could be interesting to provide an abstract way for them to work.

An abstract system could be feed with two parent recipe ID, the regular download and the pkg one, all the intelligence could be in the importer to actually detect if the downloaded item is usable like it is or if it need the packaged one.

It mean more work of abstraction on autopkg core but it also mean less recipe to maintain and more focused works for contributors. So for the community side it will mean a more readable list of recipe and an overall improvement for security and scalability (less work to do, more human power doing the same thing, less error reaming in the end).

Regarding images, the best option would be to always provide the same (an icns or a list of png at specific file sizes) and let the customer importer to convert in supported format. It none of the recipe writer business to understand of some specific tools don't handle all file format supported by OS X.

**Comment by gregneagle** [comment]
I think the effort to abstract all the bits around importing into Munki, Casper, LANrev, Filewave, DeployStudio, SCCM, BigFix (and are there other import processors) is far too large to contemplate.

Each of these destinations has its own set of quirks and needs. I already mentioned the case where Munki is perfectly happy with a vendor DMG, where Casper needs a package. As a Munki admin, I _don't_ want to convert Google Chrome to a pkg before importing it into Munki (one reason: removing an item via `removepackages` is much much much slower than using `remove_copied_items`)

Another difference: Munki's importer does a far amount of inspection of what is being imported and generates a lot of metadata "automatically". Casper needs autopkg to provide more of that metadata. A specific example is the _version_ of the item being imported. MunkiImporter figures that out on its own; but JSS recipes seem to need an AutoPkg step to explicitly get it.

Now multiply the various needs for each "destination" to make a generic abstraction and you'll need people intimately familiar with the needs of each destination to work together to build this abstraction. And then people intimately familiar with the needs of each destination to continue to maintain it.

I just can't see this amount of work leading to a result that makes the amount of work worth it.

**Comment by timsutton** [comment]
Re: how to handle extraction of icons - a generic "IconExtractor" processor could be time-consuming if it involves expanding a package payload, but if this were the _last_ step to run in a recipe, the "provider" could potentially know ahead of time whether the icon is needed.

That would be easy for MunkiImporter, maybe less so for JSSImporter. MunkiImporter just needs to consult a filesystem, JSSImporter may need to associate the icon at the time of importing (it's been a very long time since I've looked at early versions of JSSImporter and the JSS, so I forget how icons are managed).

**Comment by gregneagle** [comment]
Make sure the generic pkg importer supports this, too: http://macpatch.llnl.gov/docs/7_packaging-autopkg/
