### ISSUE TITLE
looking for recipe examples that use these processors

### ISSUE THREAD

**Issue by cv-rao** [autopkg/autopkg#286]
can anyone point me to working recipes that use these processors:

PkgExtractor
PkgPayloadUnpacker
FlatPkgUnpacker

or any other processors that 'installs' a package into a directory.

i am looking for a way to convert a package back to it's files for import into filewave.

thanks.

**Comment by scriptingosx** [comment]
I am not sure what you need to achieve, but you may want to look at [Suspicious Package](http://www.mothersruin.com/software/SuspiciousPackage/), [Pacifist](https://www.charlessoft.com) or plain `pkgutil --expand` for this rather than `autopkg`.
