### ISSUE TITLE
Underscore not allowed in application ID in autopkgserver/packager.py

### ISSUE THREAD

**Issue by mattlavine** [autopkg/autopkg#287]
I am trying to create a pkg out of Substance Designer and it fails with:

"Error in _insert_recipe_here_: Processor: PkgCreator: Error: Invalid package id"

After some troubleshooting I noticed that the package id of the application is:

**org.allegorithmic.substance_designer**

I looked at the code in autopkgserver/packager.py for determining the requirements for a pkg id is and I saw the following:

`re_id      = re.compile(r'^[a-z0-9]([a-z0-9 \-]*[a-z0-9])?$', re.I)`

It seems that the underscore is not an accepted character for the ID.

**Comment by goobersmooch** [comment]
See #272 and #285
