### ISSUE TITLE
Please fork my repo

### ISSUE THREAD

**Issue by erikng** [autopkg/autopkg#288]
Current: https://github.com/erikng/erikng-recipes
Expected: https://github.com/autopkg/erikng-recipes

**Comment by timsutton** [comment]
Thanks Erik!

There's already recipes for both of these ([OracleJava7JDK.munki](https://github.com/autopkg/jaharmi-recipes/blob/master/Oracle/OracleJava7JDK.munki.recipe) and [VirtualBox.munki](https://github.com/autopkg/jessepeterson-recipes/blob/master/Oracle/VirtualBox.munki.recipe)) - did you already look at these options? In general we strive to avoid duplicates, or if alternate recipes are proposed, that their descriptions explain their differences.

**Comment by erikng** [comment]
Yes I have looked at these and wrote them because I was not satisfied with their methodology. I was adverse to sending them PRs because I was worried it may disrupt others workflows.

**Comment by erikng** [comment]
@timsutton I have removed the other packages and sent PR's to the two author's. If they opt to not merge my changes, we can discuss adding them back in.

**Comment by timsutton** [comment]
Thanks - done and available here:

https://github.com/autopkg/erikng-recipes
