### ISSUE TITLE
autopkg does not bail when SSL certificate chain is invalid

### ISSUE THREAD

**Issue by erikng** [autopkg/autopkg#289]
When autopkg curl's a HTTPS url and the certificate chain is invalid, autopkg does not exit. You end up with a 0kb download package (and in this case CodeSignatureVerifier fails), but autopkg ouputs that is has successfully downloaded a package.

```curl --show-error --no-buffer --fail --dump-header - --speed-time 30 --location --url https://download.ap.bittorrent.com/track/stable/endpoint/utmac/os/osx
curl: (60) SSL certificate problem: Invalid certificate chain```

Autopkg should bail immediately. 

Example recipe: https://gist.github.com/erikng/b0af4b354c677a2364d6110932e34a1c

Autopkg run:

```
autopkg run -vv uTorrent.download
Processing uTorrent.download...
URLDownloader
{'Input': {'filename': u'uTorrent.dmg',
           'url': u'https://download.ap.bittorrent.com/track/stable/endpoint/utmac/os/osx'}}
URLDownloader: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: Downloaded /Users/Shared/autopkg/cache/com.scriptingosx.download.uTorrent/downloads/uTorrent.dmg
{'Output': {'download_changed': True,
            'pathname': u'/Users/Shared/autopkg/cache/com.scriptingosx.download.uTorrent/downloads/uTorrent.dmg',
            'url_downloader_summary_result': {'data': {'download_path': u'/Users/Shared/autopkg/cache/com.scriptingosx.download.uTorrent/downloads/uTorrent.dmg'},
                                              'summary_text': 'The following new items were downloaded:'}}}
EndOfCheckPhase
{'Input': {}}
{'Output': {}}
CodeSignatureVerifier
{'Input': {'input_path': u'/Users/Shared/autopkg/cache/com.scriptingosx.download.uTorrent/downloads/uTorrent.dmg/uTorrent.app',
           'requirement': u'identifier "com.bittorrent.uTorrent" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = SNBT6M4A7T'}}
CodeSignatureVerifier: hdiutil imageinfo error hdiutil: imageinfo failed - image not recognized
 with image /Users/Shared/autopkg/cache/com.scriptingosx.download.uTorrent/downloads/uTorrent.dmg.
/Users/Shared/autopkg/cache/com.scriptingosx.download.uTorrent/downloads/uTorrent.dmg is not mounted
Failed.
Receipt written to /Users/Shared/autopkg/cache/com.scriptingosx.download.uTorrent/receipts/uTorrent-receipt-20160630-171625.plist

The following recipes failed:
    uTorrent.download
        Error in com.scriptingosx.download.uTorrent: Processor: CodeSignatureVerifier: Error: /Users/Shared/autopkg/cache/com.scriptingosx.download.uTorrent/downloads/uTorrent.dmg is not mounted

The following new items were downloaded:
    Download Path                                                                          
    -------------                                                                          
    /Users/Shared/autopkg/cache/com.scriptingosx.download.uTorrent/downloads/uTorrent.dmg 
```

**Comment by timsutton** [comment]
Thanks - did you try this since #284 was merged? That added the `--fail` option to curl.

**Comment by erikng** [comment]
I did not, but I just tried it and it still works.

**Comment by erikng** [comment]
Apologies, adding https://github.com/autopkg/autopkg/commit/df48d8981349a21ba826ae5a9f15cc745dd638bc with #284 is working correctly.
