### ISSUE TITLE
UnicodeEncodeError when pkg_path or pkg_repo_path contain Umlaut character

### ISSUE THREAD

**Issue by workflowsguy** [autopkg/autopkg#290]
Hello,

for a software package, I have paths that contain the character "ü" `(\xfc)` in the name. When running my overridden .munki recipe that should add the package, AutoPkg writes the following error message:

`Traceback (most recent call last):`
 `File "/usr/local/bin/autopkg", line 1662, in <module>`
 `sys.exit(main(sys.argv))`
`File "/usr/local/bin/autopkg", line 1656, in main`
`exit(subcommands[verb]['function'](argv))`
`File "/usr/local/bin/autopkg", line 1566, in run_recipe`
`log(format_str.format(*row))`
`UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 15: ordinal not in range(128)`

Also, it puts the created package into a different folder that it seems to derive from the original .munki recipe (where the path doesn't have an umlaut).

Thanks!

**Comment by gregneagle** [comment]
Is this just a logging error? If you comment out the logging in line 1566 of /usr/local/bin/autopkg, does the recipe complete successfully?

**Comment by workflowsguy** [comment]
With lines 1565 and 1566 commented out, no error message shows, but the package is still imported into the wrong MUNKI_REPO_SUBDIR.

When I replace the Umlaut with a different character in MUNKI_REPO_SUBDIR in my recipe override, then the package is imported into this directory.

**Comment by gregneagle** [comment]
Can we see -vv output that demonstrates this behavior? This sounds like possibly a recipe-specific issue.

**Comment by workflowsguy** [comment]
You are right, it seemed to be recipe-specific. As I was not able to find the cause of the issue with the base/derived recipe, I created .download, .pkg and .munki recipes from scratch. Now the package really is imported into the folder (containing Umlaut) that I defined.
But also in this case, the logging error still shows.
