### ISSUE TITLE
AutoPkg shouldn't exit 1 if a recipe fails

### ISSUE THREAD

**Issue by nmcspadden** [autopkg/autopkg#296]
Currently, if AutoPkg runs a recipe with 1 success, 1 fail, it returns an exit code of 1.

This is problematic in a number of ways:

- Based on exit code, it's not possible to tell if AutoPkg ran all recipes or failed due to some exception or traceback.
- AutoPkg successfully handling a failed recipe and moving on to the next one is expected behavior, and therefore should exit 0 if this happens.
- The reporting options (such as --reportplist) are there to inform the admins if recipes fail during the run, and even if a successful report is generated that contains fails, the exit code of 1 still seems to indicate an overall execution fail, even though the program behaved exactly as intended.

Exit non-zero should only happen in a case where AutoPkg encountered an error it couldn't resolve (such as a recipe being malformed, permissions issues, etc.).  A recipe failing due to ProcessorError exceptions, which are then skipped, should not indicate a program fail.

An autopkg run execution that only contains one recipe and fails that recipe should still exit 0 if it generated a report successfully and informed the user of the fail.

**Comment by timsutton** [comment]
I think I agree. I'm betting that its behaviour for exiting non-zero if any failures occur may have predated us having the reporting option.

**Comment by timsutton** [comment]
I'm guessing that the exit code is actually the number of failures, from looking at this: https://github.com/autopkg/autopkg/blob/master/Code/autopkg#L1583

**Comment by timsutton** [comment]
I'm in favour of changing this to be that a successful run _completion_, regardless of individual recipe results, causes `run_recipes()` to exit 0.

I imagine this could break someone's AutoPkg run wrapper script, however I think if a script were doing that it wouldn't be very helpful, since you'd probably want to know _which_ recipe(s) failed anyway.

**Comment by nmcspadden** [comment]
I'm in favor of that too. Would simply removing that one line be sufficient? It doesn't seem to be used anywhere else outside that function anyway.

**Comment by gregneagle** [comment]
I'm still not really understanding the issue. (or maybe _why_ it's an issue)

**Comment by gregneagle** [comment]
I think overall I'd be happier if it was something like 0 meant no errors, 1 meant one or more recipes failed, and -1 meant some other autopkg problem occurred.

I think intentionally returning 0 even if a recipe failed seems odd.

**Comment by nmcspadden** [comment]
In my specific use case, I am wrapping AutoPkg runs with another script that also does a lot of other organization-specific things.  

I don't care if one recipe fails out of 20, because AutoPkg handles that gracefully. It tells me so in the report plist, which I can parse, and then inform me via email, filing a ticket, whatever. I don't care if 20 recipes fail out of 20, for the same reason.  AutoPkg tells me that they failed, and why, in the report.  

I do care if AutoPkg failed to run because it encountered an exception/traceback it couldn't overcome.  A malformed recipe, for example, or a permissions issue, or something that causes Autopkg to fault and not complete its run. 

In that case, I don't get a report plist. I don't get informed by the script that AutoPkg completed but recipes failed.  I get nothing.

Right now, if a single recipe out of 20 fails, there's no distinction in exit code between that and AutoPkg crashing.

**Comment by gregneagle** [comment]
"Right now, if a single recipe out of 20 fails, there's no distinction in exit code between that and AutoPkg crashing." so let's fix that instead of pretending everything is just fine when one or more recipes fail.

**Comment by nmcspadden** [comment]
As long as the Autopkg run completes and generates its report (either to stdout or to a report plist or whatever), I'd argue that it hasn't failed at all.  Even if a recipe it runs didn't complete according to expectation, as long as AutoPkg handled it, AutoPkg did the expected thing. I'd only expect a non-zero exit code if the process itself fails.

**Comment by gregneagle** [comment]
Should `/usr/sbin/installer` return 0 if a pkg install fails? It handles it and cleans things up and doesn't actually crash, so why not return 0? Exit codes are used with UNIX/POSIX tools to communicate things about what happened during execution. They don't just mean "I crashed".

**Comment by nmcspadden** [comment]
All right, then let's go back to your earlier statement and fix a situation where an exit code of 1 could mean two different results.

**Comment by gregneagle** [comment]
That makes the most sense to me. I think a new autopkg user that was reasonably familiar with UNIX/Linux tools would be perplexed that a failed `autopkg run AdobeFlashPlayer.pkg` run returned 0.

**Comment by nmcspadden** [comment]
Also worth pointing out that `/usr/sbin/installer` doesn't install multiple packages in the same execution, so I'm not sure that analogy necessarily applies. Since AutoPkg can run multiple recipes at once, with various possibilities of success or failure, I think a completion of the overall run is what the exit code should represent.

At this point, though, the discussion is more philosophical, and we can continue that via autopkg-discuss if we want.  

I'd like to see the real fix I mentioned above.

**Comment by gregneagle** [comment]
"I'd like to see the real fix I mentioned above." <--PRs accepted

**Comment by nmcspadden** [comment]
Also, devil's advocate argument here, but it's not without precedent that tools exit 0 even if they report something failed.  

Example: `lptopions`
`lpoptions -p thisprinterdoesntexist -l` will exit 0 even if it can't find the printer or class.

**Comment by nmcspadden** [comment]
https://github.com/autopkg/autopkg/pull/297

**Comment by timsutton** [comment]
Heh - I ran into the same thing today with `dscl . -search`. Exited `0` despite not finding anything, and all I actually wanted to do was check if a local record existed.

I'm not sure what precedent we could compare AutoPkg to in terms of other tools that do something similar. I feel like config management tools that take a "run list" would probably exit non-zero if they have failures - but in failure cases there may be reasons a run would halt, or wouldn't, depending on exactly what the user's trying to do. AutoPkg kind of sits somewhere in the middle.

But as Greg suggested there's no reason we can't still define non-zero exit codes but just dedicate a specific error code to "run completed, but one more recipes failed." Since `1` is what's used already (as a default of `sys.exit()`) in other cases and unhandled Python exceptions, we could pick a different number that's reserved for just this case.

This way when you wrap it you can get the exit code and at least know if it was all OK, if there were one or more failures, or if there was some other issue. Later, other exit codes could be added for specific things like file access errors, etc.

**Comment by nmcspadden** [comment]
My pull request uses '1' to indicate 'something failed'.  I would indeed like to do something different, but it sounded like this was @gregneagle's preference.

Would it be better to return a hardcoded value? i.e. "any recipes failed" = 2?

**Comment by natewalck** [comment]
I think it should stay how it is now, but return -1 if autopkg itself blows up. 

I like the idea of the exit code being how many recipes failed, with 0 meaning none failed.

**Comment by natewalck** [comment]
I like the idea of knowing how many recipes failed just from the exit code. Maybe 201 = 1 recipe failed, 202 = 2 failed, etc? 

Trying to get it out of range of standard exit codes, but that could get near 255+ then. 

I like -1 for autopkg died and 0 for run was successfully.

**Comment by timsutton** [comment]
Closed by #297.
