### ISSUE TITLE
Repo to add

### ISSUE THREAD

**Issue by chilcote** [autopkg/autopkg#298]
Please to add repo, please.  Hopefully I did this correctly.  I'll prepare for the chastisement and judging stares in slack if I did not. 

https://github.com/chilcote/autopkg-recipes

**Comment by timsutton** [comment]
Thanks! You'll get access to your repo here once you accept GitHub's team invite:

https://github.com/autopkg/chilcote-recipes

I've also been wanting to see a Docker for Mac recipe that would be able to also perform all the post-installation tasks, so I've opened [this issue](https://forums.docker.com/t/feature-request-cli-tool-for-automated-installation/18334) on their official forums (which seems to be the place to post feature requests..)

**Comment by chilcote** [comment]
Thank you.  I didn't think about those extra tools.  Definitely will want to include that in the recipe.
