### ISSUE TITLE
requesting to add/fork my repo

### ISSUE THREAD

**Issue by peshay** [autopkg/autopkg#302]
https://github.com/peshay/autopkg-recipes

**Comment by timsutton** [comment]
Sorry for the long response time to this - these look good, only two things stood out to me:

1) There is already an existing ScreenFlow download recipe in rderewianko-recipes, so you might see if you can re-use that, and
2) The ScreenFlow download recipe has a colon in the `Identifier`, which looks like a typo.

**Comment by peshay** [comment]
1) I create my own because back then the other recipe was not working. I tested it again and now it seems to be fine, so now I use the rderewianko download recipe
2) fixed
3) I also added CodeSignatureVerifier where it was missing and where it was possible. I would prefer to use it only in download recipes, but put it in my filewave recipes if the download recipes I used does not have the verification

**Comment by timsutton** [comment]
Done, and available here:

https://github.com/autopkg/peshay-recipes

I'd definitely suggest that if you find CodeSignatureVerifier missing from a recipe that warrants it, open an issue or a PR with the upstream repo so that it's available for everyone.
