### ISSUE TITLE
Please Add/Fork my repo

### ISSUE THREAD

**Issue by sethku** [autopkg/autopkg#306]
https://github.com/sethku/autopkgrecipes

**Comment by arubdesu** [comment]
Hey @sethku, these look fine minus a few exceptions. There are already 5 VMwareHorizonClient recipes (`autopkg search Horizon`), does yours do something special? I don't see the APP_FILENAME variable in the [EvolusPencil recipe](https://github.com/sethku/autopkgrecipes/blob/master/Evolus%20Pencil/EvolusPencil.munki.recipe#L13-L14) uses, was that old and could be cleaned out? 
Evolus also has a [DOWNLOAD_URL](https://github.com/sethku/autopkgrecipes/blob/9c80159716f0139b1391dad829c84dbef8e36ec4/Evolus%20Pencil/EvolusPencil.download.recipe#L15-L16) variable that doesn't get used.
Gambit seems to be a hardcoded URL, there is the [SourceforgeURLProvider processor](https://github.com/autopkg/jessepeterson-recipes/blob/master/GrandPerspective/SourceForgeURLProvider.py) you could use instead.
I'd assume recipe robot would have scraped it for you, but these really have no code signing?

**Comment by sethku** [comment]
Thanks for the feedback. There's nothing real special about the VMwareHorizonClient recipes, other than when I've tested out the other recipes they don't get me the most recent version. It is possible mine will have the same problem after the next version release. 

I'll work on cleaning up the EvolusPencil recipes and I'll try using the SourceforgeURLProvider processor. Thanks again.

**Comment by timsutton** [comment]
@sethku Did you have any more updates you wanted to make to these, such as Allister's suggestions re: the VMware Horizon Client recipes? Also, for Gambit, you should make these changes:

* remove `.test` and `.pyc` files
* Include the appropriate copyright and attribution/license information for `SourceForgeURLProvider`

**Comment by timsutton** [comment]
Looks ready to go besides that ^ comment, and I'd also recommend removing the `.DS_Store` file and adding a `.gitignore` so that they aren't added again later accidentally.

**Comment by homebysix** [comment]
Sorry for the delay: https://github.com/autopkg/sethku-recipes
