### ISSUE TITLE
Copier mounts dmg unnecessarily instead of copying

### ISSUE THREAD

**Issue by homebysix** [autopkg/autopkg#313]
If I try to copy a dmg from one place to another using Copier, it mounts the dmg and fails due to permissions on an enclosed folder.

Here are the arguments that result in failure:

```
<dict>
    <key>Processor</key>
    <string>Copier</string>
    <key>Arguments</key>
    <dict>
        <key>source_path</key>
        <string>%RECIPE_CACHE_DIR%/downloads/ParallelsDesktop-%MAJOR_VERSION%.dmg</string>
        <key>destination_path</key>
        <string>%pkgroot%/private/tmp/ParallelsDesktopAutoDeploy.pkg/Parallels/ParallelsDesktop-%version%.dmg</string>
        <key>overwrite</key>
        <string>true</string>
    </dict>
</dict>
```

And here's the error from verbose output:

```
Copier
Copier: Mounted disk image ~/Library/AutoPkg/Cache/com.example.pkg.ParallelsDesktopAutoDeploy/downloads/ParallelsDesktop-12.dmg
Can't copy /private/tmp/dmg.RIWw4F/ to ~/Library/AutoPkg/Cache/com.example.pkg.ParallelsDesktopAutoDeploy/payload/private/tmp/ParallelsDesktopAutoDeploy.pkg/Parallels/ParallelsDesktop-12.0.2.dmg: [(u'/private/tmp/dmg.RIWw4F/.Trashes', u'~/Library/AutoPkg/Cache/com.example.pkg.ParallelsDesktopAutoDeploy/payload/private/tmp/ParallelsDesktopAutoDeploy.pkg/Parallels/ParallelsDesktop-12.0.2.dmg/.Trashes', "[Errno 13] Permission denied: '/private/tmp/dmg.RIWw4F/.Trashes'")]
Failed.
```

I found a workaround, which is to add a wildcard into the extension of the source_path. Perhaps this obscures from Copier the fact that it's dealing with a dmg, preventing the unnecessary mounting.

Here is the modified source_path:

```
        <key>source_path</key>
        <string>%RECIPE_CACHE_DIR%/downloads/ParallelsDesktop-%MAJOR_VERSION%.d?g</string>
```

In any case, if you're just copying a dmg from one place to another, mounting the dmg isn't desired or necessary.

**Comment by gregneagle** [comment]
Is this new behavior? And if so, might it be caused by the changes here? https://github.com/autopkg/autopkg/commit/421638ebff10d6c97f1cdbc506b1a5cc5add76fa

**Comment by homebysix** [comment]
I only noticed this recently.

I reverted to commit bd73659e59f8565849664fa62fd1f91927cef1d8 (just before 421638ebff10d6c97f1cdbc506b1a5cc5add76fa was merged in) and the problem went away, so suspect it is indeed related to 421638ebff10d6c97f1cdbc506b1a5cc5add76fa.

**Comment by gregneagle** [comment]
Oh @nmcspadden ^^^^

**Comment by nmcspadden** [comment]
Crikey.  Fun times!

**Comment by nmcspadden** [comment]
What's a less problematic solution - putting in a special case in PlistReader to handle searching for a bundle when just given a DMG path, or putting a special case in Copier to just copy a path that ends in ".dmg"?

**Comment by gregneagle** [comment]
I think some analysis and discussion of the various use-cases needs to be done.

**Comment by nmcspadden** [comment]
One easy solution is in PR above, where the DMG is only mounted if there's a tail on the end of it.  Passing in a .dmg at that point would resolve the Copier issue, let me retest to make sure the PlistReader issue isn't broken...

**Comment by nmcspadden** [comment]
This does not break the PlistReader behavior, so this is good.

**Comment by gregneagle** [comment]
Reverted 5871fe4 and DmgMounter returns to previous behavior so I believe that addresses this.
