### ISSUE TITLE
Please fork/add my repo

### ISSUE THREAD

**Issue by morgrowe** [autopkg/autopkg#320]
https://github.com/morgrowe/morgrowe-recipes

**Comment by timsutton** [comment]
Done and available here:

https://github.com/autopkg/morgrowe-recipes

The only thing I'd recommend doing (which you can do on the new repo URL) is to document other repos that this one depends on, which is the case for a few of your recipes (AdobeDNGConverter, for example). AutoPkg doesn't have an automatic dependency detection/resolution mechanism, so manual documentation in the form of a repo's README, or even better, a recipe's `Description` key, is recommended to make it as easy as possible for others to use your recipes.
