### ISSUE TITLE
AttributeError: '__NSCFString' object has no attribute 'get'

### ISSUE THREAD

**Issue by TheVakman** [autopkg/autopkg#323]
Hello, I just set this up but I am having an issue with any recipe that I try. Is there a particular version of Python that I should have installed?

According to Console/System Logs, this is the error:
```
(FULL AUTOPKG TRACEBACK) 
  File "/usr/local/bin/autopkg", line 2400, in <module>

    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2394, in main

    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1854, in run_recipes

    recipe_paths.extend(recipe_list.get('recipes', []))
AttributeError: '__NSCFString' object has no attribute 'get'
```
This issue occurs on both Mac OS X 10.11 and macOS 10.12.

Thanks!

**Comment by gregneagle** [comment]
What version of autopkg?

You may also want to post on autopkg-discuss.

As for JSS Importer issues, https://github.com/sheagcraig/JSSImporter/issues is probably a better place to look/report -- the JSSImporter is not part of the core AutoPkg project and the core AutoPkg maintainers don't use Casper/JAMFPro.

**Comment by TheVakman** [comment]
That's a good call, will do.

Additionally, I should have posted in: https://github.com/lindegroup/autopkgr

Just noticed.

However, this would be the latest release of AutoPkg (1.0.0) but I will post over there.

**Comment by gregneagle** [comment]
The AutoPkgr folk are going to ask you to test via the command line.

`autopkg run SomeRecipe.pkg`
`autopkg run --recipe-list ~/Library/Application\ Support/AutoPkgr/recipe_list.txt`

etc.

**Comment by gregneagle** [comment]
https://github.com/lindegroup/autopkgr/blob/master/README.md#troubleshooting

**Comment by homebysix** [comment]
For what it's worth, I'm getting the same error when running a test recipe list:

```
$ autopkg run -v --recipe-list ~/Library/Application\ Support/AutoPkgr/test_recipe_list.txt 
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 2400, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2394, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1854, in run_recipes
    recipe_paths.extend(recipe_list.get('recipes', []))
AttributeError: '__NSCFString' object has no attribute 'get'

$ autopkg version
1.0.0
```

**Comment by gregneagle** [comment]
And I get no such error.

**Comment by TheVakman** [comment]
That @homebysix did! Apologies about the cross-post issue. I had originally meant to put it over on AutoPkgr.

MACHINENAME:~ USERNAME$ /usr/bin/python /usr/local/bin/autopkg run --recipe-list ~/Library/Application\ Support/AutoPkgr/recipe_list.txt --report-plist /tmp/autopkg-report.xml
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 2400, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2394, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1854, in run_recipes
    recipe_paths.extend(recipe_list.get('recipes', []))
AttributeError: '__NSCFString' object has no attribute 'get'

**Comment by gregneagle** [comment]
Perhaps share a recipe_list.txt file generated by AutoPkgr?

**Comment by gregneagle** [comment]
https://github.com/autopkg/autopkg/wiki/Running-Multiple-Recipes#plist-recipe-lists

**Comment by homebysix** [comment]
```
$ echo "com.github.autopkg.munki.munkitools2" > /tmp/recipe_list.txt

$ autopkg run -v --recipe-list /tmp/recipe_list.txt 
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 2400, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2394, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1854, in run_recipes
    recipe_paths.extend(recipe_list.get('recipes', []))
AttributeError: '__NSCFString' object has no attribute 'get'
```

I'm not going to say AutoPkgr isn't involved, but it looks that way at first glance.

**Comment by homebysix** [comment]
Looks like it works fine if given a plist:

```
$ cat /tmp/recipe_list.plist 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>recipes</key>
    <array>
        <string>com.github.autopkg.munki.munkitools2</string>
    </array>
</dict>
</plist>

$ autopkg run -v --recipe-list /tmp/recipe_list.plist 
Processing com.github.autopkg.munki.munkitools2...
--- etc. ---
```

**Comment by gregneagle** [comment]
I'm sure it's the support for plist recipe lists. Too bad there wasn't a lengthy testing period where people might have tested this. But again, 1.0 works fine here with plain text recipe lists that look like this:

```
AdobeAIR.munki
AdobeFlashPlayer.munki
AdobeReader.munki
AdobeReaderDC.munki
AdobeShockwavePlayer.munki
Atom.munki
#(etc)
````

**Comment by TheVakman** [comment]
I can confirm what @homebysix is saying. With the recipe in plist format, it seems to like that.

**Comment by timsutton** [comment]
Can you please share 1) your recipe list that's causing the issue, and 2) the output of a run of `autopkg` with increased verbosity (`autopkg run -vvv`)?

**Comment by TheVakman** [comment]
The output above is verbose.

@timsutton This happens on any recipe list. 

But here a sample that it happens with:
`com.github.autopkg.download.firefox-rc-en_US`

**Comment by gregneagle** [comment]
As it turns out, it doesn't happen on _any_ recipe list. It happens _only_ with version 1.0.0 on plain-text recipe lists containing a _single item_.

Using recipe lists that contain a single item is not common for non-AutoPkgr users, as it's more work and more difficult than just running the single recipe directly. A fix has been pushed to GitHub. https://github.com/autopkg/autopkg/commit/1a912bb4884ad196bbd09f3eab1bfb2137d3579e

**Comment by TheVakman** [comment]
@gregneagle Ah, okay, that's good to know. But this happens when I try to run a single recipe directly. If i was say, following this guide: https://github.com/homebysix/auto-update-magic

**Comment by homebysix** [comment]
@TheVakman When this fix is included in an official release, AutoPkgr users will be able to update with one click. Until then, I'd recommend "checking" more than one recipe in AutoPkgr for now.

**Comment by TheVakman** [comment]
@homebysix Sounds good!

**Comment by TheVakman** [comment]
Sorry, I meant any that I had tried. Which were only single items since I just got started.

Glad to hear on the fix pushed though! Thanks!

**Comment by timsutton** [comment]
AutoPkg 1.0.1 just released with this fix - AutoPkgr should now show this as an available update.
