### ISSUE TITLE
Add new repo please

### ISSUE THREAD

**Issue by smithjw** [autopkg/autopkg#325]
Hey, can you please add my repo into the fold 😄 

https://github.com/smithjw/smithjw-recipes

**Comment by timsutton** [comment]
Would love to get feedback from people who use AutoPkg and JSS (@homebysix, @novaksam, @scriptingosx, @rtrouton?) on these. I see that many of these apps have JSS recipes already, so it's not clear to me on whether we need a duplicate set of recipes just for handling Self Service.. do we?

**Comment by macmule** [comment]
Looking at the PolicyTemplate.xml... these policies all run a custom trigger?

@smithjw can you advise on your JSS workflow with these?

**Comment by timsutton** [comment]
I guess I'm wondering if what's being done here would instead be possible using existing patterns found in JSS recipes, the processor, etc.

**Comment by homebysix** [comment]
Yes, it looks like these are "[Auto Update Magic](https://github.com/homebysix/auto-update-magic)" style overrides for existing JSS recipes. While potentially useful as examples for people to follow, I'm not sure it's a net benefit for them to appear in `autopkg search` results. Misunderstanding of what some of these overrides do could be dangerous.

Also, this may be a small nitpick, but I don't think you can just [copy](https://github.com/smithjw/smithjw-recipes/blob/master/PolicyTemplate-selfservice.xml) a [file](https://github.com/homebysix/auto-update-magic/blob/master/Exercise6c/PolicyTemplate-selfservice.xml) that's [Apache-licensed](https://github.com/homebysix/auto-update-magic/blob/master/LICENSE) and then [re-license](https://github.com/smithjw/smithjw-recipes/blob/master/README.md) it as MIT.

**Comment by smithjw** [comment]
@homebysix sorry about the licence there, I didn't have one in any of my repos so just copied it into all of mine. 

As you said these are all Auto Update Magic style recipes but instead of the JSS recipes that already show in results which assign to a Test Group, I was looking for a way to simply have the latest updates appear in Self Service automatically. 

While this could be seen as unsafe, it's essentially the same as users updating on day one when a provider releases a new version. I should definitely add in a disclaimer to only do this for apps that you are happy to deploy automatically. 

For me it makes sense to do this as it takes a lot of the headache out of managing app updates in Self Service as I'm the only person managing Macs in the org. 

If the SS recipes don't make the cut, I did have some Viscosity ones that continue from another recipe to package the app up.

**Comment by homebysix** [comment]
@smithjw, Which recipes are referring to the PolicyTemplate-autoupdate.xml and SmartGroupTemplate-autoupdate.xml file? Those two templates are where the primary danger lies, and I'd recommend removing them if possible.

It might also be advisable to beef up the read me to explain the Self Service workflow that your overrides use. [Exercise 6c](https://github.com/homebysix/auto-update-magic#exercise-6c-sending-software-directly-to-self-service-policies) of Auto Update Magic goes to great lengths to make people aware of the potential advantages and risks, and that nuance is lost if the files are offered without any context.

**Comment by smithjw** [comment]
@homebysix great suggestions. Will add in some information on the purpose of the `-selfservice` recipes and link back to your original section of the tutorial for further clarification. 

With removing the xml files, I suppose if someone new activated them, the recipes would simply error out when getting to the JSS stage. Could host them on a separate repo with instruction on the README to download and place in the folder manually after cloning through AutoPKG. 

That would then lessen the impact should someone turn them on but not understand what they do/function. Do you think that's the best course of action?

**Comment by homebysix** [comment]
I'm only proposing removing the -autoupdate xml files, not the -selfservice one. That way people who use the -selfservice recipes (and also have the jss-recipes repo added) should get by error-free. With luck, they've also read all the docs by that point.

**Comment by smithjw** [comment]
Ahhh, yes (totally missed that). They weren't actually referenced by any recipes so I removed them. Made some changes to the README to reference the original work and warnings about pushing software directly into Self Service.

**Comment by novaksam** [comment]
Just got back in from vacation.

On my personal autopkg box I have two overrides for everything I want to deploy, one with manages 'updates' and one the manages 'available software' that way both my updates, and the versions I make available for installation are up to date (and I don't need to wait for the next update cycle to happen to get everyone running the latest version)

Example 'update' override
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Identifier</key>
	<string>local.jss.AdobeDigitalEditions</string>
	<key>Input</key>
	<dict>
		<key>CATEGORY</key>
		<string>Media</string>
		<key>GROUP_NAME</key>
		<string>Outdated %NAME%</string>
		<key>POLICY_CATEGORY</key>
		<string>Available Software Updates</string>
	</dict>
	<key>ParentRecipe</key>
	<string>com.github.novaksam.jss.AdobeDigitalEditions</string>
</dict>
</plist>
```
Example 'Available' override:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Identifier</key>
	<string>local.jss.AdobeDigitalEditions_Available</string>
	<key>Input</key>
	<dict>
		<key>CATEGORY</key>
		<string>Media</string>
		<key>GROUP_NAME</key>
		<string>Available Software Group - +10.8</string>
		<key>GROUP_TEMPLATE</key>
		<string>%RECIPE_DIR%/Templates/SmartGroupTemplate-Available-Mnt-Plus.xml</string>
		<key>POLICY_CATEGORY</key>
		<string>Available Software</string>
		<key>POLICY_TEMPLATE</key>
		<string>%RECIPE_DIR%/Templates/PolicyTemplate-Available.xml</string>
		<key>SELF_SERVICE_DESCRIPTION</key>
		<string>Adobe Digital Editions software offers an engaging way to view and manage media rich eBooks and other digital publications.</string>
	</dict>
	<key>ParentRecipe</key>
	<string>com.github.novaksam.jss.AdobeDigitalEditions</string>
</dict>
</plist>
```

PolicyTemplate-Available.xml
```
<policy>
    <general>
        <name>%PROD_NAME%</name>
        <enabled>true</enabled>
        <trigger_checkin>false</trigger_checkin>
    	<trigger_enrollment_complete>false</trigger_enrollment_complete>
    	<trigger_login>false</trigger_login>
    	<trigger_logout>false</trigger_logout>
    	<trigger_network_state_changed>false</trigger_network_state_changed>
    	<trigger_startup>false</trigger_startup>
        <frequency>Ongoing</frequency>
        <category>
            <name>Available Software</name>
        </category>
    </general>
    <scope>
		<!--Scope added by JSSImporter-->
    </scope>
    <package_configuration>
		<!--Package added by JSSImporter-->
    </package_configuration>
    <scripts>
		<!--Scripts added by JSSImporter-->
    </scripts>
    <self_service>
        <use_for_self_service>true</use_for_self_service>
	<install_button_text>Install</install_button_text>
	<self_service_description>%SELF_SERVICE_DESCRIPTION%</self_service_description>
    </self_service>
    <maintenance>
        <recon>false</recon>
    </maintenance>
    <user_interaction>
        <message_start>Beginning %PROD_NAME% update.</message_start>
        <message_finish>%PROD_NAME% update complete.</message_finish>
    </user_interaction>
</policy>
```

**Comment by smithjw** [comment]
Just wanted to breathe some life back into this thread. I've not added a bunch of Zoom specific rules which will pull down the appropriate packages and rename them including the version number which isn't present in other recipes I've found.

Should the `selfservice` recipes/overrides be moved out into a personal repo? As it stands, so long as a user has the jss-recipes repo added, they will be able to run these recipes and the relevant packages will be uploaded to the JSS and become directly available in Self Service for users

**Comment by smithjw** [comment]
@novaksam I like your overrides and might need to use them here too 😄

**Comment by novaksam** [comment]
One thing I do Is have two overrides per recipe, one for my ‘Available Software Updates’ policy, which runs a bunch of JSS policies in sequence, and ‘Available’ policies which keeps my available software listings up to do so people that want to install new software won’t automatically be out of date when they install.

I can share more details later this morning, if you’d like.

**Comment by novaksam** [comment]
Oh, I already provided that info. My bad!

**Comment by smithjw** [comment]
Just wanted to flag this repo again. I've actually removed all my -selfservice recipes as I'm overriding the JSS recipes locally now. Hoping to get my repo added in as I've got a couple of good recipes written now (including one for Little Snitch 😄).

**Comment by smithjw** [comment]
Is there any way to bump this again? cc @timsutton? 😄

**Comment by smithjw** [comment]
@hjuutilainen Given you've been the most active recently at adding new repos, any chance you can spread some love my way?

**Comment by hjuutilainen** [comment]
Hello and sorry for the wait. Repo is now available here: 
https://github.com/autopkg/smithjw-recipes
