### ISSUE TITLE
Add brianwells-recipes repo

### ISSUE THREAD

**Issue by brianwells** [autopkg/autopkg#327]
I've started creating new and unique AutoPkg recipes, primarily for software specific to the broadcast TV industry. Some of these are now in a repo located at https://github.com/brianwells/autopkg-recipes.git and I was wondering if this repo could be added to the AutoPkg org. Thanks.

**Comment by timsutton** [comment]
These look good, I'd just suggest adding some more documentation in the `Description` for nextSPOT.download, as to why the download is hardcoded. (Is it also OK for you legally-speaking to re-distribute that download URL publicly?)

Also to follow existing convention: nextSPOT.download can use an upper-case `URL` input variable and then use string substitution to pass `%URL%` to the `url` argument for URLDownloader. This makes it more clear that it's a supported input variable.

**Comment by brianwells** [comment]
After investigating, I found that the URL being used to download nextSPOT was temporary and so adjusted the recipe to use the `--pkg` argument to `autopkg run`.

**Comment by timsutton** [comment]
Sorry for the delay. You should be able to push to the new repo here:

https://github.com/autopkg/brianwells-recipes
