### ISSUE TITLE
Unexpected behavior running sharedProcessor

### ISSUE THREAD

**Issue by arubdesu** [autopkg/autopkg#329]
I'm trying [this](https://github.com/arubdesu/jps3-recipes/blob/less-futzing-for-objsee-apps/SharedProcessors/JSONParser.py) new shared processor against autopkg 1.0.1 and getting the following traceback:
```py
  File "/usr/local/bin/autopkg", line 2407, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2401, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 2000, in run_recipes
    autopackager.process(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 456, in process
    processor = processor_class(self.env)
TypeError: this constructor takes no arguments
```
I should mention I'm testing by copying the shared processor from that stub location to a relative location (the same folder as the recipe) for testing, as reflected in [the recipe](https://github.com/arubdesu/jps3-recipes/blob/less-futzing-for-objsee-apps/Objective-See/RansomWhere.download.recipe). 
It would also be a bummer if the `?` [in the value](https://github.com/arubdesu/jps3-recipes/blob/less-futzing-for-objsee-apps/Objective-See/RansomWhere.download.recipe#L26) that's used in the dictionary's key was the cause of the issue...

**Comment by timsutton** [comment]
Your processor isn't a subclass of anything.

Not directly related but it seems a bit unusual to make a shared processor for a single vendor's feed, and for that processor to have the very generic `JSONParser` name. I think it would be more clear if it had a name like `ObjectiveSeeJSONFeedParser` or similar.

**Comment by arubdesu** [comment]
Maybe I should have made a processor that inherits the `Processor` class, so it, y'know, works... fixed with the changes [here](https://github.com/arubdesu/jps3-recipes/blob/cf3b76f95e1106f8f11e366d7d35000532afc540/SharedProcessors/JSONParser.py)
