### ISSUE TITLE
Reference to https://github.com/lindegroup/autopkgr/issues/563

### ISSUE THREAD

**Issue by danner26** [autopkg/autopkg#331]
Please refer to my comment in [this thread](https://github.com/lindegroup/autopkgr/issues/563).

I am not sure if this is an issue with Sierra, or what is going on. I have attempted to debug this for hours but the only solution I can find is to rebuild the system (which is not a solution at all). I have also ran disk utility to repair the volumes to no avail as it does not error out. 

Any information you may need to assist me just ask.

**Comment by arubdesu** [comment]
Please don't have us go search for what you're opening an issue about. You seem to be experiencing DMG mounts left around for subsequent autopkg runs, is that correct? Sierra has had unmounting issues with the OS installer itself, but you can search issues here and see there haven't been many other reports. I can be pretty confident when I say substantial unmount handling is already written into autopkg, so its own functionality is probably not causing your symptom. You should look for other environmental causes, perhaps running AutoDMG builds during the same runtime/uptime session, or similar processes.

**Comment by danner26** [comment]
Okay that would explain the dropbox munki recipe issue, but that does nto explain the GoogleChrome issue. In reference to the dropbox issue, there is no mounted objects except for the drives in the machine. I have checked all mount points that I can think of but cannot find any stray mounts. I have restarted the machine multiple times and the only processes running are deploystudio (which does not handle any package installs for us).

Now on to the GoogleChrome.munki issue. This I believe is totally different. When I run the recipe I always get `Error in local.munki.GoogleChrome: Processor: MunkiImporter: Error: creating pkginfo for /Users/administrator/Library/AutoPkg/Cache/local.munki.GoogleChrome/downloads/GoogleChrome.dmg failed: Traceback (most recent call last):
          File "/usr/local/munki/makepkginfo", line 1166, in <module>
            main()
          File "/usr/local/munki/makepkginfo", line 847, in main
            if munkicommon.DMGisWritable(item):
          File "/usr/local/munki/munkilib/munkicommon.py", line 856, in DMGisWritable
            'hdiutil error %s with image %s.' % (err, dmgpath))
        UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 194: ordinal not in range(128)`

Attached is the receipt if that will assist at all.
[GoogleChrome-receipt-20161222-202532.zip](https://github.com/autopkg/autopkg/files/670988/GoogleChrome-receipt-20161222-202532.zip)

**Comment by gregneagle** [comment]
You have a meta-error here. The underlying error is an hdiutil error. (hdiutil is a command-line utility that works with disk images) When trying to report the hdiutil error, autopkg is choking on a non-ascii character in the error message.

Since the underlying error is with working with /Users/administrator/Library/AutoPkg/Cache/local.munki.GoogleChrome/downloads/GoogleChrome.dmg -- I'd be looking more closely at that disk image.  Can you mount it manually? Once you mount it, can you unmount it? Etc.

**Comment by danner26** [comment]
Hello,

Thank you for the response. It looks like that would be the issue. We have a script that simply mounts a local network share on login, but I do not think that is it.

If I disable the script and restart the computer, that "cached" folder does not remove itself as I would assume it should. We use DeployStudio heavily, and I am kind of assuming this is attached for that process. Any idea what might be going on here? If this is so, does anyone know of a work around so we can use autopkg and deploystudio on the same instance? My only thought is possibly a VM. Below is the output when I use hdiutil attach (dmg that throws the errors).

As an FYI, it does mount the dmg, and I can unmount the dmg too.

`fsmacserv:downloads administrator$ hdiutil attach GoogleChrome.dmg 
2016-12-27 09:56:16.693 hdiutil[5779:22680] kCFURLVolumeIsAutomountedKey missing for file:///private/tmp/DSNetworkRepository/: Error Domain=NSCocoaErrorDomain Code=257 "The file “DSNetworkRepository” couldn’t be opened because you don’t have permission to view it." UserInfo={NSURL=file:///private/tmp/DSNetworkRepository/, NSFilePath=/private/tmp/DSNetworkRepository, NSUnderlyingError=0x7fbf5360fca0 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}
expected   CRC32 $FC5BB004
/dev/disk4          	Apple_partition_scheme         	
/dev/disk4s1        	Apple_partition_map            	
/dev/disk4s2        	Apple_HFS                      	/Volumes/Google Chrome
fsmacserv:downloads administrator$ `

**Comment by danner26** [comment]
So DeployStudio is confirmed to be the issue. The /private/tmp file is indeed the network repo mounted by DeployStudio when the service starts. Our work around for now is to stop the DeployStudio service when the script runs, then start it automatically when finished. Since this script only runs around 3:00 AM on Sunday night, this should not be an issue for us. We simply unload the service then load it when we are finished. I would like to hear other work arounds anyone may have, as I would prefer to not have to mess with DeployStudio. Worse case scenario we stick with this.

**Comment by gregneagle** [comment]
Closing as it appears it's an external issue.

**Comment by benmartel** [comment]
Danner what specifically are you doing to stop DS? I have tried every way  I can think of and we are still having a similar problem.

**Comment by danner26** [comment]
@benmartel Hey Ben,

It is actually really simple. We basically have scripts on one of our control servers that execute once a week to update software, and as you have already read we have to disable deploystudio beforehand. I suggest doing so when there is guaranteed off time (we run the scripts inside our scheduled maintenance window).

To disable deploystudio:
`sudo launchctl unload -F /Library/LaunchDaemons/com.deploystudio.server.plist`

To enable deploystudio:
`sudo launchctl load -F /Library/LaunchDaemons/com.deploystudio.server.plist`


Hope this helps! Let me know if you need anything else.
