### ISSUE TITLE
AutoPkg should ignore trust info unless it's in a recipe override

### ISSUE THREAD

**Issue by homebysix** [autopkg/autopkg#334]
Currently, adding trust info to a non-override recipe allows `autopkg verify-trust-info` to pass.

AutoPkg should ignore trust information unless it's in an override. Trust information in parent recipes should probably generate a warning of some kind.

[Example of a parent recipe with trust info embedded](https://gist.github.com/homebysix/5754705252e3f0c8ccbcce1065afae4f). Assuming you have the homebysix-recipes repo added and updated, this recipe passes verification even though it's not an override.

**Comment by gregneagle** [comment]
Addressed here: https://github.com/autopkg/autopkg/commit/4c827447ff71e071e76f65dcf02bcd1cd023195c

May need some additional thought/work as since ParentTrustInfo is ignored in non-override recipes, there's no warning about ParentTrustInfo in the wrong places. May then confuse people who look at a non-override recipe and see ParentTrustInfo why autopkg is warning about no trust info...

**Comment by jessepeterson** [comment]
I'm now getting:

```
Traceback (most recent call last):
  File "Code/autopkg", line 2435, in <module>
    sys.exit(main(sys.argv))
  File "Code/autopkg", line 2429, in main
    exit(subcommands[verb]['function'](argv))
  File "Code/autopkg", line 1963, in run_recipes
    search_github=make_suggestions)
  File "Code/autopkg", line 367, in load_recipe
    search_github=search_github)
  File "Code/autopkg", line 399, in load_recipe
    if parent_trust_info:
UnboundLocalError: local variable 'parent_trust_info' referenced before assignment```

With this change. Perhaps init `parent_trust_info` to `None` or something at the top of `load_recipe`?

**Comment by jessepeterson** [comment]
Interesting — I think I found the edge case causing this. A recipe in a list of recipes that isn't valid. E.g.:

```
Code/autopkg run -v Firefox.munki NonExistentRecipe.munki GoogleChrome.munki
```

Will trigger it.

**Comment by gregneagle** [comment]
See if this addresses: https://github.com/autopkg/autopkg/commit/1b1bfdbc996196a5409d7f34781f1e49ef64558f

**Comment by jessepeterson** [comment]
Yep, fixed.

**Comment by gregneagle** [comment]
So before closing this issue I'd like to see if @homebysix agrees the original issue has been addressed.

**Comment by homebysix** [comment]
Maybe I'm being dense, but I can't get the `Trust information in non-override recipe` warning to appear.

If I verify an override with a "trusted" parent, I get this:
```
$ autopkg verify-trust-info local.pkg.Caffeine -vv
local.pkg.Caffeine: FAILED
    No trust information present.
    Audit the parent recipe, then run:
    	autopkg update-trust-info local.pkg.Caffeine
```

If I add trust info to the override and run verify again (still with "trusted" parent), I get this:
```
$ autopkg verify-trust-info local.pkg.Caffeine -vv
local.pkg.Caffeine: OK
```

And if I try to verify the "trusted" parent directly, I get this:
```
$ autopkg verify-trust-info com.github.homebysix.pkg.Caffeine -vv
com.github.homebysix.pkg.Caffeine: FAILED
    No trust information present.
    Audit the recipe, then store trust info by running:
    	autopkg make-override com.github.homebysix.pkg.Caffeine
```

So what condition am I failing to trigger in order to get the new `Trust information in non-override recipe` warning?

**Comment by gregneagle** [comment]
See https://github.com/autopkg/autopkg/issues/334#issuecomment-270209653

**Comment by gregneagle** [comment]
Closing due to lack of followup/interest. Reopen if we can identify an actionable issue here.
