### ISSUE TITLE
AutoPkg version 1.0.1 failures after upgrade / new install

### ISSUE THREAD

**Issue by davoMM** [autopkg/autopkg#340]
Hi all,

I am getting some errors when using AutoPkg 1.0.1 (on macOS Sierra), both from the Terminal and within the AutoPkgr app.

After adding `defaults write com.github.autopkg FAIL_RECIPES_WITHOUT_TRUST_INFO -bool NO` to the preferences file (to get around the Trust warnings), and adding 
`<key>DISABLE_CODE_SIGNATURE_VERIFICATION</key>
<string>True</string>` to the individual overrides to get around the CodeSig errors, I experience various Versioner and other errors, similar to the one below:

`The following recipes failed:
    vlc.ds
        Error in local.ds.vlc: Processor: AppDmgVersioner: Error: 'ascii' codec can't decode byte 0xe2 in position 204: ordinal not in range(128)

Nothing downloaded, packaged or imported.`

There seems to be some underlying reason for all of these errors that I must be missing. So far in troubleshooting I've tried the following steps:

• Adding prefs and override edits to circumvent initial errors
• Running the parent .pkg recipes before .ds (DeployStudio) child recipes
• Running new, never-before used recipes
• Created new environment on a different server
• Reinstalled AutoPkg

Any help is greatly appreciated. Thanks,

**Comment by arubdesu** [comment]
It's a bad sign that you disabled everything before trying anything. 'getting around CodeSig errors' is asking for broken or unknown code to be loaded into your mgmt system.
@jazzace hasn't changed that recipe in two years. It is probable that something about python is broken on that computer, or you broke the recipe with a unicode char in the file. You should be able to check out clean copies of this code on a clean image and it will run successfully, which will prove that the failing computer has a broken python or bad source files.

**Comment by davoMM** [comment]
Hi arubdesu,

Thanks for your comment. The errors are happening on all of the recipes, and I've tried installing on a new machine as well so I don't think it's Python or bad source.

**Comment by gregneagle** [comment]
I'm betting you have an invalid recipe somewhere in your search path. In fact, I'm betting the error is trying to tell you that, but while trying to report the error it's raising an exception because the error contains Unicode characters it doesn't know how to handle.  We've had a really hard time reproducing this issue so it can be fixed. I'd start by validating that "local.ds.vlc" is a valid plist. `plutil -lint /path/to/local.ds.vlc.recipe` might be a good start.

**Comment by arubdesu** [comment]
I know it's not particularly helpful, but 'works on my machine'
https://gist.github.com/arubdesu/5b277e0a4fbc876009694e8226cf9d7c

**Comment by jazzace** [comment]
I will be equally unhelpful. My local override of the VLC.ds recipe has been running daily without problem. My workflow does include Trust Verification and Code Signature Verification. OS X 10.11.5.

**Comment by davoMM** [comment]
Thanks everyone for your help on this.  To re-summarize the issue we're having, we're seeing problems across all our recipes and are trying to isolate it on VLC to find the solution.

We decided to start fresh with a fresh install of OS Sierra / autopkg / autopkgr / xcode / command line tools / git

Then working with vlc.pkg:
```
$ autopkg info vlc.pkg
Description:         Downloads latest VLC disk image and builds a package.
Identifier:          com.github.autopkg.pkg.VLC
Munki import recipe: False
Has check phase:     True
Builds package:      True
Recipe file path:    /Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/VLC/vlc.pkg.recipe
Parent recipe(s):    /Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/VLC/VLC.download.recipe
Input values:

    NAME = VLC;
```

Validating the plists:
```
$ plutil -lint ~/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/VLC/VLC.pkg.recipe
/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/VLC/VLC.pkg.recipe: OK
```
```
$ plutil -lint ~/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/VLC/VLC.download.recipe
/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/VLC/VLC.download.recipe: OK
```

Then running the vlc.pkg recipe:
```
$ autopkg run vlc.pkg
Processing vlc.pkg...
WARNING: vlc.pkg is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
/Users/sysadmin/Library/AutoPkg/Cache/com.github.autopkg.pkg.VLC/downloads/VLC.dmg is not mounted
Failed.

The following recipes failed:
    vlc.pkg
        Error in com.github.autopkg.pkg.VLC: Processor: CodeSignatureVerifier: Error: /Users/sysadmin/Library/AutoPkg/Cache/com.github.autopkg.pkg.VLC/downloads/VLC.dmg is not mounted

Nothing downloaded, packaged or imported.
```

Same issue with vlc.download:
```
$ autopkg run vlc.download
Processing vlc.download...
WARNING: vlc.download is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
/Users/sysadmin/Library/AutoPkg/Cache/com.github.autopkg.download.VLC/downloads/VLC.dmg is not mounted
Failed.

The following recipes failed:
    vlc.download
        Error in com.github.autopkg.download.VLC: Processor: CodeSignatureVerifier: Error: /Users/sysadmin/Library/AutoPkg/Cache/com.github.autopkg.download.VLC/downloads/VLC.dmg is not mounted

The following new items were downloaded:
    Download Path
    -------------
    /Users/sysadmin/Library/AutoPkg/Cache/com.github.autopkg.download.VLC/downloads/VLC.dmg
```

Then tried to disable code signature verification (because we don't know what else to do):
```
$ autopkg run -k DISABLE_CODE_SIGNATURE_VERIFICATION=1 vlc.pkg
Processing vlc.pkg...
WARNING: vlc.pkg is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
'ascii' codec can't decode byte 0xe2 in position 204: ordinal not in range(128)
Failed.

The following recipes failed:
    vlc.pkg
        Error in com.github.autopkg.pkg.VLC: Processor: AppDmgVersioner: Error: 'ascii' codec can't decode byte 0xe2 in position 204: ordinal not in range(128)

The following new items were downloaded:
    Download Path
    -------------
    /Users/sysadmin/Library/AutoPkg/Cache/com.github.autopkg.pkg.VLC/downloads/VLC.dmg
```

However we do get different results on the vlc.download:
```
$ autopkg run -k DISABLE_CODE_SIGNATURE_VERIFICATION=1 vlc.download
Processing vlc.download...
WARNING: vlc.download is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...

The following new items were downloaded:
    Download Path
    -------------
    /Users/sysadmin/Library/AutoPkg/Cache/com.github.autopkg.download.VLC/downloads/VLC.dmg
```

But we still get the same issue as above on the vlc.pkg .

I'm wondering if this has something to do with Sierra, or if there is anything else we could try.

Thanks again.

**Comment by poundbangbash** [comment]
Sounds like the download is failing and the .dmg is actually a text file.
Try opening /Users/sysadmin/Library/AutoPkg/Cache/com.github.autopkg.download.VLC/downloads/VLC.dmg in a text editor.  I bet you'll see curl error output.

Do you have a proxy between you and the internet?

-Eric

**Comment by davoMM** [comment]
Interestingly, the .dmg in `/Users/sysadmin/Library/AutoPkg/Cache/com.github.autopkg.download.VLC/downloads/VLC.dmg` does not open: 

![download](https://cloud.githubusercontent.com/assets/17628831/23083960/08620016-f515-11e6-8b10-3d6b6b1ba3bd.png)

However the one in `/Users/sysadmin/Library/AutoPkg/Cache/com.github.autopkg.pkg.VLC/downloads/VLC.dmg` does open:

![pkg](https://cloud.githubusercontent.com/assets/17628831/23084002/41e23b44-f515-11e6-89c5-66192c05b12b.png)

This is weird, because .download is a parent of .pkg

**Comment by arubdesu** [comment]
He said text editor, not Finder. Your network (proxy?) is screwing with you.

**Comment by davoMM** [comment]
As I mentioned above, vim just spits out the guts with nothing indicating a curl error. 

![pasted image at 2017_02_17 01_43 pm](https://cloud.githubusercontent.com/assets/17628831/23084514/7e5e7b12-f517-11e6-9ae7-785a9e93ece1.png)

Not sure why the .dmg would work with the .pkg parent recipe though. 

There is no proxy here, but next I'll try tapping out directly to the internet.

**Comment by davoMM** [comment]
Hi all,

We were able to get a deploy working by creating a new server on El Capitan. After two deploys on Sierra, it's working on El Capitan.

This is still inexplicable by us, but we're glad to be up and running. Thanks for the help on this matter.
