### ISSUE TITLE
AdobeReader CodeSignature issue

### ISSUE THREAD

**Issue by DrChuTang** [autopkg/autopkg#342]
Hello,

Using the latest version of AutoPKG with AutoPKGr and getting this error when attempting to download the latest version of Adobe Reader:

> Error in com.github.autopkg.download.AdobeReader: Processor: CodeSignatureVerifier: Error: Code signature verification failed. Note that all verification can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.

Any help would be much appreciated. Thank you

**Comment by timsutton** [comment]
This issue should be over in https://github.com/autopkg/recipes.

Adobe's certificates for many of their previously-built packages expired a couple of days ago and so are prone to fail. @foigus has already done a lot of work researching this today:

https://twitter.com/foigus/status/834823211183378435

For Adobe Reader, you should be using the AdobeReaderUpdates recipes if you want the latest patches, and the updates these recipes pull in are signed with valid certs.

**Comment by gregneagle** [comment]
Closing as this is not an AutoPkg issue. If you'd like to open a new issue in https://github.com/autopkg/recipes, but it's likely to be resolved by _removing_ the AdobeReader recipe once it seems clear that Adobe won't be updating/fixing the installer pkg.

**Comment by timsutton** [comment]
Adobe's evidently re-signed their 11.0.10 installer (which is still out date but the latest "full" installer), and a recipe update has been made in 71a9ca9ea3b9610c732aa95f906d20b0213f60c8 to update the certname.
