### ISSUE TITLE
Can't add Trust Info to Recipe without parents

### ISSUE THREAD

**Issue by tcinbis** [autopkg/autopkg#344]
Hello,
I tried to add a trust info for my recipe, because I got a warning:
`WARNING: myRecipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set.`
My recipe does not have any parents nor is it an override. 
Thats why autopkg does not allow me to add/update trust info with
`autopkg update-trust-info myRecipe` 
Is there a solution or workaround for this kind of problem?
Thanks in advance!

**Comment by gregneagle** [comment]
Trust info may exist only in overrides. 

You address your issue by making an override for each recipe you wish to run, even if it's a recipe you wrote yourself.
