### ISSUE TITLE
Please add https://github.com/grahampugh/recipes

### ISSUE THREAD

**Issue by grahampugh** [autopkg/autopkg#346]
I have a few recipes not available elsewhere, especially .ds recipes.

**Comment by timsutton** [comment]
These mostly seem ok, though there are a few duplications of existing recipes (yo.download, and some Munki recipes). Your `MakeCatalogs.munki` processor seems to have some additional output, but it wasn't clear to me how it improves on what's already output by the version in `autopkg/recipes`.

The occasional recipe duplicate is ok, provided there's a sensible reason (and explanation in the `Description`) for any alternate versions.

**Comment by grahampugh** [comment]
Hi Tim

Thanks for the reply.

For software that already exists in sombody’s repo in one format but not another, e.g. .download but not .munki, (or vice versa in the case of munkitools2), is the preferred course of action to fork and pull-request? That would make sense, and I’m happy to do that. However, I guess it depends on whether the authors of yo.download and munkitools2.munki wish to maintain .munki and .download recipes themselves, respectively.  And that would especially be the case with the more obscure .ds recipes.

The reason I had to fork the munkitools2 recipes including processors is because no standalone munkitools2.download recipe exists, which is very useful as a stepping stone to a munkitools2.ds recipe. I could’t find a way of referring to processors from another repo’s recipe, so I had to clone them - not very satisfactory I agree. I am surprised, given the number of people who use DeployStudio or Imagr to deploy Munki, that nobody else wants an automated way of keeping their munkitools up-to-date at the point of deployment.

I believe my MakeCatalogs recipe came about during the extensive work I did with git and branching in Munki-Do. I probably should do a pull request on it, if I ever revisit git branching in Munki any time soon, but in all honesty that is unlikely as I’m moving to a Jamf Pro shop.  So I’ll just park that in a branch… (I presume only the master branch is linked to github/autopkg?).

Cheers
Graham

**Comment by grahampugh** [comment]
Hi all,

Can I renew this request? I believe that I removed the issues that prevented it before, and have added a bunch of recipes since then.

Cheers
Graham

**Comment by grahampugh** [comment]
All duplicate recipes have been removed.

**Comment by gregneagle** [comment]
Done: https://github.com/autopkg/grahampugh-recipes

**Comment by grahampugh** [comment]
Many thanks for that @gregneagle.
I don't appear to have write access to the repository, unless I'm missing something.

**Comment by gregneagle** [comment]
That should have been automatic as part of the script that forks the repo; but I just manually added you. It's possible the automation is partially broken.

**Comment by grahampugh** [comment]
Thanks for the speediness, now it works.
