### ISSUE TITLE
Flash recipe failing.

### ISSUE THREAD

**Issue by LehmanITR** [autopkg/autopkg#347]
Flash pkg recipe failing in Autopkgr, then ran it from autopkg and got:
"The following recipes failed:
    com.github.autopkg.pkg.FlashPlayerExtractPackage
        Error in com.github.autopkg.pkg.FlashPlayerExtractPackage: Processor: CodeSignatureVerifier: Error: Mismatch in authority names. Note that all verification can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.

Nothing downloaded, packaged or imported."

How do I set DISABLE_CODE_SIGNATURE_VERIFICATION?

**Comment by timsutton** [comment]
See https://github.com/autopkg/autopkg/wiki/Using-CodeSignatureVerification#disabling-codesignatureverification-in-an-existing-recipe.

Although in this case, it looks like Adobe has an updated Flash which has been signed with an updated (and differently-named) developer cert, and we would need to update the one defined in the `.download` recipe.

**Comment by gregneagle** [comment]
Have you updated the recipe itself (that is, do you have the current version)?

`autopkg repo-update recipes`

I think you should spend some time learning about how Code Signature verification works rather than turning it off.

**Comment by timsutton** [comment]
Now that I ran it on my machine and see it works, it looks like, as Greg says, your recipes are out of date.

**Comment by gregneagle** [comment]
https://github.com/autopkg/recipes/commit/1e13bcf8dd8e90e10c04a5c913842e263499a8e2

**Comment by gregneagle** [comment]
Additional links:
<https://github.com/autopkg/autopkg/wiki/Using-CodeSignatureVerification>
<https://github.com/autopkg/autopkg/wiki/FAQ#im-getting-a-failure-message-code-signature-verification-failed-what-should-i-do>

**Comment by LehmanITR** [comment]
Thx

Mike Shur | Apple Systems Administrator
Lehman College, CUNY | Information Technology Division
718-960-8708 | http://www.lehman.edu

IT Staff will never ask for your password. Never provide your password to anyone by phone or by replying to/clicking on an email link.

On Mar 22, 2017, at 1:38 PM, Greg Neagle <notifications@github.com<mailto:notifications@github.com>> wrote:


Additional links:
https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_autopkg_autopkg_wiki_Using-2DCodeSignatureVerification&d=DwIGaQ&c=tzSjEhL4u5XIh9GXWARTsBI31pp--h2kWBIadC1LS_M&r=ZuY7RcfM9AcdobUqmxbw8NGvqEAYltOF7lMgIyQbMvxRW7ww7aWzFvleXc864Xapd4KR77GiyawBs3cc0W67yqWg1xojuFHWBji17b8l9D8iFNyzo8t9fm1iMl5mAvdwmocRnmWfro7naCiv7Km1YA&m=RG3DDNlBLCpRbhreQgk4zcDH3mbgIRmQ-lEdgCL3FPU&s=MbQJK4TF6BEslMvFQAOQRmpSM3o2pheqm7WRsrf1Ckw&e= <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_autopkg_autopkg_wiki_Using-2DCodeSignatureVerification&d=DwMFaQ&c=tzSjEhL4u5XIh9GXWARTsBI31pp--h2kWBIadC1LS_M&r=ikivzZ-w4bKVt6dt8ofDCXBWXRHDw1U5c5HiTef7gME&m=sJiVaA8kcsdIlyMef1IYZgepRX7P2btkL7gjhS8Dg4E&s=sQJ4x3WXWiZ5ONq-9SbPWYFOENATRvtGrZUltCKUKtw&e=>
https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_autopkg_autopkg_wiki_FAQ-23im-2Dgetting-2Da-2Dfailure-2Dmessage-2Dcode-2Dsignature-2Dverification-2Dfailed-2Dwhat-2Dshould-2Di-2Ddo&d=DwIGaQ&c=tzSjEhL4u5XIh9GXWARTsBI31pp--h2kWBIadC1LS_M&r=ZuY7RcfM9AcdobUqmxbw8NGvqEAYltOF7lMgIyQbMvxRW7ww7aWzFvleXc864Xapd4KR77GiyawBs3cc0W67yqWg1xojuFHWBji17b8l9D8iFNyzo8t9fm1iMl5mAvdwmocRnmWfro7naCiv7Km1YA&m=RG3DDNlBLCpRbhreQgk4zcDH3mbgIRmQ-lEdgCL3FPU&s=GG9OKAA6GluPTnFMGwTJ8Zhbpqv3Rzks_r_I1JGPsaE&e= <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_autopkg_autopkg_wiki_FAQ-23im-2Dgetting-2Da-2Dfailure-2Dmessage-2Dcode-2Dsignature-2Dverification-2Dfailed-2Dwhat-2Dshould-2Di-2Ddo&d=DwMFaQ&c=tzSjEhL4u5XIh9GXWARTsBI31pp--h2kWBIadC1LS_M&r=ikivzZ-w4bKVt6dt8ofDCXBWXRHDw1U5c5HiTef7gME&m=sJiVaA8kcsdIlyMef1IYZgepRX7P2btkL7gjhS8Dg4E&s=YmKbj-11pU3EZ6WHVnyVLps5iAaSlMuc6q3boKL6SO4&e=>
