### ISSUE TITLE
Email Authentication

### ISSUE THREAD

**Issue by gskibum** [autopkg/autopkg#348]
Today I brought my mail in house using a Kerio Connect mail server to host them mail.

After I got it set up and email migrated, I set about updating all my my notifications coming from servers JSS machines, Carbon Copy Cloner machines, and AutoPkg machines.

I was able to get SMTP set up for notifications on the servers, JSSs and Carbon Copy Cloner machines, but the AutoPkg machines won't authenticate, even though I'm using the same credentials as the rest.

I tried ports 25, 465 and 587 with no success.

I did spin up a VM running OS X Server on a different domain and I set up the mail service with that, and AutoPkg does work with OS X Server mail. But for some reason it won't work with Kerio Connect mail.

Any ideas?

**Comment by gregneagle** [comment]
AutoPkg has no email integration. You might be using the email integration in AutoPkgr, which is a different project. https://github.com/lindegroup/autopkgr
