### ISSUE TITLE
PkgCopier is not able to copy packages from an ISO-formatted disk image 

### ISSUE THREAD

**Issue by rtrouton** [autopkg/autopkg#349]
While working on a recipe for Parallels Tools, I needed to extract the Parallels Tools installer metapackage from inside a .iso file. I was unable to do so until I renamed the disk image file from `disk_image_name.iso` to `disk_image_name.dmg`. 

Once I did the file rename, and without making any other changes, PkgCopier was able to successfully copy the Parallels Tools metapackage from the disk image.

Would you please update PkgCopier so that it can work with .iso files in addition to .dmg files?

[https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/PkgCopier.py#L59-L62](https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/PkgCopier.py#L59-L62)

**Comment by gregneagle** [comment]
Fixing this should not be hard, but won't be trivial, either. And if anyone does it, they need to do it for all processors that can mount a disk image, which means abstracting some stuff out so all the Processors that inherit from DmgMounter behave the same way.

**Comment by gregneagle** [comment]
I take that back. Looks like the needed method already exists in DmgMounter, and PkgCopier wasn't using it. Need to check if there are other affected processors.

**Comment by gregneagle** [comment]
@rtrouton Please verify this change fixes your issue.

**Comment by rtrouton** [comment]
I'm getting the following error:

`global name 'dmg_source_path' is not defined.`

**Comment by gregneagle** [comment]
Try the subsequent commit... :-(

**Comment by rtrouton** [comment]
Winner! Following recipe works.

[https://gist.github.com/rtrouton/b51d109f61693395f26bda1e08206422](https://gist.github.com/rtrouton/b51d109f61693395f26bda1e08206422)

**Comment by gregneagle** [comment]
Great! Closing.
