### ISSUE TITLE
Repo add

### ISSUE THREAD

**Issue by HobbitHardcase** [autopkg/autopkg#350]
Hi,
Please add my Repo currently at https://github.com/HobbitHardcase/autopkg-recipes. I'm only just starting, but there are people at my org that want access.

**Comment by timsutton** [comment]
Thanks! Added here:

https://github.com/autopkg/HobbitHardcase-recipes

**Comment by timsutton** [comment]
Sorry, I just accidentally cancelled your invite while checking something in the Teams interface, will re-send it.

**Comment by timsutton** [comment]
Ok, the invitation should be enabled again.

**Comment by HobbitHardcase** [comment]
Joined. Thanks for the add!

Regards,
Dan Ebeck
0796 242 1709
