### ISSUE TITLE
Versioner fails with incorrect error message "does not exist or could not be read"

### ISSUE THREAD

**Issue by workflowsguy** [autopkg/autopkg#353]
A recipe that had worked for some time suddenly fails with

`        Error in local.munki.DEVONthinkProOffice-angepasst: Processor: Versioner: Error: File '/Users/stefan/Library/AutoPkg/Cache/local.munki.DEVONthinkProOffice-angepasst/DEVONthink Pro Office/Applications/DEVONthink Pro Office.app/Contents/Info.plist' does not exist or could not be read.`

However, the Info.plist both exists at the path and can be opened with PlistEdit Pro without any issue.

**Comment by gregneagle** [comment]
The autopkg/autopkg code issues tracker is not the best place to begin troubleshooting a specific recipe, unless the unexpected behavior is affecting multiple recipes across multiple repos and looks like a code issue.

I'd start with munki-discuss and/or the #autopkg channel on the MacAdmins Slack, and then _possibly_ open an issue with the recipe maintainer if this can be reproduced outside of your environment.

Feel free to reopen this if it is eventually determined to be a code issue with the Versioner processor.
