### ISSUE TITLE
autopkg run --report-plist does not include all output variables

### ISSUE THREAD

**Issue by hb3b** [autopkg/autopkg#354]
I noticed that the plist generated by `autopkg run --report-plist` only include one output variable from the last running processor. Some 3rd party processors like JSSImporter have two or more output variables that get listed in autopkg_results.plist.

**Comment by timsutton** [comment]
Note that `autopkg_results.plist` is only for internal use by AutoPkg itself. I'm guessing that since you closed this issue you discovered the correct usage for the `--report-plist` option?
