### ISSUE TITLE
Munki Tools 3.0.2.3348 update error

### ISSUE THREAD

**Issue by fkick** [autopkg/autopkg#359]
Hi, 

Relatively new with autopkg and munki, but I've had a working install going for a few months now. I'm currently running Munki 3. I tried to use the "Update Munki Tools" function on the Install tab of autopkg, and I receive the following error after the file is downloaded and appears to install

> There was an error with recipes
> Repo is not installed

I then manually downloaded the Munki installer package and ran it on the machine, rebooted, and Autopkg is still showing that the update for Munki tools is available. 

Has anyone encounter this before?

Thanks

**Comment by gregneagle** [comment]
https://github.com/munki/munki/issues/789

**Comment by fkick** [comment]
Thanks Greg!

**Comment by gregneagle** [comment]
IOW, update the tools and ignore the message from AutoPkgr.

BTW: autopkg is a command-line tool. You seem to be referring to AutoPkgr, which is a different tool, written by different developers, that is a GUI "front-end" to autopkg.  AutoPkgr can be found here: https://github.com/lindegroup/autopkgr
