### ISSUE TITLE
autopkg: when running "autopkg" getting error: syntaxError: invalid syntax

### ISSUE THREAD

**Issue by cwruck** [autopkg/autopkg#360]
Installed the prepackaged version of autopkg (tried latest 1.0.2 and went all the way back to 1.0.0) same problem on macOS 10.12.5.
```
$ autopkg
  File "/usr/local/bin/autopkg", line 2224
    DOWNLOAD_PROCESSORS = {'CURLDownloader', 'URLDownloader'}
                                           ^
SyntaxError: invalid syntax
```

Fixed by editing autopkg:
```
$ diff /usr/local/bin/autopkg /var/tmp/autopkg
2224c2224
<     DOWNLOAD_PROCESSORS = {'CURLDownloader', 'URLDownloader'}
---
>     DOWNLOAD_PROCESSORS = ['CURLDownloader', 'URLDownloader']
2227c2227
<     CREATOR_PROCESSORS = {'DmgCreator', 'FlatPkgPacker', 'PkgCreator'}
---
>     CREATOR_PROCESSORS = ['DmgCreator', 'FlatPkgPacker', 'PkgCreator']
```
Seems to work now.

**Comment by gregneagle** [comment]
This is perfectly valid syntax for literal sets in Python 2.7+.

Perhaps somehow you've managed to overwrite the Python Apple ships with an older python?

What is the output of `/usr/bin/python --version` ? On 10.12.x, it should be `Python 2.7.10`

**Comment by cwruck** [comment]
It is not what you would expect it to be:
```which python
/usr/bin/python
```
```
/usr/bin/python --version
Python 2.6.9
```
Option: you want to make sure it uses python 2.7 at least you might want to change (just a thought)
```#!/usr/bin/python``` to ```#!/usr/bin/python2.7```?

**Comment by gregneagle** [comment]
While explicitly calling `#!/usr/bin/python2.7` might fix this specific issue, using anything other than the default Python installed/included by Apple is likely to result in other issues.

autopkg is developed and tested using Apple's system Python and expects the features of Apple's system Python.

**Comment by cwruck** [comment]
Okay, closing this issue, just wanted to make you aware of this.
