### ISSUE TITLE
MunkiImporter can't find bundle type installs in the catalogs

### ISSUE THREAD

**Issue by nmcspadden** [autopkg/autopkg#361]
https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/MunkiImporter.py#L176-L212 doesn't work for bundles.

The code to look for installed applications and store it in the pkgdb dictionary doesn't consider 'bundles' - only types of 'applications'. 

Thus, when https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/MunkiImporter.py#L253-L254 runs and get a list of all installed applications and bundles (even though it specifically compares bundles and application types), it will never find a matching bundle.

If you set an installs array to type 'bundle' (i.e. if you are not yet on Munki 3 and type 'bundle' is still in use), that means MunkiImporter will reimport the item every single time. https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/MunkiImporter.py#L263 never matches, which causes the reimport.

**Comment by nmcspadden** [comment]
Possible solutions:
1) Thing I don't want to do: not use 'bundle' type in the AutoPkg recipe and manually change it after, which sucks because then I essentially can't automate it with AutoPkg
2) Temporarily fix the code to check for both 'bundle' and 'application' type, which bandaids the issue
3) After talking with Greg Neagle last night, the correct solution is to move all the pkgdb construction code from Munkilib into a library and have AutoPkg use that same code.

**Comment by gregneagle** [comment]
To clarify: I think that much of the `munkiimport` code should be moved into a library that's callable by autopkg. `munkiimport` would call that library as well.

It turns out that to do _that_ correctly, we'll probably also need to move more of `makepkginfo`'s code into a library...

**Comment by nmcspadden** [comment]
There's an open pull request ( #362 ) to fix this from @timsutton. Can this be merged?

**Comment by gregneagle** [comment]
@timsutton is a primary developer/maintainer of autopkg -- I think he can merge it any time he likes. You might want to ask him what he needs to feel comfortable merging it.
