### ISSUE TITLE
can't run recipes

### ISSUE THREAD

**Issue by mwieting** [autopkg/autopkg#366]
No matter what I do when I "run recipes now" I get the error before.
WARNING: plist error for /Volumes/DATA/Munki/Munki_repo/com.github.autopkg.gilbertpalau-recipes/mozilla/firefoxesr.download.recipe: Error Domain=NSCocoaErrorDomain Code=3840 "Encountered unknown ampersand-escape sequence at line 14" UserInfo={NSDebugDescription=Encountered unknown ampersand-escape sequence at line 14, kCFPropertyListOldStyleParsingError=Error Domain=NSCocoaErrorDomain Code=3840 "Malformed data byte group at line 1; invalid hex" UserInfo={NSDebugDescription=Malformed data byte group at line 1; invalid hex}}

WARNING: plist error for /Volumes/DATA/Munki/Munki_repo/com.github.autopkg.gilbertpalau-recipes/mozilla/firefoxesr.pkg.recipe: Error Domain=NSCocoaErrorDomain Code=3840 "Encountered unknown ampersand-escape sequence at line 12" UserInfo={NSDebugDescription=Encountered unknown ampersand-escape sequence at line 12, kCFPropertyListOldStyleParsingError=Error Domain=NSCocoaErrorDomain Code=3840 "Malformed data byte group at line 1; invalid hex" UserInfo={NSDebugDescription=Malformed data byte group at line 1; invalid hex}}

Failed local trust verification.

**Comment by gregneagle** [comment]
Those two recipes are broken. Fix them or remove them from your recipe search list until the author fixes them:

https://github.com/autopkg/gilbertpalau-recipes/pull/7
https://github.com/autopkg/gilbertpalau-recipes/pull/8
