### ISSUE TITLE
failed local trust verification

### ISSUE THREAD

**Issue by mwieting** [autopkg/autopkg#367]
no matter what application I pick I get "failed local trust verification" Error running recipes

**Comment by gregneagle** [comment]
Please read the FAQ and the wiki documentation on parent trust.

**Comment by gregneagle** [comment]
If you need help in using autopkg after (or while) reviewing the documentation, http://groups.google.com/group/autopkg-discuss is a good place, as is the #autopkg channel on the MacAdmins Slack.
