### ISSUE TITLE
A Python Exception Occurred

### ISSUE THREAD

**Issue by betty02** [autopkg/autopkg#370]
Hi Guys,

Been having this issue a few weeks now. Seem that whenever my schedule is set to run I check my server in the morning and I have the error in the screenshot below -

![screen shot 2017-08-31 at 08 16 48](https://user-images.githubusercontent.com/19409181/29911770-060da5b2-8e27-11e7-924d-07d59bdda242.png)

Not really sure what it is, but seems if I run recipes manually I don't get the error? Only started recently, and not sure why as I haven't changed anything?

The only related log files I see are -

`

Aug 31 04:58:59 SBGMD99999 syslogd[69]: ASL Sender Statistics
Aug 31 05:00:06 SBGMD99999 AutoPkgr[10894]: Running AutoPkgr in background...
Aug 31 05:00:06 SBGMD99999 AutoPkgr[10894]: Error when creating directory /var/empty/Library/Application Support/AutoPkgr
Aug 31 05:00:07 SBGMD99999 AutoPkgr[10894]: (FULL AUTOPKG TRACEBACK) 
	  File "/usr/local/bin/autopkg", line 2435, in <module>
	
	    sys.exit(main(sys.argv))
	  File "/usr/local/bin/autopkg", line 2429, in main
	
	    exit(subcommands[verb]['function'](argv))
	  File "/usr/local/bin/autopkg", line 1884, in run_recipes
	
	    recipe_list = parse_recipe_list(options.recipe_list)
	  File "/usr/local/bin/autopkg", line 1797, in parse_recipe_list
	
	    plist = FoundationPlist.readPlist(filename)
	  File "/Library/AutoPkg/FoundationPlist/FoundationPlist.py", line 120, in readPlist
	
	    return _dataToPlist(data)
	  File "/Library/AutoPkg/FoundationPlist/FoundationPlist.py", line 74, in _dataToPlist
	
	    data, NSPropertyListMutableContainersAndLeaves, None, None))
	ValueError: NSInvalidArgumentException - data parameter is nil
Aug 31 05:00:07 SBGMD99999 AutoPkgr[10894]: AutoPkgr background run complete.`

Not sure if that helps? Python version is 2.7.10

If anyone can help that would be great, obviously set a schedule so I don't have to manually run it daily...which I am currently doing!

**Comment by gregneagle** [comment]
AutoPkgr is a separate tool created and supported by different people. Can you replicate your issue outside of AutoPkgr, at the command line? If not, and therefore is AutoPkgr-specific, you'll need to get support from the AutoPkgr community.

**Comment by betty02** [comment]
Ahhh didn't even realise! I had an Autopkg and an Autopkgr tab both open! Posted on the wrong one!

**Comment by gregneagle** [comment]
We'll close this one, then. You can re-open it if it turns out to be an autopkg issue, but the `Error when creating directory /var/empty/Library/Application Support/AutoPkgr` makes that unlikely.
