### ISSUE TITLE
Please fork repo

### ISSUE THREAD

**Issue by wegotoeleven** [autopkg/autopkg#371]
Repo URL:
https://github.com/amsysuk/amsys-recipes

###PLEEZE FORK ME###

Darren Wallace and Stephen Bygrave

**Comment by gregneagle** [comment]
Why use your AdobeReaderDC.pkg.recipe over https://github.com/autopkg/recipes/blob/master/AdobeReader/AdobeReaderDC.pkg.recipe?

Why use your GoogleChrome.pkg.recipe over https://github.com/autopkg/recipes/blob/master/GoogleChrome/GoogleChrome.pkg.recipe?

Why use your OracleJava8.pkg recipe over https://github.com/autopkg/recipes/blob/master/OracleJava/OracleJava8.pkg.recipe?

...etc.  It's OK to have your own versions of core recipes, but other people might want to understand what's different/why yours is better/ etc. 

For example, a search for GoogleChrome.pkg already turns up three recipes -- why a fourth? At least with scriptingosx's recipe there's a hint it's special to USC...

```
$ autopkg search GoogleChrome | grep pkg.recipe
GoogleChrome.pkg.recipe                recipes                  GoogleChrome/GoogleChrome.pkg.recipe    
GoogleChrome.pkg.recipe                rtrouton-recipes         GoogleChrome/GoogleChrome.pkg.recipe    
GoogleChromeUSC.pkg.recipe             scriptingosx-recipes     GoogleChrome/GoogleChromeUSC.pkg.recipe 
```

**Comment by wegotoeleven** [comment]
@gregneagle Thanks for your input! I've cleaned the above up and removed any duplicate recipes where necessary. Could you take another gander?

Thanks!

**Comment by wegotoeleven** [comment]
Hey guys. Any news on this repository fork at all?

Many thanks!

**Comment by hjuutilainen** [comment]
Sorry for the late reply. Currently at MacSysAdmin but will create the fork as soon as possible.

**Comment by wegotoeleven** [comment]
❤️❤️❤️

**Comment by hjuutilainen** [comment]
Ok, the repo is now available at https://github.com/autopkg/amsysuk-recipes

I'll add you (@wegotoeleven) as owner for that repository and I think you should then be able to add new members with write permissions.

**Comment by wegotoeleven** [comment]
Hey! I've just tried to add new members, and I don't have the option to... Can someone have a peek?

Thanks!
