### ISSUE TITLE
Request to add new repository to autopkg project

### ISSUE THREAD

**Issue by jlehikoinen** [autopkg/autopkg#374]
Hi!

Here's the repo link: https://github.com/jlehikoinen/jlehikoinen-recipes

Best regards
Janne Lehikoinen (@fatmrcrab)

**Comment by hjuutilainen** [comment]
Available here: https://github.com/autopkg/jlehikoinen-recipes

You should have full read/write permissions on that repo and the content should be the same as your original repo. Let me know if you have any questions!
