### ISSUE TITLE
Please fork repo

### ISSUE THREAD

**Issue by asemak** [autopkg/autopkg#377]
Hi,

Please add/fork the below repo into the AutoPkg organisation.

https://github.com/asemak/asemak-recipes

Thanks,
Andy

**Comment by asemak** [comment]
Hi Hannes,

Are we able to get my repo merged please?

Thanks

**Comment by hjuutilainen** [comment]
Hello and my apologies for the wait. Your repo is finally available here: 
https://github.com/autopkg/asemak-recipes
