### ISSUE TITLE
Please add my repo

### ISSUE THREAD

**Issue by jpiel** [autopkg/autopkg#381]
I've created some recipes and if you think they are useful, please add my repo.

The URL is https://github.com/jpiel/jpiel-recipes.git

I welcome any comments on them since they are my first tries to learn/understand recipes.

When it makes sense, i've made 2 munki recipes, 1 to install the application only, and the default one to install the Application and joined files in a subfolder with the name of the app.

**Comment by hjuutilainen** [comment]
Hello and sorry for the wait. Is this request still valid?

**Comment by jpiel** [comment]
Yes please.  :)

**Comment by hjuutilainen** [comment]
Your repo is now available here: https://github.com/autopkg/jpiel-recipes

**Comment by jpiel** [comment]
Thanks !!
