### ISSUE TITLE
[Request] Please fork my repo

### ISSUE THREAD

**Issue by neilmartin83** [autopkg/autopkg#383]
Heyas,

I've started creating AutoPkg recipes - could you please add/fork my repo here? I'm still fairly new with GitHub and recipe creation - I think I've got everything right but please let me know if I've messed something up.

https://github.com/neilmartin83/autopkg-recipes

Many thanks and kind regards,

Neil.

**Comment by neilmartin83** [comment]
Just a gentle bump to my request :-)

**Comment by hjuutilainen** [comment]
Thanks for the repo request and sorry for the wait. You should generally add subfolders for your recipes to keep the repo layout clean. This might seem minor at the moment but you'll thank me later when you have more recipes :). AutoPkg also searches the recipe file's directory first for parent recipes so you might end up with unexpected results.

**Comment by neilmartin83** [comment]
Hi @hjuutilainen thank you very much for your reply and the tips! I've added a folder structure and moved the recipes into all the right places. Fingers crossed. :-)

**Comment by hjuutilainen** [comment]
And sorry for the wait. Now available here: https://github.com/autopkg/neilmartin83-recipes
