### ISSUE TITLE
URLFormSubmitter core processor?

### ISSUE THREAD

**Issue by orbsmiv** [autopkg/autopkg#387]
Further to a brief Slack discussion with @bochoven and @fuzzylogiq and to complement PRs #384 & #386 I'm opening this up to see whether there's any appetite for a URLFormSubmitter core processor.

As I see it the primary use case would be for authenticating with a website and storing the relevant cookies (to pass onwards to the other URL core processors) – however, this may be myopic and I would welcome any comments. 

The processor would perhaps look something like this:

---
#### Inputs:
  - URL string (required)
  - Form fields/values dictionary (required)
  - Variable name (string) containing path to cookie jar (optional, defaults to `cookie_jar`)
  - Regex string used to verify the success of the submission (optional)
  - Request headers dict (optional)
  - Additional curl options array (optional)
  - Curl path (optional)

#### Outputs:
  - Path string, pointing to location of cookie jar. (Variable name from input var above.)
  - Server response code
  - String found from regex search (if present)

#### Process:
  - Build curl command, as per _URLDownloader_ and _URLTextSearcher_
  - Parse the dict of form fields/values and extend the curl command with `['-d', 'field1=value&field2=value']`
  - Create a temporary cookie-jar file in %RECIPE_CACHE_DIR% and assign its path to either `cookie_jar` or the input variable, if specified.
  - Run the command with the cookie jar functionality (`-b pathToJar -c pathToJar`) enabled
  - If verification regex string provided:
    - Check returned content (including headers??) against regex. Raise error if no match found.
---
Additional possibility: (extending idea by @fuzzylogiq)
The _URLDownloader_ and _URLTextSearcher_ could be modified so that if `self.env` contains `cookie_jar`, this automatically enables cookies and their storage. This would mean removing the ability to change the `cookie_jar` path variable name.

#### Possible issues?
  - The above process this clearly geared towards the cookie-element of form submission, maybe the processor should be more specific, e.g. _URLCookieStore_.
  - It would be the recipe creator's responsibility to tidy-up the cookie_jar path.
  - The use cases for any form submission are too specific and a core processor is therefore unhelpful.

I'm happy to submit a PR with all of this but thought it better to do a little research first!

**Comment by bochoven** [comment]
I think we don't need this as we can get by with the recent addition of curl_opts to URLDownloader and URLTextSearcher. It would be possible to add the possibility of capturing/passing cookies in those processors as well.

**Comment by orbsmiv** [comment]
That's true – I guess the main benefit would be the ability to pass the fields & values as a dictionary. Also, how could one create the initial cookie jar temp file to pass around the processors?

**Comment by orbsmiv** [comment]
@bochoven Sorry, I think I misread your previous comment – so, are you suggesting that it _would_ be better to potentially enhance URLDownloader and URLTextSearcher with cookie-capturing functionality in addition to the curl_opts already added?

**Comment by bochoven** [comment]
@orbsmiv Indeed, creating a cookie jar on disk is a bit tedious, capturing cookie data and passing it on would be a nice enhancement

**Comment by orbsmiv** [comment]
The specific recipe where I've found that this would be helpful needs a cookie jar because to reach the final URL there are around 20 redirects, each of which read and write the cookie jar until eventually it produces the cookies required to access the download – yuck!

However, I completely take your point so will instead make a simple processor that produces a temp-file, the path of which I can pass in to the curl_opts of URLDownloader and URLTextSearcher.
