### ISSUE TITLE
Please fork my repo

### ISSUE THREAD

**Issue by Yohan460** [autopkg/autopkg#390]
Added a couple JSS recipes and re-did some of the custom ones

[github.com/Yohan460/autopkg-recipes](https://github.com/Yohan460/autopkg-recipes)

**Comment by hjuutilainen** [comment]
Hello and sorry for the wait. Is this request still valid?

**Comment by Yohan460** [comment]
Yes, there is some updating that needs to happen, but I believe I do have some unique autopkg recipes.

**Comment by Yohan460** [comment]
Currently have the only Jamf Connect recipes. I think the community would like more general access to them.

Please let me know if there are edits that need to be made.

**Comment by gregneagle** [comment]
Done: https://github.com/autopkg/Yohan460-recipes
