### ISSUE TITLE
Recipe fails due to 'hdiutil: couldn't unmount "diskX" - Resource busy'

### ISSUE THREAD

**Issue by jby** [autopkg/autopkg#391]
I'm starting to get at least one of these running a 40 recipe list.

I've looked at https://github.com/autopkg/autopkg/issues/331, but I don't have DS installed and after doing some testing I don't believe DS specifically has anything to do with it.

I'm able to manually both mount and unmount the DMG that complains withouth any errors (or messages at all for that matter, more than regular mount/unmount/eject notification).

One recipe in my case is BBEdit.jss, and it runs without problem if run alone, and after manually mounting and unmounting the DMG it runs in the list as well...

It seems to be a bit random though, while creating this ticket I re-ran my list a couple of times, and I have at least one DMG failing to unmount in each run, but not always the same.
During my tests I've now seen this with BBEdit, Firefox, Slack and VLC.

**Comment by scriptingosx** [comment]
Do you have a virus or malware scanner running? If this process scans the disk image mounted by autopkg in the background it may keep the resource busy when autopkg tries to unmount it.

**Comment by jby** [comment]
Maybe, or it might be spotlight trying to index it...

**Comment by jby** [comment]
Ok, I tried running my list again, with CarbonBlack disabled - **no errors**, so it might have been just what you suspected @scriptingosx. I'll keep watch and see what happens.

**Comment by jby** [comment]
Ok, it's probably CarbonBlack causing the dmg to be busy at unmount time.

**Comment by diwanicki** [comment]
It appears to be Time Machine runs causing this, I found https://github.com/lindegroup/autopkgr/issues/563. The comment by trademarkable got me headed in the right direction to troubleshoot this on my own macOS server. The error in the autopkgr logs confirmed it for me:

kCFURLVolumeIsAutomountedKey is missing for file:///Volumes/Backups/: Error Domain=NSCocoaErrorDomain Code 257 "The file "Backups" couldn't be opened because you don't have permission to view it."...

Tried the same failed autopkg run after verifying Time Machine was not running and did not get the issue.

I don't supposed there is a way to programmatically suppress this in CodeSignatureVerifier?

**Comment by MatGriffin** [comment]
Was also having this issue running Symantec Endpoint, removed it and it seems much better

**Comment by jby** [comment]
I've tried it with and without CarbonBlack now - no difference, so the TimeMachine path sounds plausible.

**Comment by jby** [comment]
However - I do *not* have TM enabled on the host where I run autopkg(r) so I don't think that has anything to do with this...
Could it be Spotlight indexing that keeps the volume open?

**Comment by jby** [comment]
This is really getting out of hand...
I've just cleaned out these:

```
/dev/disk2 (disk image):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     Apple_partition_scheme                        +54.5 MB    disk2
   1:        Apple_partition_map                         32.3 KB    disk2s1
   2:                  Apple_HFS BBEdit 12.6.6           54.4 MB    disk2s2

/dev/disk3 (disk image):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        +2.5 GB     disk3
   1:                        EFI EFI                     209.7 MB   disk3s1
   2:                  Apple_HFS Docker                  2.2 GB     disk3s2

/dev/disk4 (disk image):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     Apple_partition_scheme                        +209.8 MB   disk4
   1:        Apple_partition_map                         32.3 KB    disk4s1
   2:         Apple_Driver_ATAPI                         4.1 KB     disk4s2
   3:                 Apple_HFSX Firefox                 209.7 MB   disk4s3

/dev/disk5 (disk image):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     Apple_partition_scheme                        +215.1 MB   disk5
   1:        Apple_partition_map                         32.3 KB    disk5s1
   2:                  Apple_HFS Google Chrome           215.1 MB   disk5s2

/dev/disk6 (disk image):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:                            OmniGraffle            +269.5 MB   disk6

/dev/disk7 (disk image):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        +22.0 MB    disk7
   1:                  Apple_HFS Quicksilver             22.0 MB    disk7s1

/dev/disk8 (disk image):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        +1.0 GB     disk8
   1:                  Apple_HFS Skype                   1.0 GB     disk8s1

/dev/disk9 (disk image):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        +324.5 MB   disk9
   1:                  Apple_HFS Slack.app               324.5 MB   disk9s1

/dev/disk10 (disk image):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        +383.1 MB   disk10
   1:                  Apple_HFS Spotify                 383.1 MB   disk10s1

/dev/disk11 (disk image):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     Apple_partition_scheme                        +184.6 MB   disk11
   1:        Apple_partition_map                         32.3 KB    disk11s1
   2:         Apple_Driver_ATAPI                         4.1 KB     disk11s2
   3:                 Apple_HFSX Thunderbird             184.5 MB   disk11s3

/dev/disk12 (disk image):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        +150.3 MB   disk12
   1:                  Apple_HFS VLC media player        150.3 MB   disk12s1

/dev/disk14 (disk image):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        +286.2 MB   disk14
   1:                  Apple_HFS Visual Studio Code      286.2 MB   disk14s1
```

**Comment by nmcspadden** [comment]
To be explicitly clear, this is not an issue with AutoPkg specifically. Your machine has a configuration issue that is preventing it from unmounting disks cleanly, likely due to installed security software. Given that this issue is unique to your machine, and not a widespread issue with AutoPkg, it doesn't really belong here in the Issues list.

If you test this on a fresh vanilla macOS install, I'd bet that it would work as expected (and it works as expected in my own testing and production use right now).

**Comment by jby** [comment]
I now have a cleanly installed Mac Pro with 10.14.6, and **no** security software installed - and I'm still getting some of these, not as many as before, but still getting some...

**Comment by jackiealex** [comment]
see your Finder sidebar, you will see something mounted, just delete it, everyting will be ok
