### ISSUE TITLE
Installer Issues

### ISSUE THREAD

**Issue by JzGenie** [autopkg/autopkg#392]
For some reason after I try to install there are no files or anything. Can someone fill me in?

**Comment by gregneagle** [comment]
This isn't a general support mechanism. Read the wiki (https://github.com/autopkg/autopkg/wiki/Getting-Started) and ask questions if you still have them in the discussion group: http://groups.google.com/group/autopkg-discuss

**Comment by JzGenie** [comment]
Thankyou
