### ISSUE TITLE
Request to add a new repository

### ISSUE THREAD

**Issue by MLBZ521** [autopkg/autopkg#394]
I have created a few recipes that are not available in current AutoPKG Repos.

https://github.com/MLBZ521/mlbz521-recipes

Thanks

**Comment by hjuutilainen** [comment]
Hello and sorry for the wait. Is this request still valid?

**Comment by MLBZ521** [comment]
No worries.  There's only a few open issues to go through.  😄

If any benefit is seen in my recipes/repo, then feel free.  If not, no worries.  🤷‍♂️

**Comment by gregneagle** [comment]
Done: https://github.com/autopkg/MLBZ521-recipes
