### ISSUE TITLE
Please add my recipe repo

### ISSUE THREAD

**Issue by wholtz** [autopkg/autopkg#398]
Hello,
I have some recipes I'd like to share: https://github.com/wholtz/wholtz-recipes

I'm fairly new to recipe writing, so please let me know if you spot anything that could be done better. Also, note that my PostgreSQL recipes, based on the EnterpriseDB installer, differ from the existing PostgresApp recipes in several important ways, much of which is outlined here: https://www.postgresql.org/download/macosx/

**Comment by hjuutilainen** [comment]
Hello and thanks for creating the recipes. Everything looks good to me. The repo fork is now available here: https://github.com/autopkg/wholtz-recipes

You should have an email invitation to join the autopkg org. Let me know once you've accepted it so I'll check the team permissions.

**Comment by wholtz** [comment]
Hi @hjuutilainen -- I have accepted the invitation to the repo.

**Comment by apizz** [comment]
It looks like this issue should be closed.

**Comment by wholtz** [comment]
Repo add is complete.
