### ISSUE TITLE
VLC Email Notifications for VLC.dmg file

### ISSUE THREAD

**Issue by bditton** [autopkg/autopkg#399]
Hi 

We are currently on VLC Version 2.2.8 and are consistently receiving email notifications every time a new VLC.dmg file has been downloaded can this be stopped as the VLC Version always stays the same as version 2.2.8.

**Comment by gregneagle** [comment]
https://github.com/autopkg/autopkg/wiki/FAQ#every-time-i-run-a-recipe-it-downloads-something-even-if-it-didnt-change-why

Easiest way to stop it is remove VLC from your list of recipes you run frequently.

**Comment by gregneagle** [comment]
Oh -- autopkg itself doesn't do any email notifications at all...

**Comment by bditton** [comment]
We would like to keep VLC in the list of recipes to receive software version updates when they become available and not every dmg file update.  This has been going on for quite sometime and we are currently at:

NAME | RATIO (CLICK FOR DETAILS)
-- | --
VLC.dmg | 0/57

VLC is the only software package that does this for us.
Please help.

**Comment by gregneagle** [comment]
autopkg itself doesn't do any email notifications at all. Make whatever is doing the email notifications "smarter".  AutoPkgr (which is a separate product) may have settings that can help you, but that is not something supported by this project. There is no code change to _autopkg_ needed here.

**Comment by bditton** [comment]
Autopkg is able to send notifications to selected emails once and update has been made available for download. The information below is text copied from that email.

New software available for testing
--

AutoPkgr Notification

New software was downloaded:

NAME | VERSION
-- | --
VLC | 2.2.8

The following new items were downloaded:

/Users/administrator/Library/AutoPkg/Cache/com.github.autopkg.munki.VLC/downloads/VLC.dmg


NAME | RATIO (CLICK FOR DETAILS)
-- | --
VLC.dmg | 0/57

**Comment by gregneagle** [comment]
Autopkg and Autopkgr are two separate projects.

Autopkg does no email notifications. You are posting issues to the autopkg project.

**Comment by jessepeterson** [comment]
Is this a download eTag issue? Could maybe get around by doing a `CHECK_FILESIZE_ONLY` in an override recipe, too.
