### ISSUE TITLE
Please include my recipe repo

### ISSUE THREAD

**Issue by nstrauss** [autopkg/autopkg#400]
https://github.com/nstrauss/autopkg-recipes

Pretty much all education focused stuff (standardized testing, Google products, etc.) other folks might not be making recipes for. Thanks!

**Comment by hjuutilainen** [comment]
Thanks for patiently waiting for us to create the fork. It is now available here: https://github.com/autopkg/nstrauss-recipes and you should have received an email to join the autopkg org.

Some observations about the recipes:

- In my opinion, the CodeSignatureVerifier processor should be used in the download recipe and right after the URLDownloader and EndOfCheckPhase processors. You're doing this already in most recipes but there are some recipes where the signature check is done in pkg recipes and after doing a lot of expanding/extracting.
- Use tabs/spaces consistently within files, GitHub renders those differently and mixing them in the same file makes them harder to view in browser.

The following already have recipes:
- Autodesk Fusion
- Express Scribe
- GoPro Quick
- Google recipes

There's no policy that says you can't have duplicates, so this is just a FYI.

**Comment by nstrauss** [comment]
Thank you for all the feedback. I've moved CodeSignatureVerification to download recipes only and changed over to consistently using spaces. Will do so in the future as well. Going to close this.
