### ISSUE TITLE
Issue with perms in pkg for recent release

### ISSUE THREAD

**Issue by arubdesu** [autopkg/autopkg#402]
I tried install recipes while bootstrapping a machine and noticed it failing silently, when I went to load the installd plist (thinking it was an issue that the job hadn't loaded yet) I got this message: `/Library/LaunchDaemons/com.github.autopkg.autopkginstalld.plist: Path had bad ownership/permissions` and sure enough, it was 664 instead of 644. Seems the release script doesn't check/correct that? https://github.com/autopkg/autopkg/blob/bd73659e59f8565849664fa62fd1f91927cef1d8/Scripts/install.sh#L57

**Comment by hjuutilainen** [comment]
The launch daemons are copied on lines 59 and 60 and there's no explicit setting of permissions or owner for either. This issue might easily happen if the original permissions are not 644.

But I think you're actually talking about the packaged release version of AutoPkg and not the install script. Just checked the latest release and the permissions are indeed incorrect. Releases are packaged with an AutoPkg recipe but the recipe is only setting permissions for autopkgserver: https://github.com/autopkg/recipes/blob/0cfce113ee899522c6f37bbabe86b7e91f38f36d/AutoPkg/AutoPkgGitMaster.pkg.recipe#L283-L292

Will fix, thank you for reporting!
