### ISSUE TITLE
datajar-recipes

### ISSUE THREAD

**Issue by macmule** [autopkg/autopkg#406]
Hi folks,

Can I have rights to manage collaborators to [https://github.com/autopkg/dataJAR-recipes](https://github.com/autopkg/dataJAR-recipes)?

If not, please add the following:

[https://github.com/jridsdale](https://github.com/jridsdale)
[https://github.com/richard-datajar](https://github.com/richard-datajar)

**Comment by hjuutilainen** [comment]
Yes, of course. You should be able to add them to https://github.com/orgs/autopkg/teams/datajar-recipes/members and that should give them write permissions to the repo. Let me know if you can't do it and I'll go through the permissions.

**Comment by macmule** [comment]
Thanks Hannes,

I'm getting the error:

> Only organization owners can Send invitations

**Comment by hjuutilainen** [comment]
How about now?

**Comment by macmule** [comment]
Same issue sadly

**Comment by hjuutilainen** [comment]
I've now invited them. They should have admin access to the repo.

**Comment by macmule** [comment]
@hjuutilainen many thanks!
