### ISSUE TITLE
install.sh tries/falls to cp from incorrect directory

### ISSUE THREAD

**Issue by tallfunnyjew** [autopkg/autopkg#410]
https://github.com/autopkg/autopkg/blob/439c7d79643a26e7f4280a3dbed243b4e7066e11/Scripts/install.sh#L47

From lines 47 - 63, cp is trying/failing to move files from the incorrect directory. Propose adding one line at 46 to restore script to functionality:

cd ../

From the GUI:

<img width="371" alt="wrong directory" src="https://user-images.githubusercontent.com/2782686/36943711-6124152e-1f42-11e8-838f-559b84bd4118.png">

**Comment by hjuutilainen** [comment]
The install script is designed to be called from the main autopkg directory with `sudo Scripts/install.sh`

I agree though that it could be made more robust but it is designed to be used for development and it gets the job done currently.

**Comment by tallfunnyjew** [comment]
Thanks for the fast response @hjuutilainen !!

FWIW: your suggestion for how the script is designed to work doesn't play out for me. See attached. My recommendation, use best/standard practice with this script. Should be able to run when calling the full path to script or when running from within the scripts dir.

<img width="837" alt="screenshot 2018-03-04 11 58 31" src="https://user-images.githubusercontent.com/2782686/36949928-62d16424-1fa3-11e8-9d73-385b9a43e11d.png">

**Comment by gregneagle** [comment]
@tallfunnyjew Your proposed change would not work when using the full path and an arbitrary working directory; your change would only help when the cwd is the one containing install.sh.

Yes, it would be nice to be more robust. It's not designed for frequent use by newbies, so right now, requiring one to read the instructions before use seems acceptable.  If you want to fix it, that's fine and would be appreciated, but make sure it is actually a fix and not just moving the problem around.
