### ISSUE TITLE
precursorca recipes

### ISSUE THREAD

**Issue by precursorca** [autopkg/autopkg#412]
Respectfully request you add/fork my repo of recipes. 
GitHub.com/precursorca/autopkg

It includes a recipe for the silent install of VectorWorks Viewer 2018.

**Comment by hjuutilainen** [comment]
Thank you for the repo request. One question about your identifier, you seem to be using `precursorca.girhub.com` prefix on all of your identifiers. Maybe the girhub should be github? The identifier can be anything you want (as long as it's unique) but the usual convention is to use reverse dns style strings and if you wanted to use that convention, your identifiers would all start with `com.github.precursorca`.

Other than that, no issues.

**Comment by hjuutilainen** [comment]
Hello and sorry for the wait. Is this request still valid?

**Comment by precursorca** [comment]
Can’t find the original email but I think this pertains to requesting that https://github.com/precursorca/precursorca-recipes <https://github.com/precursorca/precursorca-recipes> aliased into GitHub.com/autopkg <http://github.com/autopkg>.

If so then the request was never fulfilled and it is indeed still a valid request.

---
Alex Narvey
anarvey@precursor.ca <mailto:anarvey@precursor.ca>

**Comment by gregneagle** [comment]
The typo persists:

	<key>Identifier</key>
	<string>precursorca.girhub.com.download.CiscoSpark</string>

	<key>Identifier</key>
	<string>precursorca.girhub.com.pkg.WebexTeams</string>

Do you really intend identifiers that begin with "precursorca.girhub.com"?

**Comment by precursorca** [comment]
No.

I thought these recipes were created by Recipe Robot but perhaps it was my pathetic typing and proof-reading skills that led to this mess.

Alex

**Comment by homebysix** [comment]
I opened a PR to fix the identifiers: https://github.com/precursorca/precursorca-recipes/pull/1

**Comment by homebysix** [comment]
Repo created: https://github.com/autopkg/precursorca-recipes
