### ISSUE TITLE
Request to Fork my Autopkg Recipe Repo

### ISSUE THREAD

**Issue by apizz** [autopkg/autopkg#418]
Desired repo to fork:
https://github.com/apizz/apizz-recipes

You can keep the repo name the same: apizz-recipes

- I've verified all my recipes have unique identifiers
- I've verified my repo has no forked recipes

Thanks in advance!

**Comment by apizz** [comment]
Thank you @hjuutilainen. I will fix this today. Much appreciated!

**Comment by apizz** [comment]
@hjuutilainen Looking more closely at the duplicates, there appears to be two different Adobe Shockwave recipe sets - one by novaksam and another by jleggat.  My munki recipe was based on novaksam's.

While jleggat has a munki recipe, all of his munki variables are buried in the recipe, rather than available in the input, which doesn't make it very flexible.  Additionally his download recipe doesn't have a `CodeSignatureVerifier`.

Understand about the lack of rules RE duplicate recipes, but I wonder if this case if I might be able to keep my Shockwave munki recipe given it's based on the "better" recipe sets that novaksam has written.

**Comment by hjuutilainen** [comment]
Once again sorry for the wait. Your repo is finally available here: https://github.com/autopkg/apizz-recipes

**Comment by apizz** [comment]
Thanks so much, @hjuutilainen! 🍻
