### ISSUE TITLE
Recipes for the Vivaldi browswer

### ISSUE THREAD

**Issue by oculos** [autopkg/autopkg#423]
Hi! 

I just created a repo that, for now, contains recipes for the Vivaldi browser! Could you please add my repo so that this becomes available? 

The url is https://github.com/oculos/oculos-recipes.git

Thanks!

Francis

**Comment by macmule** [comment]
@oculos There are already recipes for Vivaldi, how does yours differ?

> Name                        Repo                   Path                                    
> ----                        ----                   ----                                    
> Vivaldi.jss.recipe          jss-recipes            Vivaldi/Vivaldi.jss.recipe              
> Vivaldi.download.recipe     sheagcraig-recipes     Vivaldi/Vivaldi.download.recipe         
> Vivaldi.munki.recipe        sheagcraig-recipes     Vivaldi/Vivaldi.munki.recipe            
> Vivaldi.pkg.recipe          sheagcraig-recipes     Vivaldi/Vivaldi.pkg.recipe

**Comment by oculos** [comment]
Mine are simpler, but otherwise they don't differ that much. I haven't seen them before, that's why I made them. I am closing this.
