### ISSUE TITLE
Request to include Apfelwerk repository

### ISSUE THREAD

**Issue by apettinen** [autopkg/autopkg#427]
Please fork our Apfelwerk repository from https://github.com/apfelwerk/autopkg-recipes

There isn't much yet, but as far as we know, none of these recipes are in the autopkg-repositories. All are tested to download, import to munki, and install.

**Comment by hjuutilainen** [comment]
Available here: https://github.com/autopkg/apfelwerk-recipes

**Comment by apettinen** [comment]
Thanks!
