### ISSUE TITLE
Processor to find multiple download URLs..

### ISSUE THREAD

**Issue by sggr57a** [autopkg/autopkg#428]
Is there an existing processor or way of using the existing framework to have a URL provider create a list of download URL links instead of just the one then have a processor download all of those files? Now that HP has discontinued the Apple printer driver package, they have a series of packages named of the same convention carrying the different printer drivers.  I did see that n8felton has the URL provider which allows you to enter a product code but I was hoping for one recipe to download all HP printer driver packages via a URL provider.

**Comment by gregneagle** [comment]
This is a place to report code issues, and not a place for general Q&A and discussion. Consider posting to the autopkg-discuss Google Group, or asking a question in the #autopkg channel in MacAdmins Slack.

**Comment by sggr57a** [comment]
Sorry about that Greg.  I'll post to the discussion group.
