### ISSUE TITLE
PlistReader assumes that you are trying to load a .dmg when you provide a .mobileconfig

### ISSUE THREAD

**Issue by nathanperkins** [autopkg/autopkg#430]
When you provide PlistReader with the path to a .mobileconfig file, it assumes you are trying to load a dmg, looks for a different path, then fails.

Versioner seems to work fine with .mobileconfig but only supports exporting one key.

```
Processing configuration-profile.download...
No bundle found in dmg
Failed.

The following recipes failed:
    configuration-profile.download
        Error in download.configuration-profile: Processor: PlistReader: Error: No bundle found in dmg
```

**Comment by gregneagle** [comment]
Neither processor was designed to work with mobileconfig files and mobileconfig files don't contain version information about the config. (The "PayloadVersion" refers to the version of the mobileconfig file format and to-date should always be an integer with value 1).

An unencrypted, unsigned mobileconfig is indeed a plist, but once you sign or encrypt one, it is no longer a plist.

So: what are you trying to accomplish?

**Comment by nathanperkins** [comment]
Possibly a Bad Thing™ but I'll let you judge.

I am trying to automate the process of downloading version-controlled configuration profiles from our internal GitLab and importing them into munki.

I was hoping to reduce duplication/maintenance by reading the PayloadIdentifier, PayloadDisplayName, PayloadDescription and a custom added key (ConfigurationProfileVersion) from the profiles and using them in my pkginfo.

**Comment by nmcspadden** [comment]
@nathanperkins If this is still something you want, I think you're better off doing it with a custom processor to handle unsigned mobileconfig files. I don't think this is the right fit for PlistReader.
