### ISSUE TITLE
Add/Fork repo

### ISSUE THREAD

**Issue by drewdiver** [autopkg/autopkg#440]
https://github.com/drewdiver/grumpydrew-recipes

**Comment by hjuutilainen** [comment]
Thank you for the request and sorry for the wait. Any specific reason you have new recipes for Slack and Keka? There are already existing recipes for both of them. We don't have an official policy for duplicate recipes but it would be best to avoid them.

**Comment by drewdiver** [comment]
I can move my Keka and Slack recopies out of this repo, they were learning processes for me with AutoPkg.
