### ISSUE TITLE
Unable to install 1.04 or anything older

### ISSUE THREAD

**Issue by cpenick** [autopkg/autopkg#450]
I was getting the "update to 1.04 available" but it never updated.  I dumped the whole thing and wiped all traces of the app, and attempted to install from scratch.  No good.  It says it finishes but it never shows up.  Attempted to go back to previous version, same thing.
On Mojave 10.14.3 and Xcode is current.

**Comment by gregneagle** [comment]
You are describing an issue with AutoPkgr -- a separate product with a different (dormant) set of developers. autopkg does not have an application -- its a command line tool. AutoPkgr is a GUI app that makes autopkg easier to use for some. This GitHub project is not AutoPkgr.
