### ISSUE TITLE
Request to add talosfleet-recipes

### ISSUE THREAD

**Issue by SeanHansell** [autopkg/autopkg#451]
https://github.com/mikestechshop/talosfleet-autopkg-recipes

Good afternoon. My team and I have created a recipe repo that we would like to be forked and added to the main autopkg account. For now, it'll be mostly pkg and jss recipes to complement a small pile of download/munki recipes that are out there in other repos, but we have plans to add some full recipe stacks for some other obscure software that isn't currently available here.

There's only one commit from today for these, but rest assured these recipes have been tested and in use in our private client environments for a while now.

Thanks in advance for your help.

**Comment by gregneagle** [comment]
Done at https://github.com/autopkg/mikestechshop-recipes
