### ISSUE TITLE
Add psaintemarie-recipes repo

### ISSUE THREAD

**Issue by psaintemarie** [autopkg/autopkg#457]
Hi,

Could you add my psaintemarie-recipes repo located at https://github.com/psaintemarie/psaintemarie-recipes ?

I will update the README in the old location once this is done to reflect the changes and tell any users that they need to come here for the latest version. And also instructions on how to remove the old repo/add the new in autopkg.

Thanks!

**Comment by gregneagle** [comment]
Done. At https://github.com/autopkg/psaintemarie-recipes
