### ISSUE TITLE
Oracle Java 8

### ISSUE THREAD

**Issue by jfuchtm** [autopkg/autopkg#460]
I am seeing the following error on a package update for Java 8:

RECIPE | MESSAGE
-- | --
com.github.autopkg.filewave.OracleJava8 | Error in com.github.autopkg.filewave.OracleJava8: Processor: URLTextSearcher: Error: No match found on URL: https://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

The URL is valid. Is it anything to do with the license agreement at the top?

Thanks
jfuchtm

**Comment by macmule** [comment]
yep: [https://grahamrpugh.com/2019/04/19/macos-java-autopkg.html](https://grahamrpugh.com/2019/04/19/macos-java-autopkg.html)

**Comment by gregneagle** [comment]
This is the wrong repo (there are no OracleJava8.*.recipes in this repo, but see the README here:
https://github.com/autopkg/recipes/tree/master/OracleJava
