### ISSUE TITLE
Summary result data doesn't support multiple items

### ISSUE THREAD

**Issue by gkluoe** [autopkg/autopkg#518]
I have a custom processor which creates many packages at once - I'd like to be able to list them in AutoPkg's summary output. As far as I can tell, though, it's not possible to have anything other than a single `dict` as the data item in a summary report from a single processor:

https://github.com/autopkg/autopkg/blob/d159a8e0b747e6ffe79300457dce3ccde39c3d73/Code/autopkg#L2129-L2140

It looks to me as if the intention is that multiple runs of the same processor could add to `data_rows`, but there's no way for a single processor to add multiple rows (eg because it produced several packages it wants to tell you about).

I'd like to propose supporting a list of `dicts` as the data for a summary result, with each `dict` being added as a `data_row`.

**Comment by gregneagle** [comment]
You are right in your analysis: to-date we've never had a processor that produced multiple things of interest. Even an existing recipe that imports multiple packages to a Munki repo (https://github.com/autopkg/recipes/blob/master/munkitools/munkitools3.munki.recipe) calls the MunkiImporter processor five times, which can add up to five items to the summary results.

**Comment by gkluoe** [comment]
Hmm, thanks. Having thought about this more, I suspect that what I'm doing (one processor creating lots of packages) is an anti-pattern, and probably I should re-engineer it to produce only a single package at a time. That's simple enough.

The processor is for Native Instruments software, where the suites tend to have large numbers of individual products - 54 for the suite I'm dealing with (and that's which is far from the largest).

Perhaps I should include a script that folk can use to easily generate individual recipes for each product in the suite they want to package - that way the suite can be packaged in one AutoPkg run; the current reporting mechanism works fine; and the individual recipes can be overridden if the user wants to process the packages further.

https://github.com/UoE-macOS/autopkg-recipes/tree/master/Native%20Instruments

**Comment by nmcspadden** [comment]
This issue doesn't seem to have any action items left. I'm closing it, but please re-open if there's more that we need to do. I agree with your general assessment that AutoPkg isn't really suited for handling a single processor producing multiple things of interest, and recipes that produce multiple output is a bit tough to fit into the current architecture.
