### ISSUE TITLE
curl compress argument ambiguous

### ISSUE THREAD

**Issue by rickheil** [autopkg/autopkg#537]
Running recipes that leverage URLTextSearcher on a macOS with built-in curl 7.64.1 causes an error that the compress argument is ambiguous. Flag was introduced with 605b8a8 to handle sites that don't use Accept-Encoding and send compressed data anyhow.

I'll PR a change for Sparkle and URLTextSearcher to --compressed which seems to be the right intent. Testing so far on 10.15 and 10.14 is fine, need to boot up some older VMs and test against those.

**Comment by gregneagle** [comment]
No need for the PR. I'd guess https://github.com/autopkg/autopkg/commit/3c8bc23d89e902d9e7f69ff698179f38f36a9a44 matches what you'd submit?

**Comment by rickheil** [comment]
Sure does. Thanks Greg.
