### ISSUE TITLE
MunkiInstallsItemsCreator and defining the version_comparison_key in recipe

### ISSUE THREAD

**Issue by hjuutilainen** [autopkg/autopkg#54]
I would like to see a possibility to define a version_comparison_key for MunkiInstallsItemsCreator processor in recipe. I've mostly run into this when an installs item needs to be defined with CFBundleVersion instead of CFBundleShortVersionString.

I see that MunkiInstallsItemsCreator is calling makepkginfo -f and there's no options for makepkginfo to do this but the processor could of course modify the installs item dictionary before returning.

I could take a closer look and create a pull request when I have way to do this. Any thoughts?

**Comment by prochat** [comment]
It doen't work in my recipe: LoggerPro Update
I set the version_comparison_key to version (as it's set in the plist), but it continuously load copies.

Anyone could help ? (recipe is: com.github.prochat.munki.loggerpro_update)

Regards,
Ph.R.

**Comment by gregneagle** [comment]
I suggest you post to autopkg-discuss. It's likely this is simply a CDN issue and not at all related to this.

**Comment by prochat** [comment]
A CDN ?

**Comment by prochat** [comment]
What is a CDN issue ?

Ph.R.

**Comment by gregneagle** [comment]
Content Delivery Network. Please post on autopkg-discuss.
