### ISSUE TITLE
AutoPkg on Catalina: WARNING: Executing a script that is loading libcrypto in an unsafe way

### ISSUE THREAD

**Issue by grahampugh** [autopkg/autopkg#550]
When running AutoPkg on a Catalina beta, we get a warning:
```
% autopkg version
WARNING: Executing a script that is loading libcrypto in an unsafe way. This will fail in a future version of macOS. Set the LIBRESSL_REDIRECT_STUB_ABORT=1 in the environment to force this into an error.
1.1
```
It does not break any functionality as far as I can tell.

**Comment by nmcspadden** [comment]
This seems to work just fine now with AutoPkg 1.2 on the latest Catalina beta. If that's not the case, please re-open.

**Comment by SeanHansell** [comment]
I'm getting this on AutoPkg 1.4 on Catalina 10.15.1

**Comment by gregneagle** [comment]
This is not actually an Autopkg issue. This is an issue with extra Python modules you’ve installed, possibly for use with Jss-importer.
