### ISSUE TITLE
Symantec Endpoint Protection causes DmgMounter to fail at unmount 

### ISSUE THREAD

**Issue by Honestpuck** [autopkg/autopkg#553]
Symantec Endpoint Protection has a feature that scans any mounted volume and this often causes DmgMounter to fail an unmount as the processor gets a "resource busy" error.

In testing this was fixed by adding `-force` as an option to the `hdiutil` call in the 'unmount' function in the processor. Given that AutoPkg should have finished with the DMG by the time a detach is attempted this seems reasonable.

**Comment by gregneagle** [comment]
I’m going to need a lot of convincing to add —force to the unmount, at least as a default behavior. Perhaps gated behind a preference....

**Comment by Honestpuck** [comment]
I checked a bunch of my recipes to see where the unmount in DmgMounter occurred and any errors in the build should be picked up well before it happens so the only thing picked up by the unmount/detach failing is it's own failure. On the flip side there are a bunch of things that might cause a "resource busy" including Time Machine and an AV scan.

Of course adding the `—force` gated behind a preference would be a fine solution.

(I find myself forced to run Symantec Endpoint Protection so my build machine is allowed on the network. The downside of working in the finance industry.)

**Comment by LcTrKiD** [comment]
I had the same issue. I couldn’t t use autopkg with SEP so I disabled it in my autopkg machine.

**Comment by macmule** [comment]
that's the solution really.. any AV which does on-access scanning etc will impact AutoPkg.. as such these AutoPkg hosts should either:

- Have AV disabled completely
- Have on-access scanning disabled & scheduled scans run outside of AutoPkg runs

**Comment by nmcspadden** [comment]
I'm inclined to agree that adding --force to the default behavior to handle some security software misbehaving is not the right behavior. This issue isn't really AutoPkg's fault - it's an interaction between external software and this tool.

If you want to add an option to force unmount to DmgMounter that you can specify in your recipes, I'd likely accept a PR, but I wouldn't make it the default behavior for everyone.
