### ISSUE TITLE
Rename apfelwerk-recipes to zentral-recipes

### ISSUE THREAD

**Issue by hjuutilainen** [autopkg/autopkg#555]
Request from @headmin to rename apfelwerk-recipes to zentral-recipes. Pinging @apettinen too to notify about this.

**Comment by hjuutilainen** [comment]
And this is done

**Comment by apettinen** [comment]
I’ll come up with a plan to notify the users. Thanks @hjuutilainen for taking care of this! 👍

**Comment by hjuutilainen** [comment]
AFAIK existing clones should still work as GitHub automatically redirects from the old name to the new name

**Comment by nmcspadden** [comment]
Looks like this got taken care of, so I'm closing it. Please re-open if there's more to be done.
