### ISSUE TITLE
Add/fork andrewzirkel-recipes

### ISSUE THREAD

**Issue by andrewzirkel** [autopkg/autopkg#557]
Respectfully request you add/fork my repo of recipes.
https://github.com/andrewzirkel/andrewzirkel-recipes

It includes recipes for ComicLife3, Origin client from EA, GarageBand, Kuta educational apps, Lightspeed Relay Agent client, NWEA Lockdown browser and Mitel ip phone client.

**Comment by homebysix** [comment]
@andrewzirkel - A repo we just created includes Kuta app recipes (https://github.com/autopkg/macprince-recipes/tree/master/Kuta%20Software). Would it be possible to compare yours against those and see if you can consolidate?

Also, is there anything in the GarageBand recipe (and accompanying MASReceipt processor originally created by scriptingosx) that couldn't be done with the [AppStoreApp](https://github.com/autopkg/nmcspadden-recipes#appstoreapp-recipe) family of recipes?

**Comment by andrewzirkel** [comment]
@homebysix - I was beat to it, I removed the Kuta software recipes.

Yes, the GarageBand recipes also include loops.

**Comment by homebysix** [comment]
New repo created: https://github.com/autopkg/andrewzirkel-recipes
