### ISSUE TITLE
Add Fork/Repo

### ISSUE THREAD

**Issue by doschupp** [autopkg/autopkg#559]
https://github.com/faumac/faumac-recipes

Thanks!

**Comment by homebysix** [comment]
Hi @doschupp - Would you like to be in charge of this new repo, or do you want @faumac to be in charge?

**Comment by homebysix** [comment]
Also you may want to look at the Affinity products recipes mentioned here, because it's likely that repo would be created first: https://github.com/autopkg/autopkg/issues/558

**Comment by doschupp** [comment]
Hi @homebysix 

yes, faumac pleas - it's like mac@sap.

oh.. i didn't saw it, but the affinity recipes are different. We use the appsparkle feed and have a pkg recipe with a license activation script.

**Comment by homebysix** [comment]
New repo created: https://github.com/autopkg/faumac-recipes
