### ISSUE TITLE
Merge autopkg/morgrowe-recipes with different recipes repo

### ISSUE THREAD

**Issue by morgrowe** [autopkg/autopkg#561]
It's been a long time since I last contributed recipes to this project. As I'm no longer working as a Mac admin, I'm no longer able to properly maintain the recipes in my repo.

Would anyone be interested in copying the recipes from my repo (https://github.com/autopkg/morgrowe-recipes) into their own?

Cheers
Morgan

**Comment by homebysix** [comment]
Sure, I can take these over. Thanks for keeping them in working order 'til now!

Step 1: https://github.com/autopkg/homebysix-recipes/pull/240
Step 2: https://github.com/autopkg/morgrowe-recipes/pull/12

**Comment by morgrowe** [comment]
Great. I've merged in the depreciation warnings. Thank you.
