### ISSUE TITLE
autopkg version 1.2: "--prefs" flag not working

### ISSUE THREAD

**Issue by jotai73** [autopkg/autopkg#566]
While on a fresh Mojave virtual machine, I executed the steps to test the `--prefs` flag on the 1.2 version of autopkg, and received a "No recipe repos." message:

Here were the steps:

1. I copied the preferences file from the location it was installed to, `~/Library/Preferences/com.github.autopkg.plist`, to a working folder.
2. I renamed the file to autopkg_prefs.plist and ran `defaults delete com.github.autopkg`
3. I ran `autopkg repo-list --prefs ./autopkg_prefs.plist` and it returned: "No recipe repos."
4. The behavior was the same when I converted the file to xml and json.

**Comment by nmcspadden** [comment]
Thanks, I'm able to repro this. Investigating.

**Comment by nmcspadden** [comment]
Fixed by https://github.com/autopkg/autopkg/commit/ec7222335f7a0a191c8c7664ab81de477292f8b7
