### ISSUE TITLE
Add my repo (https://github.com/peetinc/peetinc-recipes)?

### ISSUE THREAD

**Issue by peetinc** [autopkg/autopkg#579]
After being bumped noone had done it, I finally wrote a recipe for Splashtop Streamer and Splashtop Business Access. And after writing them, I see why no one has already. That said, I'd like to give back to someone out there that needs the crap I need.

Cheers.Peet

**Comment by homebysix** [comment]
Hi @peetinc - Could you let me know whether your Kerio Control VPN recipes are still needed, given these exist? https://github.com/autopkg/tbridge-recipes/tree/master/Kerio%20Control%20VPN

Similarly, your MacsFanControl recipes may be similar to these: https://github.com/autopkg/bradclare-recipes/tree/master/MacsFanControl

Thanks!

**Comment by peetinc** [comment]
The Kerio Control VPN is definitely a duplicate. That's on me I'd thought I couldn't override what I needed to on the munki.recipe, and I've removed it. 

bradclare's MacsFanControl is failing CodeSignatureVerifier. I just opened an issue and shot them a MacsFanControl.download.recipe with a working CodeSignatureVerifier. I can pull the recipes from my repo if that's best. 

Cheers.Peet

**Comment by homebysix** [comment]
Hi @peetinc - https://github.com/autopkg/bradclare-recipes/pull/10 has been merged, which should resolve the MacsFanControl CodeSignatureVerifier issue once merged. You can remove your MacsFanControl recipes, if that works for you.

**Comment by homebysix** [comment]
Repo created: https://github.com/autopkg/peetinc-recipes

**Comment by peetinc** [comment]
Thanks for all you do!

As an aside, my brain just could not could not see the the camel case in the CodeSignatureVerifier requirement and of course I was searching with a case-insensitive string ... Doh.
