### ISSUE TITLE
add recipe repo.

### ISSUE THREAD

**Issue by weswhet** [autopkg/autopkg#582]
@nmcspadden add my repo please https://github.com/weswhet/weswhet-recipes. Thanks buddiE.

**Comment by homebysix** [comment]
Hi there @weswhet! Is the `%release_notes%` variable referenced elsewhere in the Munki recipe? If so, I can't find it.

**Comment by homebysix** [comment]
Repo added: https://github.com/autopkg/weswhet-recipes
