### ISSUE TITLE
Add/Fork Repo: kevinmcox-recipes

### ISSUE THREAD

**Issue by kevinmcox** [autopkg/autopkg#606]
Please add my repo to the AutoPkg organization.

https://github.com/kevinmcox/AutoPkg-Recipes

Thanks,
Kevin

**Comment by homebysix** [comment]
These look great, thanks! New repo created: https://github.com/autopkg/kevinmcox-recipes

**Comment by kevinmcox** [comment]
Thanks @homebysix!
