### ISSUE TITLE
Request to add/fork my repo

### ISSUE THREAD

**Issue by joncrain** [autopkg/autopkg#611]
https://github.com/joncrain/joncrain-recipes

Thanks!

**Comment by homebysix** [comment]
Hi @joncrain - It looks like your exacqVision.munki.recipe has trust info added. That's something you'd want to keep in your local override, not your shared recipe. Once that's fixed, I can proceed with the repo fork. Thanks!

**Comment by joncrain** [comment]
I have made the change! And thanks for the help!

**Comment by homebysix** [comment]
Repo created: https://github.com/autopkg/joncrain-recipes
