### ISSUE TITLE
update-trust-info does not catch use of identifier instead of recipe name

### ISSUE THREAD

**Issue by jazzace** [autopkg/autopkg#620]
**Describe the problem**
`autopkg update-trust-info` reports success when specifying an identifier [of an override] instead of a recipe name in the command. The override is not updated.

**Preferences contents**
`"FAIL_RECIPES_WITHOUT_TRUST_INFO" = 1`

**AutoPkg output**
```
% autopkg verify-trust-info -vv local.ds.Fetch
local.ds.Fetch: FAILED
    Processor FetchVersionFixer contents differ from expected.
        Path: /Users/tech/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes/Fetch/FetchVersionFixer.py
    
% autopkg update-trust-info local.ds.Fetch
Wrote updated /Users/tech/Library/AutoPkg/RecipeOverrides/Fetch.ds.recipe
% autopkg run -vv local.ds.Fetch       
Processing local.ds.Fetch...
Failed local trust verification.
Receipt written to /tmp/receipts/local.ds-receipt-20200219-093120.plist

The following recipes failed:
    local.ds.Fetch
        Processor FetchVersionFixer contents differ from expected.
            Path: /Users/tech/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes/Fetch/FetchVersionFixer.py
        

Nothing downloaded, packaged or imported.
% autopkg verify-trust-info -vv local.ds.Fetch 
local.ds.Fetch: FAILED
    Processor FetchVersionFixer contents differ from expected.
        Path: /Users/tech/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes/Fetch/FetchVersionFixer.py
```

**Expected behaviour**
An error message should be thrown that this is not correct syntax and that no update was made. (Alternately, that AutoPkg recognize that the identifier belongs to a recipe override with trust information and that it treat the request as if it had been entered with the proper syntax for that recipe. The first one is easier and promotes literacy.)

**Version (please complete the following information):**
- OS version: 10.15.3
- AutoPkg Version: 2.0.2
- Shell: zsh

**Comment by gregneagle** [comment]
"autopkg update-trust-info reports success when specifying an identifier instead of a recipe name in the command. The override is not updated."

should be

"autopkg update-trust-info reports success when specifying an identifier _**of an override**_ instead of a recipe name in the command. The override is not updated."

The problem is not identifier vs name. The problem is specifying something that points (only) to an override. When using a "simple" name ("Fetch.ds") autopkg can find the original recipe and "ignore" the override.

**Comment by jazzace** [comment]
Yes, you are correct that "of an override" should be added. AutoPkg successfully traps the error if you specify the identifier of a recipe that is not an override (`com.github.githubname.Fetch.munki does not appear to be a recipe override.`). I would suggest that if the bug is fixed by throwing an error message regarding the use of an identifier, then that would also be a more appropriate error message for all cases where an identifier is used with `update-trust-info`.

**Comment by nmcspadden** [comment]
I can't reproduce this. I made an override of hansen-m-recipes Fetch.download, and then modified it:
```
$ ./autopkg verify-trust-info -vv local.download.Fetch
local.download.Fetch: FAILED
    Parent recipe com.github.hansen-m.download.Fetch contents differ from expected.
        Path: /Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes/Fetch/Fetch.download.recipe
    diff --git a/Fetch/Fetch.download.recipe b/Fetch/Fetch.download.recipe
    index e82ceff..f145340 100644
    --- a/Fetch/Fetch.download.recipe
    +++ b/Fetch/Fetch.download.recipe
    @@ -40,7 +40,7 @@
                     <key>url</key>
                     <string>%DOWNLOAD_URL%%dmg%?direct=1</string>
                     <key>filename</key>
    -                <string>%NAME%.dmg</string>
    +                <string>%NAME%.cool.dmg</string>
                 </dict>
             </dict>
             <dict>
$ ./autopkg update-trust-info local.download.Fetch 
Recipe name: local.download.Fetch
Recipe path: /Users/nmcspadden/Library/AutoPkg/RecipeOverrides/Fetch.download.recipe
Wrote updated /Users/nmcspadden/Library/AutoPkg/RecipeOverrides/Fetch.download.recipe
$ ./autopkg verify-trust-info -vv local.download.Fetch
local.download.Fetch: OK
```

**Comment by jazzace** [comment]
The difference between your test and mine was that the Shared Processor was what changed, not the override itself. The shared processor is not called in the .download recipe, only the .pkg recipe (from scriptingosx-recipes). When I re-tested, I changed the hashes for the processor back to the previous values to trigger the trust error. 

There's actually a bigger problem with the recipe chain I was using in that the custom processor exists in both hansen-m and scriptingosx repos. And as of this update, they are different. The pkg recipe uses the short form, so I wonder if there is a context problem here. Let me go ask Armin for a PR on his recipe (which it appears he doesn't use any more) to have it point to the hansen-m processor to eliminate that possibility and come back and do more testing after that.

**Comment by jazzace** [comment]
I have determined that the problem I was having was related to the fact that three recipe repos were involved and two had a processor with the same name (probably written pre-Shared Processors). Here was an interesting test:
1. Edited override so that the hashes for the scriptingosx processor were pasted in, but the hansen-m processor path remained. (I was trying to generate a version mismatch with the processor.)
```
% autopkg verify-trust-info -vv local.ds.Fetch
local.ds.Fetch: FAILED
    Processor FetchVersionFixer contents differ from expected.
        Path: /Users/tech/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes/Fetch/FetchVersionFixer.py
    
% autopkg update-trust-info local.ds.Fetch    
Wrote updated /Users/tech/Library/AutoPkg/RecipeOverrides/Fetch.ds.recipe
```
That changed the path value in the override to the scriptingosx path and kept the hashes (not what I would have expected). That wasn't desired, so once again:
```
% autopkg update-trust-info local.ds.Fetch
Wrote updated /Users/tech/Library/AutoPkg/RecipeOverrides/Fetch.ds.recipe
```
Now the hashes and the path reflect the hansen-m version of the processor. (!!) So:
```
% autopkg verify-trust-info -vv local.ds.Fetch
local.ds.Fetch: FAILED
    Processor FetchVersionFixer contents differ from expected.
        Path: /Users/tech/Library/AutoPkg/RecipeRepos/com.github.autopkg.scriptingosx-recipes/Fetch/FetchVersionFixer.py
```
Waiting 10 minutes and making no modifications:
```
% autopkg verify-trust-info -vv local.ds.Fetch
local.ds.Fetch: OK
```

This leads me to believe that this is a specific problem with the code confusing named processors, not anything to do with the fact that an identifier was used. Closing this issue. (Based on the fact we have a syntax for shared processors that we didn't originally, I'm not going to file a separate issue for the same-named processor issue, since it should rarely appear.)
