### ISSUE TITLE
MUNKI_REPO not picking up afp protocol

### ISSUE THREAD

**Issue by tonyrsutton** [autopkg/autopkg#623]
**Describe the problem**
MUNKI_REPO was set with the afp path to the filestore of where I save my Munki_repo files. But when I did a **autopkg run xxx.munki** - I see this error message:

_MunkiImporter requires missing argument MUNKI_REPO_

I have done a **defaults read com.github.autopkg** and it looks fine to me

**Preferences contents**
*BE SURE TO SANITIZE ANY SENSITIVE DATA SUCH AS PASSWORDS OR ADDRESSES.*

{
"MUNKI_REPO" = "afp://servername.host/Munki_repo";
}

**Expected behavior**
Connects to the afp and save the files in there

**Version (please complete the following information):**
 - MacOS Catalina 10.15.3
- AutoPkg Version: 2.0.2

** Additional comment.

I have searched on the WiKi and can not see if afp/smb are supported. If it's supported, please let me know where I can find the wiki for this?
If it's not supported, can we make a feature request for this?

Thanks.

**Comment by gregneagle** [comment]
Only local file paths are supported. Mounting those paths from a fileshare usually requires authentication. Storing that securely in Autopkg preferences is not a problem the Autopkg devs care to tackle.

**Comment by gregneagle** [comment]
The expectation is that you have the repo mounted and available before running Autopkg.

**Comment by nmcspadden** [comment]
There's no plan to support alternative URIs at this time.

**Comment by tonyrsutton** [comment]
Thank you, all. I will tackle this in a different way.
