### ISSUE TITLE
Please add my repo

### ISSUE THREAD

**Issue by ahousseini** [autopkg/autopkg#631]
Hi

I would like to add my repository:

https://github.com/ahousseini/ahousseini-recipes

**Comment by homebysix** [comment]
Hi @ahousseini - On first glance, there are a few issues I'd point out:

- It looks like you've got a duplicate key in this recipe: https://github.com/ahousseini/ahousseini-recipes/blob/master/WirelessMedia/WirelessMedia.download.recipe#L43-L44

- You have a few hard-coded version numbers in paths, and those probably won't work for future versions of their software titles. For example:
    - https://github.com/ahousseini/ahousseini-recipes/blob/master/SketchBook/SketchBook.download.recipe#L45
    - https://github.com/ahousseini/ahousseini-recipes/blob/master/SketchBook/SketchBook.download.recipe#L56
    - https://github.com/ahousseini/ahousseini-recipes/blob/master/SeaDrive/SeaDrive.download.recipe#L26
    - https://github.com/ahousseini/ahousseini-recipes/blob/master/WorkSpace/WorkSpace.download.recipe#L24
    - https://github.com/ahousseini/ahousseini-recipes/blob/master/MountainDuck/MountainDuck.download.recipe#L26

- The following recipes aren't running successfully for me at the moment:
    - MagicPrefs/MagicPrefs.download.recipe
    - DriveDx/DriveDx.download.recipe

- There are many recipes in your repo that appear to duplicate existing recipe functionality. While duplicates aren't uncommon, we discourage duplication unless it's for a specific reason.
    - DBeaver.download
    - Dash.download
    - Fantastical.download
    - Freeplane.download
    - Freeplane.pkg
    - GanttProject.download
    - GanttProject.pkg
    - GeoGebraClassic6.download
    - GeoGebraClassic6.pkg
    - GoogleEarthPro.download
    - GoogleEarthPro.pkg
    - MendeleyDesktop.download
    - MendeleyDesktop.pkg
    - MountainDuck.download
    - MountainDuck.pkg
    - OmniFocus3.pkg
    - PyCharm.pkg
    - SilhouetteStudio.download
    - SilhouetteStudio.pkg
    - Sonos.download
    - Sonos.pkg
    - Stellarium.pkg
    - balenaEtcher.download
    - balenaEtcher.pkg
    - drawio.download
    - drawio.pkg
    - iStopMotion.download
    - iStopMotion.pkg
    - jamf-migrator.pkg
    - zoom.download
    - zoom.pkg
    - zoom.install

**Comment by homebysix** [comment]
Hi @ahousseini - I see you've resolved most of the issues I noted above. I'll create the new repo, but please do keep our preference for non-duplication of existing recipes in mind. Thank you!

New repo: https://github.com/autopkg/ahousseini-recipes
