### ISSUE TITLE
PkgCreator chokes on valid version number

### ISSUE THREAD

**Issue by Honestpuck** [autopkg/autopkg#641]
**Describe the problem**
Building a package for "Appium-1.1.17-1" and I get the error: `Error in local.pkg.Appium: Processor: PkgCreator: Error: Invalid version component "1-1"` That version number parses fine with semantic versioning and package.version.parse.

Looking for the error text I find that it's come from `autopkgserver` `packager.py` line 233 and that the component `1-1` fails the regular expression defined in line 34: `re_version = re.compile(r"^[a-z0-9_ ]*[0-9][a-z0-9_ ]*$", re.I)`

BTW - the parent recipe is `com.github.blackthroat.download.Appium`, here's the PkgCreator block.

```
<key>Processor</key>
<string>PkgCreator</string>
<key>Arguments</key>
<dict>
    <key>pkgname</key>
    <string>%NAME%-%version%</string>
    <key>pkg_request</key>
    <dict>
        <key>pkgdir</key>
        <string>%RECIPE_CACHE_DIR%</string>
        <key>id</key>
        <string>%PKG_ID%</string>
        <key>options</key>
        <string>purge_ds_store</string>
        <key>chown</key>
        <array>
            <dict>
                <key>path</key>
                <string>Applications</string>
                <key>user</key>
                <string>root</string>
                <key>group</key>
                <string>admin</string>
            </dict>
        </array>
    </dict>
</dict>
```

**Preferences contents**
Just my repo list. 
```
https://github.com/autopkg/recipes
https://github.com/autopkg/rtrouton-recipes
https://github.com/autopkg/hansen-m-recipes
https://github.com/autopkg/hjuutilainen-recipes
https://github.com/autopkg/homebysix-recipes
https://github.com/autopkg/moofit-recipes
https://github.com/autopkg/rderewianko-recipes
https://github.com/autopkg/dataJAR-recipes
https://github.com/autopkg/HobbitHardcase-recipes
https://github.com/autopkg/novaksam-recipes
https://github.com/autopkg/justinrummel-recipes
https://github.com/autopkg/keeleysam-recipes
https://github.com/autopkg/arubdesu-recipes
https://github.com/autopkg/gregneagle-recipes
https://github.com/autopkg/fishd72-recipes
https://github.com/autopkg/mosen-recipes
https://github.com/autopkg/blackthroat-recipes
https://github.com/autopkg/chilcote-recipes
https://github.com/autopkg/MichalMMac-recipes
https://github.com/autopkg/valdore86-recipes
https://github.com/autopkg/aysiu-recipes
https://github.com/autopkg/jleggat-recipes
https://github.com/facebook/Recipes-for-AutoPkg
https://github.com/autopkg/grahampugh-recipes
https://github.com/autopkg/48kRAM-recipes
https://github.com/autopkg/foigus-recipes
https://github.com/autopkg/adobe-ccp-recipes
https://github.com/autopkg/n8felton-recipes
https://github.com/autopkg/tbridge-recipes
```
(That's in search order).
**AutoPkg output**
```
autopkg run Appium.pkg
Processing Appium.pkg...
Invalid version component "1-1"
Failed.

The following recipes failed:
    Appium.pkg
        Error in local.pkg.Appium: Processor: PkgCreator: Error: Invalid version component "1-1"

Nothing downloaded, packaged or imported.
```

**Expected behavior**
A nice built package called "Appium-1.17.1-1.pkg"

**Version (please complete the following information):**
 - OS version: 10.15.6
- AutoPkg Version: 2.1

**Comment by taagaard** [comment]
Yeah, I just ran into this problem, too.

What is the reasoning behind using custom version checking (packager.py, lines 225-234)

`        # Check version.
        if len(self.request["version"]) > 40:
            raise PackagerError("Version too long")
        components = self.request["version"].split(".")
        if len(components) < 1:
            raise PackagerError(f"Invalid version \"{self.request['version']}\"")
        for comp in components:
            if not self.re_version.search(comp):
                raise PackagerError(f'Invalid version component "{comp}"')
        self.log.debug("version ok")`

rather than delegating to package.version.parse?

**Comment by magnusviri** [comment]
I'm having this problem too. Do versions really have to conform to this regex in order to build a package?
 
     re_version = re.compile(r"^[a-z0-9_ ]*[0-9][a-z0-9_ ]*$", re.I)

Is there any way to modify and clean up a version string before calling PkgCreator? The only way I can think of doing this is by writing a custom processor or using URLTextSearcher to try to clean up the version.

**Comment by Honestpuck** [comment]
@magnusviri We could see about coming up with code change to use semantic versioning and see if a PR would be accepted.  I could add it to my long list of things to do between now and JNUC :)

 It may be possible to catch the error above and try semantic versioning. That way no existing recipes would break.

**Comment by nmcspadden** [comment]
What happens in Munki if you try to import a package with a hyphen in the version?

**Comment by Honestpuck** [comment]
No idea, Nick.
