### ISSUE TITLE
Please fork my repo

### ISSUE THREAD

**Issue by jc0b** [autopkg/autopkg#668]
Hi,

I would like my repo (https://github.com/jc0b/jc0b-recipes.git) to be forked by AutoPkg.

Thanks!

**Comment by homebysix** [comment]
Hi @jc0b - Right now, it looks like the only recipes you have in the repo are redundant with [some recipes offered by kevinmcox](https://github.com/autopkg/kevinmcox-recipes/tree/master/Mothers%20Ruin%20Software). We do [discourage](https://github.com/autopkg/autopkg/wiki/Sharing-Recipes#repo-maintenance-expectations) duplicating the function of existing recipes, unless there's a good reason to do so.

**Comment by jc0b** [comment]
Ah ok, I somehow hadn't spotted those. Thanks!
