### ISSUE TITLE
Auto Pkg2.0 post install error

### ISSUE THREAD

**Issue by tsinghzf** [autopkg/autopkg#669]
**Describe the problem**
After updating from autopkg1.4 to autopkg 2.0, 
I am receiving an error

**AutoPkg output**
*BE SURE TO SANITIZE ANY SENSITIVE DATA SUCH AS PASSWORDS OR ADDRESSES.*
raceback (most recent call last):
  File "/usr/local/bin/autopkg", line 36, in <module>
    import autopkglib.github
  File "/Library/AutoPkg/autopkglib/__init__.py", line 854, in <module>
    import_processors()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 747, in import_processors
    __import__(mydirname + "." + name, fromlist=[name]), name
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 30, in <module>
    import jss
  File "/Library/Application Support/JSSImporter/jss/__init__.py", line 62, in <module>
    from .jamf_software_server import JSS
  File "/Library/Application Support/JSSImporter/jss/jamf_software_server.py", line 45, in <module>
    import distribution_points
ModuleNotFoundError: No module named 'distribution_points'

**Expected behavior**
A clear and concise description of what you expected to happen. What specific part of the recipe or AutoPkg run did not behave correctly?
Updated search path:
  '.'
  '~/Library/AutoPkg/Recipes'
  '/Library/AutoPkg/Recipes'
  '/Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.sheagcraig-recipes'
  '/Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.justinrummel-recipes'
  '/Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.gmarnin-recipes'
  '/Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.novaksam-recipes'
  '/Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.jleggat-recipes'
  '/Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes'
  '/Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.kitzy-recipes'
  '/Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.gerardkok-recipes'
  '/Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.jss-recipes'
  '/Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes'
  '/Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.keeleysam-recipes'
  '/Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes'
  '/Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.crystalllized-recipes'
  '/Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.nmcspadden-recipes'
  '/Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes'
  '/Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.cgerke-recipes'
  '/Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes'
  '/Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.bkerns-recipes'
  '/Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.autopkg'
  '/Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.jlehikoinen-recipes'
  '/Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.scriptingosx-recipes'
  '/Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.peshay-recipes'
  '/Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.jaharmi-recipes'
  '/Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.golbiga-recipes'
  '/Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes'
  '/Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.killahquam-recipes'
  '/Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.moofit-recipes'
  '/Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.blackthroat-recipes'
Updating existing repos
Attempting git pull for /Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.jleggat-recipes...
Already up to date.

Attempting git pull for /Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.bkerns-recipes...
Already up to date.

Attempting git pull for /Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.kitzy-recipes...
Already up to date.

Attempting git pull for /Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.golbiga-recipes...
Already up to date.

Attempting git pull for /Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.jlehikoinen-recipes...
Already up to date.

Attempting git pull for /Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes...
Already up to date.

Attempting git pull for /Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes...
Already up to date.

Attempting git pull for /Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes...
Already up to date.

Attempting git pull for /Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.justinrummel-recipes...
Already up to date.

Attempting git pull for /Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.moofit-recipes...
Already up to date.

Attempting git pull for /Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.scriptingosx-recipes...
Already up to date.

Attempting git pull for /Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.killahquam-recipes...
Already up to date.

Attempting git pull for /Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.nmcspadden-recipes...
Already up to date.

Attempting git pull for /Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.autopkg...
Already up to date.

Attempting git pull for /Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.sheagcraig-recipes...
Already up to date.

Attempting git pull for /Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.cgerke-recipes...
Already up to date.

Attempting git pull for /Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.jss-recipes...
Already up to date.

Attempting git pull for /Users/security/Library/AutoPkg/RecipeRepos/com.github.autopkg.blackthroat-recipes...
Already up to date.

**Version (please complete the following information):**
 - OS version: 10.14.4
- AutoPkg Version: latest v2.0, all v2 cause the issue

**Comment by homebysix** [comment]
Hi @tsinghzf - It looks like you have JSSImporter installed. Do you have the latest version of JSSImporter?

**Comment by nmcspadden** [comment]
This is a JSSImporter issue, not an Autopkg issue specifically, so please follow up with the JSSImporter project for support on that.
