### ISSUE TITLE
dmg mounting not working as expected

### ISSUE THREAD

**Issue by jutonium** [autopkg/autopkg#674]
The FileFinder processor will try to mount the given path until the first occurrence of .dmg. E.g. the pattern is /Users/jutonium/Library/AutoPkg/Cache/xyz.dmg/downloads/xyz.dmg/*.app
The processor fails because hdiutil failed to mount /Users/jutonium/Library/AutoPkg/Cache/xyz.dmg

**Comment by gregneagle** [comment]
Yes, you are correct, the various processors that can access files in a disk image do not handle nested disk images.

**Comment by nmcspadden** [comment]
This is more or less by design, and not likely to change. Nested DMGs simply aren't supported, and I've yet to ever actually see one in the wild.

If this is something you need to address, you'll probably have to use Copier to copy the nested DMG out of the parent DMG, and then use FileFinder on the newly copied one.

**Comment by jutonium** [comment]
I didn't describe the problem clear enough: There are no nested disk images.
/Users/jutonium/Library/AutoPkg/Cache/xyz.dmg is a path in the file system with xyz.dmg being the caching directory created by running a recipe called xyz.dmg.recipe. The recipe did download a disk image and placed it in xyz.dmg/download/xyz.dmg.
The FileFinder tries to mount the directory /Users/jutonium/Library/AutoPkg/Cache/**xyz.dmg** instead of the disk image contained in /Users/jutonium/Library/AutoPkg/Cache/xyz.dmg/download/**xyz.dmg**

Here is the output of autopkg -vvv
FileFinder
{'Input': {'pattern': '/Users/jutonium/Library/AutoPkg/Cache/com.github.wycomco.sipgate-softphone.dmg/downloads/sipgate-softphone.dmg/*.app'}}
FileFinder: No value supplied for find_method, setting default value of: glob
FileFinder: hdiutil imageinfo error hdiutil: imageinfo failed - image not recognised
 with image /Users/jutonium/Library/AutoPkg/Cache/com.github.wycomco.sipgate-softphone.dmg.
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/FileFinder.py", line 85, in main
    mount_point = self.mount(dmg_path)
  File "/Library/AutoPkg/autopkglib/DmgMounter.py", line 134, in mount
    raise ProcessorError(f"mounting {pathname} failed: {stderr}")
autopkglib.ProcessorError: mounting /Users/jutonium/Library/AutoPkg/Cache/com.github.wycomco.sipgate-softphone.dmg failed: hdiutil: attach failed - image not recognised

**Comment by gregneagle** [comment]
So address the problem by giving the recipe a different name.

**Comment by jutonium** [comment]
I did. I called it .img.recipe.
I did not expect the behaviour of trying to mount the first part of path that looks like .dmg instead of the last match.
