### ISSUE TITLE
Host is down

### ISSUE THREAD

**Issue by mikafletcher** [autopkg/autopkg#684]
hello, I'm trying to use munkiiport on a Mac 10.3.6 using the terminal.
But I keep getting this message :
Could not connect to munki repo: Error mounting url "afp://Users/Shared/munki_repo": Host is down, error 64

MunkiAdmin works ok with AutoPkgr, but not using the terminal

I'm using the latest versions (munkitools-5.0.1.4059)

**Comment by gregneagle** [comment]
"afp://Users/Shared/munki_repo" does not seem to be a valid URL for a Munki repo.

**Comment by nmcspadden** [comment]
You almost certainly do not want afp:// as your repo location, if you are trying to use a local file path. 

Please consult these two wikis:
https://github.com/autopkg/autopkg/wiki/Getting-Started#optional-configure-for-use-with-munki
https://github.com/munki/munki/wiki/Demonstration-Setup#populating-the-repo
