### ISSUE TITLE
AutoPKG Upgrade path and system requirements.

### ISSUE THREAD

**Issue by Minspace32** [autopkg/autopkg#687]
I am current running AutoPKG verion 1.4.2 on Mac Sierra. 

I have tried using the inbuilt updater to upgrade to 2.2. After it downloads the file I get a prompt to enter admin username and password. after which it attempts to install the package but this does not upgrade AutoPKG.

What are the system  requirements to run the latest Auto PKG? What is the recommended upgrade path to the lastest.

**Comment by homebysix** [comment]
Hi @Minspace32 - Is it possible you're using AutoPkgr (the Mac app)? The autopkg command line tool does not have a built-in updater.

**Comment by Minspace32** [comment]
Yes it is the Mac app.  I am new to this sorry for wasting your time.

**Comment by homebysix** [comment]
Sounds good. I'll close this issue.

According to AutoPkgr's latest release notes, the required minimum macOS version is 10.13.

AutoPkg itself "may" work on older releases, but is only tested on the current macOS release.
