### ISSUE TITLE
Pleas add repo

### ISSUE THREAD

**Issue by yngast** [autopkg/autopkg#688]
Hi 
Could you please add https://github.com/yngast/recipes/tree/master/JetBrains
to the recipe-repo?

**Comment by arubdesu** [comment]
Hey there, thanks for opening an issue! Jetbrains toolbox recipes already exist, do they not work for you?
```
JetBrainsToolbox.pkg.recipe          crystalllized-recipes     JetBrains Toolbox/JetBrainsToolbox.pkg.recipe
JetBrainsToolbox.jss.recipe          crystalllized-recipes     JetBrains Toolbox/JetBrainsToolbox.jss.recipe
JetBrainsToolbox.download.recipe     crystalllized-recipes     JetBrains Toolbox/JetBrainsToolbox.download.recipe
```

**Comment by yngast** [comment]
Hi, 
Oh, never found them when I was searching for them, but yeah they will work perfectly.
Never mind the request then.
Thanks.
Y
