### ISSUE TITLE
Please add lrz-recipes

### ISSUE THREAD

**Issue by ChrOst** [autopkg/autopkg#691]
https://github.com/ChrOst/lrz-recipes

It currently just contains a POST Processor named "NotifyPatchServer", readme and Details will follow.

**Comment by homebysix** [comment]
Before I review this, could you add a readme to the repo with post-processor usage information and intended benefits? I see that there's already some info in the comments of the processor itself, but better to make the information accessible when browsing the repo on GitHub in my opinion.

**Comment by ChrOst** [comment]
Added some description/readme.

**Comment by homebysix** [comment]
New repo created: https://github.com/autopkg/lrz-recipes
