### ISSUE TITLE
Add/fork my recipe repo

### ISSUE THREAD

**Issue by skoobasteeve** [autopkg/autopkg#692]
I've only created one recipe so far but I anticipate more as the need arises. Can you please add my repo to the Autopkg account? Link below:

https://github.com/skoobasteeve/skoobasteeve-recipes.git

Let me know if you have any questions or need anything more from my end.

Thank you!

**Comment by homebysix** [comment]
Looks good. New repo created: https://github.com/autopkg/skoobasteeve-recipes
