### ISSUE TITLE
Please add/fork my repository

### ISSUE THREAD

**Issue by oliverweinm** [autopkg/autopkg#694]
Hi AutoPkgers,

I have create a Github repository with my own recipes: https://github.com/oliverweinm/oliverweinm-recipes

I would like to make these recipes accessible for the wider AutoPkg community, so please add/fork my repo.
A readme listing all the existing recipes is also available on there. 

Cheers,
oliverweinm

**Comment by homebysix** [comment]
Repo created: https://github.com/autopkg/oliverweinm-recipes

I'll submit a PR or two shortly to help align with recipe conventions.
