### ISSUE TITLE
Add members to recipe repo team

### ISSUE THREAD

**Issue by choules** [autopkg/autopkg#705]
Dear AutoPkg team,

could you please add my colleagues @a-vogel and @stankewitz to our team [wycomco-recipes](https://github.com/orgs/autopkg/teams/wycomco-recipes/members)?

Thanks in advance!
Matthias

**Comment by homebysix** [comment]
Invitations sent.

**Comment by a-vogel** [comment]
Sorry, I missed the invitation (it was sent, though). Apologies for this. Can you please re-send me the invitation? That would be great.

**Comment by homebysix** [comment]
@a-vogel Invitation resent.

**Comment by a-vogel** [comment]
Thanks a lot!
