### ISSUE TITLE
Add/fork repo (recipe for Syncthing app)

### ISSUE THREAD

**Issue by ctueck** [autopkg/autopkg#706]
I'd like to make my recipe repo available to others and thus ask to fork/copy.

It's actually just one single set of two recipes for [Syncthing](https://syncthing.net/). If that's under the threshold of relevance I do understand, of course - but there didn't seem to be a specific requirement for a repo to be big. :)

Repo URL is: https://github.com/ctueck/munki-recipes

**Comment by homebysix** [comment]
Repo created: https://github.com/autopkg/ctueck-recipes
