### ISSUE TITLE
Please fork repo

### ISSUE THREAD

**Issue by ucam-apple-support** [autopkg/autopkg#707]
Can you please fork the repo https://github.com/ucam-apple-support/autopkg_recipes? If you could name the fork com.github.autopkg.ucam-recipes that would be ideal.

Thanks,
James

**Comment by homebysix** [comment]
Hi James - The reverse-domain naming is typically used for recipe identifiers, not the repositories that contain them. The default name for your repo would be autopkg/ucam-apple-support-recipes. Is that acceptable?

**Comment by ucam-apple-support** [comment]
Sorry, my misunderstanding. Setting the name to autopkg/ucam-apple-support-recipes would be fine.

Thanks,

James

**Comment by homebysix** [comment]
New repo created: https://github.com/autopkg/ucam-apple-support-recipes
