### ISSUE TITLE
Failure to decode extended attributes in URLDownloader causes etag/last-modified comparison to fail

### ISSUE THREAD

**Issue by homebysix** [autopkg/autopkg#713]
## Issue description

An instance of `.decode()` that [exists](https://github.com/autopkg/autopkg/blob/e36d5cba2823dbdfcb69a41a38b1aef9fb76121c/Code/autopkglib/URLDownloader.py#L119) on the master branch now has been [removed](https://github.com/autopkg/autopkg/commit/5ba42491feb9a255c23ed0bf0eb221b9292aa382#r47168930) on the dev branch, leading to failed etag and last-modified comparisons, among other potential problems. This has two symptoms:

- recoverable: software installers are re-downloaded unnecessarily due to AutoPkg thinking the file on the server does not match the file in the cache
- non-recoverable: some downloads fail due to the injection of binary characters into the curl command headers

The non-recoverable symptom only occurs with certain recipes, depending on the configuration of the web server hosting the download.

## Environment

- AutoPkg version: `dev` branch (and all branches derived from it)
- macOS version: 11.2.1
- Preferences not a factor

### Unnecessary re-download

1. Switch to the `dev` branch of a local AutoPkg clone.
1. Clear the AutoPkg cache:

        % rm -rf ~/Library/AutoPkg/Cache

1. Run the Google Chrome download recipe once (`-c` "check" mode is sufficient to demonstrate the issue):

        % ./Code/autopkg run -vvcq GoogleChrome.download
        Processing GoogleChrome.download...
        WARNING: GoogleChrome.download is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
        URLDownloader
        {'Input': {'filename': 'GoogleChrome.dmg',
                   'url': 'https://dl.google.com/chrome/mac/universal/stable/GGRO/googlechrome.dmg'}}
        URLDownloader: No value supplied for prefetch_filename, setting default value of: False
        URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
        URLDownloader: Storing new Last-Modified header: Sat, 13 Feb 2021 05:20:45 GMT
        URLDownloader: Storing new ETag header: "85fb96"
        URLDownloader: Downloaded ~/Library/AutoPkg/Cache/com.github.autopkg.download.googlechrome/downloads/GoogleChrome.dmg
        {'Output': {'download_changed': True,
                    'etag': '"85fb96"',
                    'last_modified': 'Sat, 13 Feb 2021 05:20:45 GMT',
                    'pathname': '~/Library/AutoPkg/Cache/com.github.autopkg.download.googlechrome/downloads/GoogleChrome.dmg',
                    'url_downloader_summary_result': {'data': {'download_path': '~/Library/AutoPkg/Cache/com.github.autopkg.download.googlechrome/downloads/GoogleChrome.dmg'},
                                                      'summary_text': 'The following '
                                                                      'new items were '
                                                                      'downloaded:'}}}
        EndOfCheckPhase
        {'Input': {}}
        {'Output': {}}
        Receipt written to ~/Library/AutoPkg/Cache/com.github.autopkg.download.googlechrome/receipts/GoogleChrome-receipt-20210220-160821.plist

        The following new items were downloaded:
            Download Path
            -------------
            ~/Library/AutoPkg/Cache/com.github.autopkg.download.googlechrome/downloads/GoogleChrome.dmg

    The installer downloads as expected.

1. Run the Google Chrome download recipe a second time and observe the installer downloaded a second time, and `download_changed` is incorrectly set to True:

        % ./Code/autopkg run -vvcq GoogleChrome.download
        Processing GoogleChrome.download...
        WARNING: GoogleChrome.download is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
        URLDownloader
        {'Input': {'filename': 'GoogleChrome.dmg',
                   'url': 'https://dl.google.com/chrome/mac/universal/stable/GGRO/googlechrome.dmg'}}
        URLDownloader: No value supplied for prefetch_filename, setting default value of: False
        URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
        URLDownloader: Storing new Last-Modified header: Sat, 13 Feb 2021 05:20:45 GMT
        URLDownloader: Storing new ETag header: "85fb96"
        URLDownloader: Downloaded ~/Library/AutoPkg/Cache/com.github.autopkg.download.googlechrome/downloads/GoogleChrome.dmg
        {'Output': {'download_changed': True,
                    'etag': '"85fb96"',
                    'last_modified': 'Sat, 13 Feb 2021 05:20:45 GMT',
                    'pathname': '~/Library/AutoPkg/Cache/com.github.autopkg.download.googlechrome/downloads/GoogleChrome.dmg',
                    'url_downloader_summary_result': {'data': {'download_path': '~/Library/AutoPkg/Cache/com.github.autopkg.download.googlechrome/downloads/GoogleChrome.dmg'},
                                                      'summary_text': 'The following '
                                                                      'new items were '
                                                                      'downloaded:'}}}
        EndOfCheckPhase
        {'Input': {}}
        {'Output': {}}
        Receipt written to ~/Library/AutoPkg/Cache/com.github.autopkg.download.googlechrome/receipts/GoogleChrome-receipt-20210220-160841.plist

        The following new items were downloaded:
            Download Path
            -------------
            ~/Library/AutoPkg/Cache/com.github.autopkg.download.googlechrome/downloads/GoogleChrome.dmg

**Desired behavior**: The cached Chrome download should be used on the second run, rather than re-downloading.

### Failed re-download

1. Clear the AutoPkg cache again:

        % rm -rf ~/Library/AutoPkg/Cache

1. Add the homebysix-recipes repo:

        % ./Code/autopkg repo-add homebysix-recipes

1. Run the NativeConnect download recipe:

        % ./Code/autopkg run -vvcq NativeConnect.download
        Processing NativeConnect.download...
        WARNING: NativeConnect.download is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
        URLTextSearcher
        {'Input': {'re_pattern': '"id":(\\d+),',
                   'result_output_var_name': 'release_id',
                   'url': 'https://install.appcenter.ms/api/v0.1/apps/vadim.shpakovski/nativeconnect/distribution_groups/public/public_releases'}}
        URLTextSearcher: Found matching text (release_id): 237
        {'Output': {'release_id': '237'}}
        URLTextSearcher
        {'Input': {'re_pattern': '"download_url":"(https:\\/\\/.+\\.app\\.zip\\?.+)","install_url":',
                   'result_output_var_name': 'url',
                   'url': 'https://install.appcenter.ms/api/v0.1/apps/vadim.shpakovski/nativeconnect/distribution_groups/public/releases/237'}}
        URLTextSearcher: Found matching text (url): https://appcenter-filemanagement-distrib1ede6f06e.azureedge.net/7925c789-5201-447b-859b-c006058ef156/NativeConnect-1.2.11-457D2D2.app.zip?sv=2019-02-02&sr=c&sig=x%2BNkdCBBY%2F5ZEDl21uw9MJLuaS1HdNh4zkRfUO4zKH8%3D&se=2021-02-21T18%3A14%3A06Z&sp=r
        {'Output': {'url': 'https://appcenter-filemanagement-distrib1ede6f06e.azureedge.net/7925c789-5201-447b-859b-c006058ef156/NativeConnect-1.2.11-457D2D2.app.zip?sv=2019-02-02&sr=c&sig=x%2BNkdCBBY%2F5ZEDl21uw9MJLuaS1HdNh4zkRfUO4zKH8%3D&se=2021-02-21T18%3A14%3A06Z&sp=r'}}
        URLDownloader
        {'Input': {'filename': 'NativeConnect.zip',
                   'url': 'https://appcenter-filemanagement-distrib1ede6f06e.azureedge.net/7925c789-5201-447b-859b-c006058ef156/NativeConnect-1.2.11-457D2D2.app.zip?sv=2019-02-02&sr=c&sig=x%2BNkdCBBY%2F5ZEDl21uw9MJLuaS1HdNh4zkRfUO4zKH8%3D&se=2021-02-21T18%3A14%3A06Z&sp=r'}}
        URLDownloader: No value supplied for prefetch_filename, setting default value of: False
        URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
        URLDownloader: Storing new Last-Modified header: Mon, 07 Sep 2020 08:33:09 GMT
        URLDownloader: Storing new ETag header: "0x8D85308A674FEA4"
        URLDownloader: Downloaded ~/Library/AutoPkg/Cache/com.github.homebysix.download.NativeConnect/downloads/NativeConnect.zip
        {'Output': {'download_changed': True,
                    'etag': '"0x8D85308A674FEA4"',
                    'last_modified': 'Mon, 07 Sep 2020 08:33:09 GMT',
                    'pathname': '~/Library/AutoPkg/Cache/com.github.homebysix.download.NativeConnect/downloads/NativeConnect.zip',
                    'url_downloader_summary_result': {'data': {'download_path': '~/Library/AutoPkg/Cache/com.github.homebysix.download.NativeConnect/downloads/NativeConnect.zip'},
                                                      'summary_text': 'The following '
                                                                      'new items were '
                                                                      'downloaded:'}}}
        EndOfCheckPhase
        {'Input': {}}
        {'Output': {}}
        Receipt written to ~/Library/AutoPkg/Cache/com.github.homebysix.download.NativeConnect/receipts/NativeConnect-receipt-20210220-161030.plist

        The following new items were downloaded:
            Download Path
            -------------
            ~/Library/AutoPkg/Cache/com.github.homebysix.download.NativeConnect/downloads/NativeConnect.zip

    The installer downloads as expected.

1. Run the NativeConnect download recipe a second time:

        % ./Code/autopkg run -vvcq NativeConnect.download
        Processing NativeConnect.download...
        WARNING: NativeConnect.download is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
        URLTextSearcher
        {'Input': {'re_pattern': '"id":(\\d+),',
                   'result_output_var_name': 'release_id',
                   'url': 'https://install.appcenter.ms/api/v0.1/apps/vadim.shpakovski/nativeconnect/distribution_groups/public/public_releases'}}
        URLTextSearcher: Found matching text (release_id): 237
        {'Output': {'release_id': '237'}}
        URLTextSearcher
        {'Input': {'re_pattern': '"download_url":"(https:\\/\\/.+\\.app\\.zip\\?.+)","install_url":',
                   'result_output_var_name': 'url',
                   'url': 'https://install.appcenter.ms/api/v0.1/apps/vadim.shpakovski/nativeconnect/distribution_groups/public/releases/237'}}
        URLTextSearcher: Found matching text (url): https://appcenter-filemanagement-distrib1ede6f06e.azureedge.net/7925c789-5201-447b-859b-c006058ef156/NativeConnect-1.2.11-457D2D2.app.zip?sv=2019-02-02&sr=c&sig=lEvF2qS3XBZ8S063s8ovev6PT6TF7tDGAVQqrDh%2BCzo%3D&se=2021-02-21T21%3A09%3A42Z&sp=r
        {'Output': {'url': 'https://appcenter-filemanagement-distrib1ede6f06e.azureedge.net/7925c789-5201-447b-859b-c006058ef156/NativeConnect-1.2.11-457D2D2.app.zip?sv=2019-02-02&sr=c&sig=lEvF2qS3XBZ8S063s8ovev6PT6TF7tDGAVQqrDh%2BCzo%3D&se=2021-02-21T21%3A09%3A42Z&sp=r'}}
        URLDownloader
        {'Input': {'filename': 'NativeConnect.zip',
                   'url': 'https://appcenter-filemanagement-distrib1ede6f06e.azureedge.net/7925c789-5201-447b-859b-c006058ef156/NativeConnect-1.2.11-457D2D2.app.zip?sv=2019-02-02&sr=c&sig=lEvF2qS3XBZ8S063s8ovev6PT6TF7tDGAVQqrDh%2BCzo%3D&se=2021-02-21T21%3A09%3A42Z&sp=r'}}
        URLDownloader: No value supplied for prefetch_filename, setting default value of: False
        URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
        Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://appcenter-filemanagement-distrib1ede6f06e.azureedge.net/7925c789-5201-447b-859b-c006058ef156/NativeConnect-1.2.11-457D2D2.app.zip?sv=2019-02-02&sr=c&sig=lEvF2qS3XBZ8S063s8ovev6PT6TF7tDGAVQqrDh%2BCzo%3D&se=2021-02-21T21%3A09%3A42Z&sp=r', '--fail', '--output', '~/Library/AutoPkg/Cache/com.github.homebysix.download.NativeConnect/downloads/tmpi9t6ie47', '--header', 'If-None-Match: b\'"0x8D85308A674FEA4"\'', '--header', "If-Modified-Since: b'Mon, 07 Sep 2020 08:33:09 GMT'"]' returned non-zero exit status 22.
        Failed.
        Receipt written to ~/Library/AutoPkg/Cache/com.github.homebysix.download.NativeConnect/receipts/NativeConnect-receipt-20210220-161205.plist

        The following recipes failed:
            NativeConnect.download
                Error in com.github.homebysix.download.NativeConnect: Processor: URLDownloader: Error: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://appcenter-filemanagement-distrib1ede6f06e.azureedge.net/7925c789-5201-447b-859b-c006058ef156/NativeConnect-1.2.11-457D2D2.app.zip?sv=2019-02-02&sr=c&sig=lEvF2qS3XBZ8S063s8ovev6PT6TF7tDGAVQqrDh%2BCzo%3D&se=2021-02-21T21%3A09%3A42Z&sp=r', '--fail', '--output', '~/Library/AutoPkg/Cache/com.github.homebysix.download.NativeConnect/downloads/tmpi9t6ie47', '--header', 'If-None-Match: b\'"0x8D85308A674FEA4"\'', '--header', "If-Modified-Since: b'Mon, 07 Sep 2020 08:33:09 GMT'"]' returned non-zero exit status 22.

        Nothing downloaded, packaged or imported.

    The download fails. Observe the `If-None-Match` and `If-Modified-Since` headers in the curl command are binary strings, not text.

**Desired behavior**: The NativeConnect installer should either (a) download again if the file has changed on the server, or (b) skip the download and use the cached download if the file is unchanged. The curl command should not fail.

## Proposed solution

Restoring `.decode()` to the `getxattr` function linked in the description above should resolve this issue. I'll submit a PR shortly that does that.

**Comment by nmcspadden** [comment]
Good catch, but long-term, I'd like to think of a way we can unit test against this.

**Comment by LcTrKiD** [comment]
I found this issue too working on #718
