### ISSUE TITLE
Request to Add Repo

### ISSUE THREAD

**Issue by primalcurve** [autopkg/autopkg#727]
haircut has asked me to take over the maintenance of Hudl Sportscode/SportsCode. Could I get my repo added to the autopkg org?

https://github.com/primalcurve/primalcurve-recipes

Thanks!

**Comment by homebysix** [comment]
Repo created: https://github.com/autopkg/primalcurve-recipes

I suggest adding a readme to your repo, and submitting a PR for @haircut to add DeprecationWarning to his old recipes, if they don't already have it.
