### ISSUE TITLE
curl command options fail.

### ISSUE THREAD

**Issue by caskie** [autopkg/autopkg#731]
The curl command fails with the option --compressed and I can't find a way to set that option.

     Processor: URLTextSearcher: Error: Command '['/usr/bin/curl', '--compressed', '--location', 'https://global.gotomeeting.com/install']' returned non-zero exit status 61.

**Version (please complete the following information):**
 - OS version: MacOS 10.15.7
- AutoPkg Version: 2.3.1

**Comment by homebysix** [comment]
Hi @caskie - could you share what AutoPkg recipe you're running that results in this error? I'm unable to reproduce the issue with only the information you've provided.

**Comment by caskie** [comment]
[GoTo Opener.download.recipe.txt](https://github.com/autopkg/autopkg/files/6287949/GoTo.Opener.download.recipe.txt)

**Comment by caskie** [comment]
[GoTo Opener.download.recipe.txt](https://github.com/autopkg/autopkg/files/6287954/GoTo.Opener.download.recipe.txt)

**Comment by homebysix** [comment]
Hi @caskie - Try adjusting your URLTextSearcher arguments like so:

```
		<dict>
		 	<key>Processor</key>
			<string>URLTextSearcher</string>
			<key>Arguments</key>
			<dict>
				<key>url</key>
				<string>https://global.gotomeeting.com/install</string>
				<key>re_pattern</key>
				<string>openerLaunchToken":"?(.+)"}</string>
				<key>curl_opts</key>
				<array>
					<string>--no-compressed</string>
				</array>
			</dict>
		</dict>
```

**Comment by caskie** [comment]
That works Thanks! now I have a different issue :)
