### ISSUE TITLE
FYI, I created a URLDownloaderPython processor

### ISSUE THREAD

**Issue by jgstew** [autopkg/autopkg#734]
**See here:** https://github.com/jgstew/jgstew-recipes/blob/main/SharedProcessors/URLDownloaderPython.py

Should I submit this as a pull request for [autopkglib](https://github.com/autopkg/autopkg/tree/master/Code/autopkglib) processors at some point? or should it live as a "SharedProcessor"?

### Enhancements over `URLDownloader` processor:

- uses python urllib to download files instead of curl
- uses certifi for SSL CA certs to validate
  - I think curl on macOS uses system certs, so this could be a negative for some edge cases
- using an `.info.json` file instead of xattr to store etag, last-modified, and content-length
  - better cross platform support
  - still storing xattr where possible for backwards compatibility with URLDownloader
  - this functionality could be put into URLDownloader as well
- always prefetches headers to determine if download changed
  - this allows download change detection for `CHECK_FILESIZE_ONLY` cases without downloading the file first
  - solves the case where GoToMeeting and some other CDNs don't support `etag` / `last-modified` headers properly
  - better support for checking just `etag` or just `last-modified` in cases where one works but the other doesn't
  - https://github.com/jgstew/jgstew-recipes/issues/3#issuecomment-816001895
  - https://github.com/jgstew/jgstew-recipes/issues/5
- It has the option of hashing files while downloading the file
  - does not slow down the download process as far as I can tell
  - does use more CPU during the process
  - more efficient than hashing later because the file doesn't need to be read back from disk
  - calculating multiple hashes in parallel is much faster than doing them sequentially
  - related: https://github.com/jgstew/jgstew-recipes/blob/main/SharedProcessors/FileHasher.py
  - related: https://github.com/jgstew/bigfix_prefetch/blob/master/src/bigfix_prefetch/prefetch_from_url.py
- It uses as many class methods from ULRDownloader and URLGetter unmodified where possible
  - `class URLDownloaderPython(URLDownloader):`
- I tried to stick to python standard libraries or things already in AutoPkg [requirements.txt](https://github.com/autopkg/autopkg/blob/master/requirements.txt)
  - I think I need to revert the use of `from six.moves import urllib` to achieve this.

### Unresolved:

- I have only validated it on macOS and Ubuntu, still need to test on Windows.
- currently the `prefetch_filename` case relies on the old cURL method
  - I couldn't figure out how to get all the headers through all of the redirects using `urllib` to handle this
  - solving this might requires the `requests` library or hackery.
  - I really did not expect this to be the hardest part to solve.
- Right now I have the file hashing enabled by default, but I should probably switch it to disabled by default to emulate the behavior of URLDownloader
- Currently using too broad of exception handling, need to figure out the right exception types to catch.
  - `except Exception as err:  # pylint: disable=broad-except`
  - Not sure why I don't see the normal python errors in AutoPkg verbose level 6 runs that have the exception types.
    - Need to try:
      - `type(err).__name__`
      - `traceback.format_exc()`

**Comment by nmcspadden** [comment]
Wow, this is impressive! 

> I tried to stick to python standard libraries or things already in AutoPkg requirements.tx

Please do, as I really want to avoid adding more complex dependencies.

Please do submit a PR so it can go through review; it's nearly impossible for me to interact with as an issue or linked like this. I'd love to look at it in depth and give feedback.

**Comment by gregneagle** [comment]
Ironic if this ends up being the new URLDownloader.

The original URLDownloader processor was written in Python. Over time, issues with Python 2's various standard http libraries (and especially with https) made it too broken. Since Autopkg was designed to work with Apple's shipping Python and not require admins to install a bunch of additional Python modules, which is incredibly difficult to support, it was easier to just punt and use curl, a purpose-built tool with lots of developer involvement.

Now that Autopkg vends its own Python, there'a less of a reason to stick with curl. I do worry though about long-term maintenance of a new Python URLDownloader; I hope the code will be easily understood and maintainable by any Autopkg contributor, since the URLDownloader is probably the single-most-important Autopkg processor.

**Comment by jgstew** [comment]
"since the URLDownloader is probably the single-most-important Autopkg processor"

absolutely, and I think for that reason it probably makes sense to have both side-by-side.

oh, and another thing, I probably need to validate more recipes with it by making custom copies or overrides and swapping URLDownloader for URLDownloaderPython.

"Please do submit a PR so it can go through review; it's nearly impossible for me to interact with as an issue or linked like this. I'd love to look at it in depth and give feedback."

I'll get on that. Should I do that against the dev branch?

"currently the prefetch_filename case relies on the old cURL method"

I feel like this must be a solvable problem, and I definitely didn't expect it to be the hardest part, but I tried quite a few things and this seems like it might be the hardest part to solve without using a non standard library like `requests`

**Comment by gregneagle** [comment]
Since Autopkg now vends its own Python, it's worth discussing adding `requests` to that Python.

**Comment by jgstew** [comment]
"I hope the code will be easily understood and maintainable by any Autopkg contributor, since the URLDownloader is probably the single-most-important Autopkg processor."

That was already a bit of a pain as far as URLDownloaderPython -> URLDownloader -> URLGetter. It isn't always clear where each class method is defined. It also feels like some of them could be NOT class methods and be regular functions pretty easily, but then you loose the ability to do `self.output` which seems like a drawback. That said, there does seem like a valid use case for Python utility functions that are shared NOT through the Processor Class structure. Might make them easier to unit test as well.

**Comment by jgstew** [comment]
?
- Should I file the PR against the dev branch? I assume so.
- Should I test against Python2? or is Python2 compatibility no longer a concern going forward?

**Comment by nmcspadden** [comment]
Yes, file a PR against dev branch.

No, don't bother with Python 2, AutoPkg 1.x is not supported and I don't intend to maintain any backwards compatibility.

**Comment by n8felton** [comment]
> Since Autopkg now vends its own Python, it's worth discussing adding `requests` to that Python. (this was an immediate "no" when Autopkg relied on Apple's bundled Python)

With the amount of page scraping that happens with some AutoPkg recipes, it may be prudent to discuss adding _Beautiful Soup_ as well.

**Comment by gregneagle** [comment]
"With the amount of page scraping that happens with some AutoPkg recipes, it may be prudent to discuss adding Beautiful Soup as well." Perhaps. If a core URLDownloader processor would be easier to write/maintain using requests, then there's an argument for including requests. If a core HTMLParser processor would would be easier to write/maintain using Beautiful Soup, then there's an argument for including Beautiful Soup. But I would not want to include Beautiful Soup without a core processor that uses it. In any case, this is a different topic for a different discussion.

**Comment by jgstew** [comment]
"In any case, this is a different topic for a different discussion."

True, but...

It would be possible to confine "requests" and "Beautiful Soup" since they are new and extra dependencies to some sort of "official" shared processor that sits outside of [autopkglib](https://github.com/autopkg/autopkg/tree/master/Code/autopkglib) and instead lives in the [autopkg/recipes](https://github.com/autopkg/recipes) in a `SharedProcessors` folder which could have it's own distinct `requirements.txt` from Autopkg itself.

This does start to become an issue when these theoretical processors are used in shared recipes adding to some dependency confusion and would need some helpful error messages around any missing dependencies that are not satisfied by [AutoPkg's own requirements.txt](https://github.com/autopkg/autopkg/blob/master/requirements.txt)

**Comment by jgstew** [comment]
Created a pull request to resolve this: https://github.com/autopkg/autopkg/pull/736

This issue can be closed in favor of the created pull request for further discussion as needed.

**Comment by jgstew** [comment]
any update?

**Comment by homebysix** [comment]
"Just adding a new file" is an oversimplification. Any new processor we introduce needs to be maintained, incorporated into testing, and documented. We also need to consider the path forward if this processor ultimately replaces URLDownloader.

I've recently run your processor in place of URLDownloader against a random sample of download recipes. The results were great — most recipes produced the same exit code with URLDownloaderPython as with URLDownloader. However there were some recipes that produced anomalous results that I'm still finding time to investigate.

Pull requests will be easier to integrate once we have more robust automated testing, which is a near-term goal.

**Comment by jgstew** [comment]
@homebysix  "However there were some recipes that produced anomalous results that I'm still finding time to investigate."

Which ones gave anomalous results? I can also investigate.

"We also need to consider the path forward if this processor ultimately replaces URLDownloader."

I feel like that is pretty far off goal and it should be a separate processor at first so it can be proven and used specifically before being a drop in replacement.

**Comment by jgstew** [comment]
Resolved: https://github.com/autopkg/autopkg/pull/736
