### ISSUE TITLE
Please remove asemak-recipes

### ISSUE THREAD

**Issue by macmule** [autopkg/autopkg#740]
2 of the 4 recipes have been moved to dataJAR-recipes.

The other 2 are not working.

This was discussed and approved with @andysemak prior :)

**Comment by asemak** [comment]
Happy for my repo to be removed. Thanks.

**Comment by homebysix** [comment]
I've added deprecation warnings to the remaining recipes, and will remove the repo sometime after 30 days from now. Thanks!

**Comment by homebysix** [comment]
The repo has been archived. Thank you!
