### ISSUE TITLE
Fork Request

### ISSUE THREAD

**Issue by jrsd** [autopkg/autopkg#745]
Hi, I'm requesting that you fork my AutoPkg recipe repository here: https://github.com/jrsd/jrsd-autopkg-recipes. Currently this would add Boop.app to known recipes, which is not currently available.

**Comment by homebysix** [comment]
Repo created: https://github.com/autopkg/jrsd-recipes

I would suggest adding a brief README file for the repo. ([Doesn't have to be fancy](https://github.com/autopkg/recipes/blob/master/README.md).) Thanks!
