### ISSUE TITLE
Add my recipe repo

### ISSUE THREAD

**Issue by jannheider** [autopkg/autopkg#748]
Please add my recipe repro https://github.com/jannheider/autopkg-recipes

**Comment by homebysix** [comment]
Hello @jannheider. I've reviewed your recipes and I have one quick question:

[We discourage](https://github.com/autopkg/autopkg/wiki/Sharing-Recipes#repo-maintenance-expectations) adding recipes to public repos that duplicate recipes already available publicly. If a good reason exists for such redundancy, that reason should be outlined in your recipe's description. The following recipes look like they duplicate other recipes already in public autopkg repos:

- darktable.download
- darktable.pkg
- GoogleWebDesigner.download
- GoogleWebDesigner.munki
- Tresorit.download
- Tresorit.pkg

**Comment by jannheider** [comment]
Hello @homebysix sorry, my fault... changed and fixed. Now Using already available download recipes for darktable and Tresorit. Deleted GoogleWebdesigner.

**Comment by homebysix** [comment]
Repo created: https://github.com/autopkg/jannheider-recipes
