### ISSUE TITLE
repo-update error: "Your configuration specifies to merge with the ref 'master' from the remote, but no such ref was fetched."

### ISSUE THREAD

**Issue by bp88** [autopkg/autopkg#751]
**Describe the problem**
I’m trying to update my repos and got this error when running: `autopkg repo-update all`

> Attempting git pull for /Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.erikng-recipes...
> ERROR: Your configuration specifies to merge with the ref 'master'
> from the remote, but no such ref was fetched.

**Version (please complete the following information):**
- AutoPkg Version: 2.3.1

As per @homebysix this occurred because:
> Erik changed the default branch from “master” to “main” recently. I would recommend repo-delete and repo-add again to try to resolve that.

This suggestion resolved the issue. However, this might become more common due to new guidance from Github on branch naming: https://github.com/github/renaming

Not sure how much effort would be involved, but perhaps it might be beneficial to have autopkg better handle branch name changes?

**Comment by gregneagle** [comment]
Pull Requests accepted. :-)

**Comment by homebysix** [comment]
If this happens to anybody else, I'd be curious to see the output of:

```
git -C ~/Library/AutoPkg/RecipeRepos/com.github.autopkg.erikng-recipes status
```

This will reveal whether there's a merge conflict at the root of the problem, or if it's truly just the branch renaming causing the error.

**Comment by nmcspadden** [comment]
If the remote branch is deleted from upstream (GitHub), all the git clones cry. There seems to be no obvious way around this, and I'm not really enthusiastic about putting in a bunch of code to handle this more gracefully.
