### ISSUE TITLE
Please add natewalck-recipes

### ISSUE THREAD

**Issue by natewalck** [autopkg/autopkg#758]
Source: https://github.com/natewalck/natewalck-recipes

Thanks!

**Comment by homebysix** [comment]
As discussed on Slack, I'd recommend using jazzace's existing MacAdminPython download recipe as a parent for your Munki recipe. Once you've done that, I'll create the repo. Thanks!

**Comment by homebysix** [comment]
Repo created: https://github.com/autopkg/natewalck-recipes
