### ISSUE TITLE
Access to mosen-recipes

### ISSUE THREAD

**Issue by macmule** [autopkg/autopkg#761]
Hi folks,

Discussed this with @mosen, and essentially we're happy to take over the working recipes from their repo into dataJAR-recipes as per: https://github.com/autopkg/sheagcraig-recipes/issues/71

As such, can I have access to mosen-recipes?

I can then update recipes with deprecations as we go.

**Comment by homebysix** [comment]
Sounds good! @mosen, would you mind providing your approval here for confirmation?

**Comment by mosen** [comment]
@homebysix I approve as I dont have time to maintain these recipes

**Comment by homebysix** [comment]
Done! @macmule, check your email for an invitation to the mosen-recipes team. After accepting, you should be able to commit directly rather than via your fork.
