### ISSUE TITLE
Adding our repo

### ISSUE THREAD

**Issue by AsosRepo** [autopkg/autopkg#766]
Hi,

I was wondering how we go about getting our repo of recipes into autopkg? Is this something we need to do from our end?
Repo URL is: https://github.com/AsosRepo/AsosRepo

Please let me know if there is anything else you need.

Thanks.

Perry

**Comment by homebysix** [comment]
Hi @AsosRepo  - Information about getting a public repository of AutoPkg recipes can be found here: https://github.com/autopkg/autopkg/wiki/Sharing-Recipes

Have a look at the "Repo maintenance expectations" section there to understand what you'd be signing up for — importantly, trying to avoid duplicate recipes when possible. I see there are no `autopkg search` results for SymantecVIP, so you should be good there.

Typically, the naming convention of public repositories is _username-recipes_, but in your case the "Repo" part seems a bit redundant. Is there an alternative you would prefer, or is _AsosRepo-recipes_ your first pick?

**Comment by AsosRepo** [comment]
Hi @homebysix,

Thanks for the info thats really helpful.

In that case would we be able to add a repo privately? I feel that the amount of recipes we will make and use will be pretty small scale and also quite niche to our business.

The naming convention is fine to be AsosRepo-recipes if thats ok?

**Comment by AsosRepo** [comment]
Hi @gregneagle,

Pardon my ignorance but I couldn't find any documentation on how to add just recipes or add a private repo? Would you have the documentation to do that?

**Comment by gregneagle** [comment]
Presumably you are using the recipes now! How else could you know if they work or if they are useful? What am I missing here?

**Comment by gregneagle** [comment]
```
$ autopkg repo-add --help
Usage: autopkg repo-add recipe_repo_url
Download one or more new recipe repos and add it to the search path.
The 'recipe_repo_url' argument can be of the following forms:
- repo (implies 'https://github.com/autopkg/repo')
- user/repo (implies 'https://github.com/user/repo')
- (http[s]://|git://|user@server:)path/to/any/git/repo

Example: 'autopkg repo-add recipes'
..adds the autopkg/recipes repo from GitHub.

Options:
  -h, --help         show this help message and exit
  --prefs=FILE_PATH  
```

`autopkg repo-add https://github.com/AsosRepo/AsosRepo`
or
`autopkg repo-add AsosRepo/AsosRepo`
or if the repo is some place other than GitHub:
`autopkg repo-add https://ourinternalgitreposerver.my.org/some_path/AsosRepo`

**Comment by AsosRepo** [comment]
The VIP access recipe was made with recipe robot and uploaded to our repo for initial testing but I didn't know how to add the repo without having it added to the main autopkg repo.

I will use the command above to add it and test it out.

Thanks for the quick help its much appreciated.
