### ISSUE TITLE
Request to be added to flywire-recipes

### ISSUE THREAD

**Issue by n8felton** [autopkg/autopkg#782]
Requesting to have myself (@n8felton) and Scott Blake (@mscottblake - https://github.com/mscottblake) added to the flywire-recipes team and granted the admin role to the repo.

cc: @LcTrKiD for approvals.

**Comment by LcTrKiD** [comment]
Please add them to autopkg/flywire-recipes.

**Comment by homebysix** [comment]
Invitations sent. Thanks @LcTrKiD for approving.
