### ISSUE TITLE
FR: Add arg/flag for generating/pointing at recipe map

### ISSUE THREAD

**Issue by bdemetris** [autopkg/autopkg#785]
**THIS IS ONLY INTENDED FOR AUTOPKG BETAS.**

**Describe the problem**
the recipe map is required for autopkg to run. If you somehow deleted it, it doesn't exist, or its wrong version 2.4.1 won't regenerate it unless there is a change in the repo state (by design).

This poses a small annoyance in some environments where the autopkg run is purely ephemeral (i.e each morning you construct a new macos host inconveniently using aws ec2, and each evening you tear it down).

In this case, the instance comes up, you install autopkg, clone your autopkg repository from source control, mount a volume containing your munki repo (if applicable), and run your recipe list. 

Issues:
- The recipe map is local to the cache dir, so you'd need to account for it, and likely copy it into place after cloning the autopkg repo down.
- The recipe map might be wrong. Since you are version controlling autopkg, someone else might have updated the repo in source control, and maybe forgot to commit the new recipe map that was generated from state change. The new map is not in the repo so it's easy to overlook.
- Running a state change after cloning (i.e repo-add recipes && repo-delete recipes) does force a new map to be made, but that's kind of a hacky workaround.

**Proposal**

- Ideally there would be an argument to generate the recipe map. This just exposes the state change behavior to the user, and allows them to control it rather than relying on default behavior.
- Alternatively, add a flag to point to a recipe map similar to how `--prefs` works. If there was an env var in prefs that could specify the path to the recipe map, even better. Someone could easily point the recipe map location back to their source control repo, and now all contributors auto generate the correct file when they make a change, and its in the commit. This would solve for having to generate it each run.

**Version (please complete the following information):**
 - OS version: 11.6.2
- AutoPkg Version: 2.4.1 f2ef0ea

**Comment by nmcspadden** [comment]
This is identical to #884 , which is more recent, so I'm merging this one into that.
