### ISSUE TITLE
Repo-add after installing Autopkg in a new mac fails because there is no prefs

### ISSUE THREAD

**Issue by LcTrKiD** [autopkg/autopkg#786]
**THIS IS ONLY INTENDED FOR AUTOPKG BETAS.**

**Describe the problem**
In a fresh install of Autopkg without any preferences in `com.github.autopkg` if you run `autopkg repo-add repo` you get a TypeError

**Preferences contents**
NONE
**AutoPkg output**
```
➜   ~/L/AutoPkg autopkg repo-add apizz-recipes                                                             17:23:25
WARNING: Did not load any default preferences.
Attempting git clone for https://github.com/autopkg/apizz-recipes...

Adding /Users/Joaquin.Cabrerizo/Library/AutoPkg/RecipeRepos/com.github.autopkg.apizz-recipes to RECIPE_SEARCH_DIRS...
Updating recipe map...
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 2716, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2712, in main
    return subcommands[verb]["function"](argv)
  File "/usr/local/bin/autopkg", line 696, in repo_add
    calculate_recipe_map()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 510, in calculate_recipe_map
    for search_dir in get_pref("RECIPE_SEARCH_DIRS") + extra_search_dirs:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
```

**Expected behavior**
```
➜   ~/c/w/g/autopkg git:(master) Code/autopkg repo-add apizz-recipes                                       17:29:29
WARNING: Did not load any default preferences.
Attempting git pull for /Users/Joaquin.Cabrerizo/Library/AutoPkg/RecipeRepos/com.github.autopkg.apizz-recipes...
Already up to date.

Adding /Users/Joaquin.Cabrerizo/Library/AutoPkg/RecipeRepos/com.github.autopkg.apizz-recipes to RECIPE_SEARCH_DIRS...
Updated search path:
  '.'
  '~/Library/AutoPkg/Recipes'
  '/Library/AutoPkg/Recipes'
  '/Users/Joaquin.Cabrerizo/Library/AutoPkg/RecipeRepos/com.github.autopkg.apizz-recipes'
```

**Version (please complete the following information):**
 - OS version: 12.1
- AutoPkg Version: 2.4.1

**Comment by fridomac** [comment]
I am hitting this issue, too. The repo does not get added to the prefs File and the recipe Map calculation fails.
Any way to work around it when setting up a new Autopkg machine?
What I aleady tried:
- setting GIT_PATH and FAIL_RECIPES_WITHOUT_TRUST so the Prefs exist.
- setting an empty RECIPE_SEARCH_DIRS-Array (as mentioned on Slack)
Both do not help, if I then add a repo, I get the error message above.

**Comment by fridomac** [comment]
Will try creating an empty recipe map beforehand and see if that changes things. My use case is a CI Node that creates its environment before every run.

**Comment by fridomac** [comment]
Ok, writing the empty JSON file before did not help. In my testing one of the processes that generates the "recipe_map.json" has to be run after creating the Prefs, then all other repo-operations work.

**Comment by nmcspadden** [comment]
This was fixed at some point in the past and does not currently exhibit in RC6+.
