### ISSUE TITLE
Error in local.pkg.AdobeAIR: Processor: CodeSignatureVerifier

### ISSUE THREAD

**Issue by thdenton** [autopkg/autopkg#791]
getting a CodeSignatureVerifier error for AdobeAIR.pkg.recipe AdobeAIR.dmg is not mounted
Failed.

ICTMacs@Toms-MacBook-Pro ~ % autopkg run AdobeAIR.pkg.recipe                                                                                     
Processing AdobeAIR.pkg.recipe...
/private/var/ICTMacs/Library/AutoPkg/Cache/local.pkg.AdobeAIR/downloads/AdobeAIR.dmg is not mounted
Failed.

The following recipes failed:
    AdobeAIR.pkg.recipe
        Error in local.pkg.AdobeAIR: Processor: CodeSignatureVerifier: Error: /private/var/ICTMacs/Library/AutoPkg/Cache/local.pkg.AdobeAIR/downloads/AdobeAIR.dmg is not mounted

Nothing downloaded, packaged or imported.
ICTMacs@Toms-MacBook-Pro ~ %

**Comment by homebysix** [comment]
Hi @thdenton - Could you provide full `-vv` output for this?

Does the issue persist after rebooting the Mac? Are other dmg-mounting recipes affected or just AdobeAIR?

Do you have any antivirus software installed that might be accessing the cached dmg?

**Comment by nmcspadden** [comment]
I'm closing this because it seems transient and not an issue with AutoPkg core.
