### ISSUE TITLE
Recipe fork

### ISSUE THREAD

**Issue by Bupsy** [autopkg/autopkg#803]
https://github.com/Milk-Studios/autopkg-recipes

**Comment by homebysix** [comment]
Would milk-studios-recipes be the desired repo name here?

**Comment by Bupsy** [comment]
Sure that works. Thanks!

**Comment by homebysix** [comment]
Repo created: https://github.com/autopkg/milk-studios-recipes

One thing you may want to consider: the DaVinci Resolve "download" recipe looks like it just sets the input variables for the parent recipe, and doesn't perform any process of its own. This is usually a good use case for a recipe override. Having this recipe in the autopkg org will expose it to search queries, and people may be confused if the behavior is different than expected. I'll let you decide how to address that.
