### ISSUE TITLE
Plz fork repo

### ISSUE THREAD

**Issue by wegotoeleven** [autopkg/autopkg#812]
Hello! Can I please ask that you fork my repo?

https://github.com/wegotoeleven/wegotoeleven-recipes

I'm in the progress of migrating some recipes from moofit-recipes, and I'll be marking any migrated recipe as deprecated.

Thanks!

**Comment by wegotoeleven** [comment]
Sorry to pester! Any movement on this at all?

Thanks in advance 😎

**Comment by homebysix** [comment]
Do the DockerUniversal recipes do something different than [these](https://github.com/autopkg/moofit-recipes/blob/master/Docker/DockerUniversal.download.recipe.yaml)?

**Comment by wegotoeleven** [comment]
No, but I'll be deprecating the recipes in `moofit-recipes`, because I'm taking over management via my own repo.

**Comment by homebysix** [comment]
Repo created: https://github.com/autopkg/wegotoeleven-recipes
