### ISSUE TITLE
License parsing

### ISSUE THREAD

**Issue by TechnologyClassroom** [autopkg/autopkg#817]
GitHub says "View license" in the about section for this package when it could say "Apache-2.0 license" instead.

To fix this minor issue, the text from [LICENSE.txt](https://github.com/autopkg/autopkg/blob/master/LICENSE.txt) could me moved to a subheader in the ReadMe.md file and the text of LICENSE.txt could be the text of the Apache 2.0 license.  I could help with this if you would like.

**Comment by nmcspadden** [comment]
What is the actual problem? I'm not I understand the concern.

**Comment by nmcspadden** [comment]
The license is correctly documented based upon the Apache standard instructions:
https://www.apache.org/licenses/LICENSE-2.0#apply

**Comment by TechnologyClassroom** [comment]
That doc says, "Include a copy of the Apache License, typically in a file called LICENSE, in your work, and consider also including a NOTICE file that references the License."  The text currently in the license file is what you would append to the header of individual files covered under the license.  You would put the entirety of the Apache license in the license file.

**Comment by nmcspadden** [comment]
What problem does this solve, aside from a change in the behavior of GitHub's "View License" button?

**Comment by TechnologyClassroom** [comment]
From a pragmatic perspective, it would show newcomers to the project what the license is within the first page view.  From an idealistic perspective, it would accurately follow the license documentation.  Not sure if there is a legal difference in this case one way or the other as I am not a lawyer.

**Comment by TechnologyClassroom** [comment]
GitHub is just following the doc.

**Comment by gregneagle** [comment]
This discussion is pointless now. People have differing opinions. The current maintainers of this project are happy with the way it is right now. You are free to do it differently in your own projects.

**Comment by TechnologyClassroom** [comment]
That's fine.  If you change your mind, reach out to me.  It would only take me a few minutes to fix it.
