### ISSUE TITLE
Scripts/generate_processor_docs.py incorrectly updates _Sidebar.md

### ISSUE THREAD

**Issue by gregneagle** [autopkg/autopkg#826]
**Describe the problem**
Running the generate_processor_docs.py script to update the Processor documentation incorrectly removes everything in _Sidebar.md _after_ the Processor docs

**How to replicate**
git clone the autopkg repo; cd into the new autopkg directory.
Run `./Scripts/generate_processor_docs.py v2.7`
Observe the proposed changes to _Sidebar.md.

**Expected behavior**
Only the "Processor Reference" section of the sidebar is modified; other sections are left alone.

**Comment by nmcspadden** [comment]
This seems to be resolved - I just ran this, and it correctly kept the Development section at the end.
