### ISSUE TITLE
Support for "repo requirements" in a recipe

### ISSUE THREAD

**Issue by timsutton** [autopkg/autopkg#83]
Some people maintain a set of recipes that are of one type, like @autopkg/hansen-m-recipes. Other people then go and maintain some recipes that use one or more of these recipes as ParentRecipes. Currently the user simply has to know of the requirement and have the ParentRecipes also in their search path (usually via a `repo-add`).

So I propose we have some support for a key like `RequiredRepos` which is an array of other required recipe URLs for this recipe. 

Without having given this much thought, I'm leaning towards just printing warnings on a repo-add for any recipes with requirements that aren't yet satisfied, and not allowing the recipe to run unless autopkg has this required repo in its list of recipe search paths. In other words, don't automatically clone new repos so as to avoid unexpected conflicts with the currently-installed list of recipes.

This would have the same issue I brought up in #82, which would be possibly needing to read the upstream Git repo URL (for example, from `.git/config`) from search paths to determine whether a search path contains a required repo, rather than simply being able to depend on actual local paths.

**Comment by jannheider** [comment]
Some kind of a key like "RequiredRepos" would be very helpful.

We recently had an issue with an repo that had an processor from another repo.
https://github.com/autopkg/jessepeterson-recipes/issues/46#issuecomment-305166424
