### ISSUE TITLE
Please add my Repo

### ISSUE THREAD

**Issue by Lotusshaney** [autopkg/autopkg#835]
Please add my repo to the other autopkg repos

URL is https://github.com/Lotusshaney/autopkg_recipes

Thanks

Dan

**Comment by Lotusshaney** [comment]
Hi, seen requests after mine done, is there anything I need to do ?

**Comment by homebysix** [comment]
Hello! I'll take a look at this soon. We typically download and inspect the repo contents and provide suggestions for alignment with conventions, which takes a little time.

**Comment by homebysix** [comment]
Hi @Lotusshaney - Here are my thoughts:

- We try to discourage the publication of duplicate recipes in public repos, to make searching a bit more manageable for people and to consolidate maintenance effort. It looks like a few of your recipes are duplicates (in function, if not in total) of existing recipes. Whenever possible, could you reference existing recipes instead of posting duplicates?
    - Your 1Password recipes duplicate those in dataJAR-recipes
    - Your ABetterFinderRename recipes duplicate those in homebysix-recipes
    - Your Bitwarden recipes duplicate those in blackthroat-recipes
    - Your DBeaver recipes duplicate those in peshay-recipes
    - Your IINA recipes duplicate those in hjuutilainen-recipes
    - Your Jamf Pro Switcher recipes duplicate those in zentral-recipes
    - Your LaunchControl recipes duplicate those in homebysix-recipes
    - Your MenuMeters recipes duplicate those in peshay-recipes
    - Your Mist recipes duplicate those in zentral-recipes
    - Your NextCloud recipes duplicate those in andredb90-recipes
    - Your Platypus recipes duplicate those in peshay-recipes
    - Your Rocket.Chat recipes duplicate those in apizz-recipes
    - Your Support recipes duplicate those in paul-cossey-recipes
    - Your xca recipes duplicate those in peterkelm-recipes
- A few Munki recipes lack a useful description. Recommend adding one in, or omitting the key:
    - 1Password8.munki
    - IPVanish VPN.munki
    - No-IP DUC.munki
    - Platypus.munki
- The following recipes failed when I tried to run them:
    - ./Nextcloud/NextcloudDesktopClient.download.recipe
    - ./Murus/murus.download.recipe
    - ./MenuMeters/MenuMeters.download.recipe
    - ./IINA/IINA.download.recipe
    - ./Jamf Pro Switcher/Jamf Pro Switcher.download.recipe
    - ./xca/xca.download.recipe
    - ./Mist/Mist.download.recipe
    - ./Support/Support.download.recipe
    - ./Bitwarden/Bitwarden.download.recipe
    - ./Rocket.Chat/Rocket.Chat.download.recipe

Thanks!

**Comment by Lotusshaney** [comment]
Hi,

Strange you say that that these recipes fail to run, they come from a running system.

In fact here is run of each one of those, with every one working.

`autopkg run -v /Users/Shared/GIT/autopkg_recipes/Nextcloud/NextcloudDesktopClient.download.recipe
Processing /Users/Shared/GIT/autopkg_recipes/Nextcloud/NextcloudDesktopClient.download.recipe...
WARNING: /Users/Shared/GIT/autopkg_recipes/Nextcloud/NextcloudDesktopClient.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
GitHubReleasesInfoProvider
GitHubReleasesInfoProvider: Matched regex '^Nextcloud-.*pkg$' among asset(s): Nextcloud-3.6.1-x64.msi, Nextcloud-3.6.1-x64.msi.asc, Nextcloud-3.6.1-x86_64.AppImage, Nextcloud-3.6.1-x86_64.AppImage.asc, Nextcloud-3.6.1.pkg, Nextcloud-3.6.1.pkg.asc, Nextcloud-3.6.1.pkg.tbz, Nextcloud-3.6.1.pkg.tbz.asc
GitHubReleasesInfoProvider: Selected asset 'Nextcloud-3.6.1.pkg' from release 'Release 3.6.1'
URLDownloader
URLDownloader: Storing new Last-Modified header: Tue, 18 Oct 2022 15:21:22 GMT
URLDownloader: Storing new ETag header: "0x8DAB11C6A1FF38E"
URLDownloader: Downloaded /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.nextcloud/downloads/Nextcloud.pkg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: Verifying installer package signature...
CodeSignatureVerifier: Package "Nextcloud.pkg":
CodeSignatureVerifier:    Status: signed by a developer certificate issued by Apple for distribution
CodeSignatureVerifier:    Notarization: trusted by the Apple notary service
CodeSignatureVerifier:    Signed with a trusted timestamp on: 2022-10-18 10:31:29 +0000
CodeSignatureVerifier:    Certificate Chain:
CodeSignatureVerifier:     1. Developer ID Installer: Nextcloud GmbH (NKUJUXUJ3B)
CodeSignatureVerifier:        Expires: 2026-08-11 15:02:05 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            64 98 3A B7 F6 59 37 C6 00 E5 72 2E 58 77 A4 9C FB C7 2C 9A 2E DE
CodeSignatureVerifier:            F6 53 6C 49 9C D5 CF 77 6C F7
CodeSignatureVerifier:        ------------------------------------------------------------------------
CodeSignatureVerifier:     2. Developer ID Certification Authority
CodeSignatureVerifier:        Expires: 2027-02-01 22:12:15 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            7A FC 9D 01 A6 2F 03 A2 DE 96 37 93 6D 4A FE 68 09 0D 2D E1 8D 03
CodeSignatureVerifier:            F2 9C 88 CF B0 B1 BA 63 58 7F
CodeSignatureVerifier:        ------------------------------------------------------------------------
CodeSignatureVerifier:     3. Apple Root CA
CodeSignatureVerifier:        Expires: 2035-02-09 21:40:36 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            B0 B1 73 0E CB C7 FF 45 05 14 2C 49 F1 29 5E 6E DA 6B CA ED 7E 2C
CodeSignatureVerifier:            68 C5 BE 91 B5 A1 10 01 F0 24
CodeSignatureVerifier:
CodeSignatureVerifier: Signature is valid
CodeSignatureVerifier: Authority name chain is valid
Receipt written to /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.nextcloud/receipts/NextcloudDesktopClient.download-receipt-20221107-083755.plist

The following new items were downloaded:
    Download Path
    -------------
    /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.nextcloud/downloads/Nextcloud.pkg
	
autopkg run -v /Users/Shared/GIT/autopkg_recipes/Murus/murus.download.recipe
Processing /Users/Shared/GIT/autopkg_recipes/Murus/murus.download.recipe...
WARNING: /Users/Shared/GIT/autopkg_recipes/Murus/murus.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
GitHubReleasesInfoProvider
GitHubReleasesInfoProvider: Matched regex '.*\.zip$' among asset(s): murus-2.3.3.zip
GitHubReleasesInfoProvider: Selected asset 'murus-2.3.3.zip' from release 'Murus 2.3.3'
URLDownloader
URLDownloader: Storing new Last-Modified header: Sat, 02 Jul 2022 13:43:26 GMT
URLDownloader: Storing new ETag header: "0x8DA5C30D7294D74"
URLDownloader: Downloaded /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.murus/downloads/murus-2.3.3.zip
Unarchiver
Unarchiver: Guessed archive format 'zip' from filename murus-2.3.3.zip
Unarchiver: Unarchived /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.murus/Downloads/murus-2.3.3.zip to /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.murus/Downloads/
FileMover
FileMover: File /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.murus/Downloads/murus 2.3.3.dmg moved to /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.murus/Downloads/murus-2.3.3.dmg
EndOfCheckPhase
Receipt written to /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.murus/receipts/murus.download-receipt-20221107-083839.plist

The following new items were downloaded:
    Download Path
    -------------
    /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.murus/downloads/murus-2.3.3.zip
	
autopkg run -v /Users/Shared/GIT/autopkg_recipes/IINA/IINA.download.recipe
Processing /Users/Shared/GIT/autopkg_recipes/IINA/IINA.download.recipe...
WARNING: /Users/Shared/GIT/autopkg_recipes/IINA/IINA.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
GitHubReleasesInfoProvider
GitHubReleasesInfoProvider: Selected asset 'IINA.v1.3.1.dmg' from release 'IINA 1.3.1'
URLDownloader
URLDownloader: Storing new Last-Modified header: Sun, 06 Nov 2022 15:13:23 GMT
URLDownloader: Storing new ETag header: "0x8DAC009725BFF27"
URLDownloader: Downloaded /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.IINA/downloads/IINA-1.3.1.dmg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: Mounted disk image /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.IINA/downloads/IINA-1.3.1.dmg
CodeSignatureVerifier: Verifying code signature...
CodeSignatureVerifier: Deep verification enabled...
CodeSignatureVerifier: Strict verification not defined. Using codesign defaults...
CodeSignatureVerifier: /private/tmp/dmg.dDJneA/IINA.app: valid on disk
CodeSignatureVerifier: /private/tmp/dmg.dDJneA/IINA.app: satisfies its Designated Requirement
CodeSignatureVerifier: /private/tmp/dmg.dDJneA/IINA.app: explicit requirement satisfied
CodeSignatureVerifier: Signature is valid
Receipt written to /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.IINA/receipts/IINA.download-receipt-20221107-084047.plist

The following new items were downloaded:
    Download Path
    -------------
    /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.IINA/downloads/IINA-1.3.1.dmg
	
autopkg run -v /Users/Shared/GIT/autopkg_recipes/Jamf\ Pro\ Switcher/Jamf\ Pro\ Switcher.download.recipe
Processing /Users/Shared/GIT/autopkg_recipes/Jamf Pro Switcher/Jamf Pro Switcher.download.recipe...
WARNING: /Users/Shared/GIT/autopkg_recipes/Jamf Pro Switcher/Jamf Pro Switcher.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
GitHubReleasesInfoProvider
GitHubReleasesInfoProvider: Matched regex '.*\.dmg$' among asset(s): Jamf.Pro.Switcher.2.4.dmg, Jamf.Pro.Switcher.2.4.pkg
GitHubReleasesInfoProvider: Selected asset 'Jamf.Pro.Switcher.2.4.dmg' from release '2.4'
URLDownloader
URLDownloader: Storing new Last-Modified header: Wed, 08 Dec 2021 06:21:10 GMT
URLDownloader: Storing new ETag header: "0x8D9BA12ED2E1B2C"
URLDownloader: Downloaded /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.JamfProSwitcher/downloads/Jamf Pro Switcher-2.4.dmg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: Mounted disk image /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.JamfProSwitcher/downloads/Jamf Pro Switcher-2.4.dmg
CodeSignatureVerifier: Verifying code signature...
CodeSignatureVerifier: Deep verification enabled...
CodeSignatureVerifier: Strict verification not defined. Using codesign defaults...
CodeSignatureVerifier: /private/tmp/dmg.aU1Y55/Jamf Pro Switcher.app: valid on disk
CodeSignatureVerifier: /private/tmp/dmg.aU1Y55/Jamf Pro Switcher.app: satisfies its Designated Requirement
CodeSignatureVerifier: /private/tmp/dmg.aU1Y55/Jamf Pro Switcher.app: explicit requirement satisfied
CodeSignatureVerifier: Signature is valid
Versioner
Versioner: Mounted disk image /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.JamfProSwitcher/downloads/Jamf Pro Switcher-2.4.dmg
Versioner: Found version 2.4 in file /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.JamfProSwitcher/downloads/Jamf Pro Switcher-2.4.dmg/Jamf Pro Switcher.app/Contents/Info.plist
Receipt written to /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.JamfProSwitcher/receipts/Jamf Pro Switcher.download-receipt-20221107-084129.plist

The following new items were downloaded:
    Download Path
    -------------
    /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.JamfProSwitcher/downloads/Jamf Pro Switcher-2.4.dmg

autopkg run -v /Users/Shared/GIT/autopkg_recipes/xca/xca.download.recipe
Processing /Users/Shared/GIT/autopkg_recipes/xca/xca.download.recipe...
WARNING: /Users/Shared/GIT/autopkg_recipes/xca/xca.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
GitHubReleasesInfoProvider
GitHubReleasesInfoProvider: Matched regex '.*\.dmg$' among asset(s): xca-2.4.0.dmg, xca-2.4.0.msi, xca-2.4.0.tar.gz, xca-portable-2.4.0.zip
GitHubReleasesInfoProvider: Selected asset 'xca-2.4.0.dmg' from release 'XCA 2.4.0'
URLDownloader
URLDownloader: Storing new Last-Modified header: Wed, 08 Dec 2021 05:49:24 GMT
URLDownloader: Storing new ETag header: "0x8D9BA0E7D2FA8C7"
URLDownloader: Downloaded /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.xca/downloads/xca-RELEASE.2.4.0.dmg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: Mounted disk image /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.xca/downloads/xca-RELEASE.2.4.0.dmg
CodeSignatureVerifier: Verifying code signature...
CodeSignatureVerifier: Deep verification enabled...
CodeSignatureVerifier: Strict verification not defined. Using codesign defaults...
CodeSignatureVerifier: /private/tmp/dmg.Ad6s2O/xca.app: valid on disk
CodeSignatureVerifier: /private/tmp/dmg.Ad6s2O/xca.app: satisfies its Designated Requirement
CodeSignatureVerifier: /private/tmp/dmg.Ad6s2O/xca.app: explicit requirement satisfied
CodeSignatureVerifier: Signature is valid
Versioner
Versioner: Mounted disk image /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.xca/downloads/xca-RELEASE.2.4.0.dmg
Versioner: Found version 2.4.0 in file /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.xca/downloads/xca-RELEASE.2.4.0.dmg/xca.app/Contents/Info.plist
Receipt written to /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.xca/receipts/xca.download-receipt-20221107-083612.plist

The following new items were downloaded:
    Download Path
    -------------
    /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.xca/downloads/xca-RELEASE.2.4.0.dmg

autopkg run -v /Users/Shared/GIT/autopkg_recipes/Mist/Mist.download.recipe
Processing /Users/Shared/GIT/autopkg_recipes/Mist/Mist.download.recipe...
WARNING: /Users/Shared/GIT/autopkg_recipes/Mist/Mist.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
GitHubReleasesInfoProvider
GitHubReleasesInfoProvider: Selected asset 'Mist.0.3.pkg' from release '0.3'
URLDownloader
URLDownloader: Storing new Last-Modified header: Mon, 26 Sep 2022 04:24:22 GMT
URLDownloader: Storing new ETag header: "0x8DA9F76FCF4D749"
URLDownloader: Downloaded /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.Mist/downloads/Mist-0.3.pkg
EndOfCheckPhase
Receipt written to /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.Mist/receipts/Mist.download-receipt-20221107-084252.plist

The following new items were downloaded:
    Download Path
    -------------
    /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.Mist/downloads/Mist-0.3.pkg
	
autopkg run -v /Users/Shared/GIT/autopkg_recipes/Support/Support.download.recipe
Processing /Users/Shared/GIT/autopkg_recipes/Support/Support.download.recipe...
WARNING: /Users/Shared/GIT/autopkg_recipes/Support/Support.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
GitHubReleasesInfoProvider
GitHubReleasesInfoProvider: Matched regex '.*\.pkg$' among asset(s): Support.2.4.1.pkg, Support.2.4.1.zip, SupportHelper1.0.pkg
GitHubReleasesInfoProvider: Selected asset 'Support.2.4.1.pkg' from release 'Support 2.4.1'
URLDownloader
URLDownloader: Storing new Last-Modified header: Sun, 28 Aug 2022 21:40:47 GMT
URLDownloader: Storing new ETag header: "0x8DA893DF7F013B6"
URLDownloader: Downloaded /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.Support/downloads/Support-2.4.1.pkg
EndOfCheckPhase
Receipt written to /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.Support/receipts/Support.download-receipt-20221107-084337.plist

The following new items were downloaded:
    Download Path
    -------------
    /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.Support/downloads/Support-2.4.1.pkg
	
autopkg run -v /Users/Shared/GIT/autopkg_recipes/Bitwarden/Bitwarden.download.recipe
Processing /Users/Shared/GIT/autopkg_recipes/Bitwarden/Bitwarden.download.recipe...
WARNING: /Users/Shared/GIT/autopkg_recipes/Bitwarden/Bitwarden.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
GitHubReleasesInfoProvider
GitHubReleasesInfoProvider: Matched regex '.*\.dmg$' among asset(s): Bitwarden-2022.5.1-amd64.deb, Bitwarden-2022.5.1-arm64-store.appx, Bitwarden-2022.5.1-arm64.appx, Bitwarden-2022.5.1-arm64.nsis.7z, Bitwarden-2022.5.1-ia32-store.appx, Bitwarden-2022.5.1-ia32.appx, Bitwarden-2022.5.1-ia32.nsis.7z, Bitwarden-2022.5.1-universal-mac.zip, Bitwarden-2022.5.1-universal.dmg, Bitwarden-2022.5.1-universal.dmg.blockmap, Bitwarden-2022.5.1-universal.pkg, Bitwarden-2022.5.1-x64-store.appx, Bitwarden-2022.5.1-x64.appx, Bitwarden-2022.5.1-x64.freebsd, Bitwarden-2022.5.1-x64.nsis.7z, Bitwarden-2022.5.1-x86_64.AppImage, Bitwarden-2022.5.1-x86_64.rpm, Bitwarden-Installer-2022.5.1.exe, Bitwarden-Portable-2022.5.1.exe, bitwarden.2022.5.1.nupkg, bitwarden_2022.5.1_amd64.snap, latest-linux.yml, latest-mac.yml, latest.yml
GitHubReleasesInfoProvider: Selected asset 'Bitwarden-2022.5.1-universal.dmg' from release 'Version v2022.5.1'
URLDownloader
URLDownloader: Storing new Last-Modified header: Wed, 08 Jun 2022 16:15:36 GMT
URLDownloader: Storing new ETag header: "0x8DA496A1F2D7908"
URLDownloader: Downloaded /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.Bitwarden/downloads/Bitwarden-2022.5.1.dmg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: Mounted disk image /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.Bitwarden/downloads/Bitwarden-2022.5.1.dmg
CodeSignatureVerifier: Verifying code signature...
CodeSignatureVerifier: Deep verification enabled...
CodeSignatureVerifier: Strict verification not defined. Using codesign defaults...
CodeSignatureVerifier: /private/tmp/dmg.mSYxdU/Bitwarden.app: valid on disk
CodeSignatureVerifier: /private/tmp/dmg.mSYxdU/Bitwarden.app: satisfies its Designated Requirement
CodeSignatureVerifier: /private/tmp/dmg.mSYxdU/Bitwarden.app: explicit requirement satisfied
CodeSignatureVerifier: Signature is valid
Versioner
Versioner: Mounted disk image /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.Bitwarden/downloads/Bitwarden-2022.5.1.dmg
Versioner: Found version 2022.5.1 in file /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.Bitwarden/downloads/Bitwarden-2022.5.1.dmg/Bitwarden.app/Contents/Info.plist
Receipt written to /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.Bitwarden/receipts/Bitwarden.download-receipt-20221107-084441.plist

The following new items were downloaded:
    Download Path
    -------------
    /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.Bitwarden/downloads/Bitwarden-2022.5.1.dmg
	
autopkg run -v /Users/Shared/GIT/autopkg_recipes/Rocket.Chat/Rocket.Chat.download.recipe
Processing /Users/Shared/GIT/autopkg_recipes/Rocket.Chat/Rocket.Chat.download.recipe...
WARNING: /Users/Shared/GIT/autopkg_recipes/Rocket.Chat/Rocket.Chat.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
GitHubReleasesInfoProvider
GitHubReleasesInfoProvider: Matched regex '.*\.dmg$' among asset(s): latest-mac.yml, latest.yml, rocketchat-3.8.12-linux-amd64.deb, rocketchat-3.8.12-linux-amd64.snap, rocketchat-3.8.12-linux-x64.tar.gz, rocketchat-3.8.12-linux-x86_64.rpm, rocketchat-3.8.12-mac.dmg, rocketchat-3.8.12-mac.dmg.blockmap, rocketchat-3.8.12-mac.pkg, rocketchat-3.8.12-mac.zip, rocketchat-3.8.12-mas.pkg, rocketchat-3.8.12-win-ia32.appx, rocketchat-3.8.12-win-ia32.exe, rocketchat-3.8.12-win-ia32.exe.blockmap, rocketchat-3.8.12-win-ia32.msi, rocketchat-3.8.12-win-x64.appx, rocketchat-3.8.12-win-x64.exe, rocketchat-3.8.12-win-x64.exe.blockmap, rocketchat-3.8.12-win-x64.msi, rocketchat-3.8.12-win.exe, rocketchat-3.8.12-win.exe.blockmap
GitHubReleasesInfoProvider: Selected asset 'rocketchat-3.8.12-mac.dmg' from release '3.8.12'
URLDownloader
URLDownloader: Storing new Last-Modified header: Mon, 10 Oct 2022 16:46:57 GMT
URLDownloader: Storing new ETag header: "0x8DAAADF0BBB8B26"
URLDownloader: Downloaded /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.Rocket.Chat/downloads/Rocket.Chat-3.8.12.dmg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: Mounted disk image /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.Rocket.Chat/downloads/Rocket.Chat-3.8.12.dmg
CodeSignatureVerifier: Verifying code signature...
CodeSignatureVerifier: Deep verification enabled...
CodeSignatureVerifier: Strict verification not defined. Using codesign defaults...
CodeSignatureVerifier: /private/tmp/dmg.7HA1K8/Rocket.Chat.app: valid on disk
CodeSignatureVerifier: /private/tmp/dmg.7HA1K8/Rocket.Chat.app: satisfies its Designated Requirement
CodeSignatureVerifier: /private/tmp/dmg.7HA1K8/Rocket.Chat.app: explicit requirement satisfied
CodeSignatureVerifier: Signature is valid
Versioner
Versioner: Mounted disk image /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.Rocket.Chat/downloads/Rocket.Chat-3.8.12.dmg
Versioner: Found version 3.8.12 in file /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.Rocket.Chat/downloads/Rocket.Chat-3.8.12.dmg/Rocket.Chat.app/Contents/Info.plist
Receipt written to /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.Rocket.Chat/receipts/Rocket.Chat.download-receipt-20221107-084554.plist

The following new items were downloaded:
    Download Path
    -------------
    /Users/test/Library/AutoPkg/Cache/com.github.Lotusshaney.download.Rocket.Chat/downloads/Rocket.Chat-3.8.12.dmg
`
and here is a screen shot of the output folder

![shot](https://user-images.githubusercontent.com/1845849/200266308-53f8435c-52a3-4449-86b1-768db3a01965.png)

**Comment by Lotusshaney** [comment]
As for the dupes and the descriptions, thanks for the critique I will update and remove as needed

**Comment by homebysix** [comment]
You're right, the failing recipes were due to an issue on my side (expired GitHub personal access token). I've fixed that now, and all the recipes are running successfully. 👍

**Comment by jannheider** [comment]
1password8 doesn't make sense as this switch more to a rolling release and at some point wenn version 9 will be out it will direkt download version 9.

Check my comment here
https://github.com/autopkg/hjuutilainen-recipes/issues/222#issuecomment-1138436900

But nice that they now have a universal app and a pkg installer.
I could add the pkg download and Munki to my 1password latest repo so we have all 3 options (universal, arm,x86) at one place

**Comment by Lotusshaney** [comment]
Ok but please add the pre and post scripts otherwise 1Password mini gets left running the older version and causes problems

**Comment by jannheider** [comment]
perfekt, i will check and test the script.

**Comment by Lotusshaney** [comment]
I have removed the items that are listed as duplicates and I have added more descriptive notes to the remaining outline recipes.

**Comment by homebysix** [comment]
New repo added. Thanks!

https://github.com/autopkg/Lotusshaney-recipes
