### ISSUE TITLE
Autopkg not installed properly?

### ISSUE THREAD

**Issue by tej** [autopkg/autopkg#847]
So I downloaded the release and I ran the GUI installer, but the folder wasn't even there in ~/Library
But Autopkgr showed it was installed.
It wasn't until I added a repo to Autopkgr that the folder showed up but in the ~/Library/Autopkg folder there was only the 'RecipeRepo' folder.

I have a custom processor I'm using so I had to create the 'autopkglib' folder and put the processor in the folder.
But when I ran my overriden recipe with the custom processor I got the error:
Unknown Processor 'MyCustomProcessorName'.

Not sure if Autopkg is installed properly but Autopkgr is showing it is installed.

How can I go about fixing this?

**Comment by tej** [comment]
Nevermind. I got it working.

**Comment by rabbitsf** [comment]
Hi tej,
I am having the same problem. I tried on different Mac laptops and it did not show up the AutoPkg application icon under the Applications folder after installation. How did you fix it? Thanks!

**Comment by homebysix** [comment]
@rabbitsf - There is no AutoPkg application in the Applications folder. It sounds like you're referring to [AutoPkgr](https://github.com/lindegroup/autopkgr/), which is a separate project dependent upon autopkg (the command line tool). I recommend you install the latest autopkg release from [here](https://github.com/autopkg/autopkg/releases/latest), then install the app AutoPkgr from [here](https://github.com/lindegroup/autopkgr/releases/latest). You can and should use autopkg in the Terminal if the AutoPkgr app isn't behaving as you expect.
