### ISSUE TITLE
Error with name in globalRecipeMap["overrides-identifiers"]

### ISSUE THREAD

**Issue by jgstew** [autopkg/autopkg#874]
**THIS IS ONLY INTENDED FOR AUTOPKG BETAS.**

Info: https://github.com/autopkg/autopkg/commit/08fbeb23aecbfe21d78dc9d2efb22e99c2b0d87e#r124169275

**Describe the problem**
If I try to run autopkg dev branch, my existing recipe map file does not have the key "overrides-identifiers" in it, so I deleted the map file hoping it would get regenerated, and the problem persists. If the key is missing it should either be skipped over without error, or it should be attempted to be regenerated by autopkg. There should also be a way to tell autopkg to regenerate the map file when needed.

I'm also having an issue with running recipes that have a parent that is not in the map file and wish to append to it or supplement it in some way since I used to be able to run recipes referenced in folders in the current working directory but can no longer.

**Preferences contents**

Output from `python autopkg info`:

```
WARNING: Library 'xattr' unavailable. Defining no-op implementation.
WARNING: Failed 'from Foundation import NSDictionary' in autopkglib.MunkiInstallsItemsCreator
WARNING: Failed 'from Foundation import CFPreferencesCopyAppValue' in autopkglib.MunkiSetDefaultCatalog
WARNING: Failed 'from Foundation import NSPredicate' in autopkglib.StopProcessingIf
Current preferences:
{'RECIPE_REPOS': {'C:\\Users\\james\\Library\\AutoPkg\\RecipeRepos\\com.github.autopkg.hansen-m-recipes': {'URL': 'https://github.com/autopkg/hansen-m-recipes'},
                  'C:\\Users\\james\\Library\\AutoPkg\\RecipeRepos\\com.github.autopkg.homebysix-recipes': {'URL': 'https://github.com/autopkg/homebysix-recipes'},
                  'C:\\Users\\james\\Library\\AutoPkg\\RecipeRepos\\com.github.autopkg.recipes': {'URL': 'https://github.com/autopkg/recipes'},
                  'C:\\Users\\james\\Library\\AutoPkg\\RecipeRepos\\com.github.hjuutilainen.autopkg-virustotalanalyzer': {'URL': 'https://github.com/hjuutilainen/autopkg-virustotalanalyzer'},
                  'C:\\Users\\james\\Library\\AutoPkg\\RecipeRepos\\com.github.jgstew.jgstew-recipes': {'URL': 'https://github.com/jgstew/jgstew-recipes'}},
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes',
                        'C:\\Users\\james\\Library\\AutoPkg\\RecipeRepos\\com.github.hjuutilainen.autopkg-virustotalanalyzer',
                        'C:\\Users\\james\\Library\\AutoPkg\\RecipeRepos\\com.github.jgstew.jgstew-recipes',
                        'C:\\Users\\james\\Library\\AutoPkg\\RecipeRepos\\com.github.autopkg.hansen-m-recipes',
                        'C:\\Users\\james\\Library\\AutoPkg\\RecipeRepos\\com.github.autopkg.homebysix-recipes']}
```

**AutoPkg output**
*BE SURE TO SANITIZE ANY SENSITIVE DATA SUCH AS PASSWORDS OR ADDRESSES.*

```
python autopkg run -vv ANYTHING
WARNING: Library 'xattr' unavailable. Defining no-op implementation.
WARNING: Failed 'from Foundation import NSDictionary' in autopkglib.MunkiInstallsItemsCreator
WARNING: Failed 'from Foundation import CFPreferencesCopyAppValue' in autopkglib.MunkiSetDefaultCatalog
WARNING: Failed 'from Foundation import NSPredicate' in autopkglib.StopProcessingIf
Looking for ANYTHING...
Traceback (most recent call last):
  File "C:\Users\james\Documents\_Code\autopkg\Code\autopkg", line 2727, in <module>
    sys.exit(main(sys.argv))
  File "C:\Users\james\Documents\_Code\autopkg\Code\autopkg", line 2723, in main
    return subcommands[verb]["function"](argv)
  File "C:\Users\james\Documents\_Code\autopkg\Code\autopkg", line 2146, in run_recipes
    recipe = load_recipe(
  File "C:\Users\james\Documents\_Code\autopkg\Code\autopkg", line 307, in load_recipe
    recipe_file = locate_recipe(
  File "C:\Users\james\Documents\_Code\autopkg\Code\autopkg", line 222, in locate_recipe
    recipe_file = find_recipe(name, skip_overrides)
  File "C:\Users\james\Documents\_Code\autopkg\Code\autopkg", line 139, in find_recipe
    ) or find_recipe_by_identifier(id_or_name, skip_overrides)
  File "C:\Users\james\Documents\_Code\autopkg\Code\autopkglib\__init__.py", line 453, in find_recipe_by_identifier
    if not skip_overrides and identifier in globalRecipeMap["overrides-identifiers"]:
KeyError: 'overrides-identifiers'
```

**Expected behavior**
A clear and concise description of what you expected to happen. What specific part of the recipe or AutoPkg run did not behave correctly?

**Version (please complete the following information):**
 - OS version: Windows 10
- AutoPkg Version: dev branch at this moment in time

**Comment by nmcspadden** [comment]
Yep, good catch - autopkg doesn't really handle an invalid recipe map well. Easy to fix this particular issue, but the larger problem remains.

**Comment by nmcspadden** [comment]
This is fixed in https://github.com/autopkg/autopkg/commit/a3e7e90ccc721008f86b3c4a5f4f948c316f7eac.

The recipe map will now automatically be created if you use any autopkg verb other than "help" or "version", and it either can't be found or is invalid.

This makes it a bit more heavy handed, but this is more likely what people expected to happen.

**Comment by nmcspadden** [comment]
Addressed in https://github.com/autopkg/autopkg/releases/tag/v2.8.1RC5.

**Comment by jgstew** [comment]
That was quick! thanks!

**Comment by jgstew** [comment]
"This makes it a bit more heavy handed, but this is more likely what people expected to happen."

I think this approach makes sense.
