### ISSUE TITLE
Sophos Endpoint Protection - hdiutil: couldn't unmount disk

### ISSUE THREAD

**Issue by mengelsen** [autopkg/autopkg#879]
[Others](https://github.com/autopkg/autopkg/issues?q=is%3Aissue+hdiutil%3A+couldn%27t+unmount) have reported issues with running autopkg recipes on hardware that has AV software installed.

Error Message:
`unmounting ~/Library/AutoPkg/Cache/local.download.RecipeNameHere/downloads/AppNameHere.dmg failed: hdiutil: couldn't unmount "disk4" - Resource busy Failed. unmounting`

I'm wondering if anyone has created an Exclusion policy (within Sophos Central Cloud), that allows both autoPKG and Sophos to run on the same system.

**Comment by nmcspadden** [comment]
This is a well known observation/problem. Anything that interferes with mounted disks mounting and unmounting rapidly is known to negatively impact AutoPkg, which often triggers multiple of these in a given recipe. There's no obvious thing to do from an AutoPkg perspective, as it largely depends on your organization and its configuration of EDR / AV tools. 

The only real advice I can give is to attempt to create broad enough exclusions that AutoPkg is allowed to move freely, or find ways to exempt the AutoPkg host from the EDR enforcement.
