### ISSUE TITLE
AutoPkg should rebuild missing recipe map on demand

### ISSUE THREAD

**Issue by gregneagle** [autopkg/autopkg#884]
**THIS IS ONLY INTENDED FOR AUTOPKG BETAS.**

**Describe the problem**
autopkg should _always_ build a recipe map if one is missing.
If an AutoPkg user installs 3.0 RC1 or uses the the dev branch as of this commit: https://github.com/autopkg/autopkg/commit/1831864ae199871b724b14a49b011b85179744ca if the next thing they do is attempt to run a recipe (a common thing to do with AutoPkg), they are greeted with this error:
```
Cannot read the recipe map file!
Cannot parse the recipe map - it's either missing or invalid!
Try adding or removing a repo to rebuild it.
```

**AutoPkg output**
```
$ autopkg run GoogleChrome.download
Cannot read the recipe map file!
Cannot parse the recipe map - it's either missing or invalid!
Try adding or removing a repo to rebuild it.
```

**Expected behavior**
autopkg should almost never output this error message.
autopkg should _always_ build a recipe map if one doesn't exist.

**Version (please complete the following information):**
 - OS version: 13.5.1
- AutoPkg Version: commit 1831864ae199871b724b14a49b011b85179744ca

**Comment by jgstew** [comment]
I've hit a version of this as well.

It seems like the error should trigger a build/rebuild of the map and a retry.

**Comment by nmcspadden** [comment]
This was fixed in https://github.com/autopkg/autopkg/issues/886.
