### ISSUE TITLE
Fork request for recipes repo

### ISSUE THREAD

**Issue by paulsuh** [autopkg/autopkg#89]
Please pull in my recipes:
https://github.com/paulsuh/paul-suh-recipes

**Comment by homebysix** [comment]
Hi @paulsuh - Are you still interested in this recipe repo getting forked? I notice that the last commit was in 2014.

I see that many of the recipes duplicate existing recipes available in the autopkg org (1Password, Audacity, ChronoSync, CoRD, GitHub, and others). While there's no rule against duplicating existing recipes, it's better to submit broadly-useful changes to the original recipes' authors as pull requests first.

I also see that many of your download recipes use MacUpdate as a download source. I would strongly encourage you to download from the original developer instead. Some party download sites have been implicated in bundling unwanted software with downloaded installers.

If the repo is still alive, could you address the items above and reply? Or if not, feel free to close this issue. Thanks!
