### ISSUE TITLE
Expecting value: line 2 column 1 (char 1) Failed.

### ISSUE THREAD

**Issue by cdlp789** [autopkg/autopkg#892]
Has anyone seen this error before? I'm new to this so would appreciate any support.
This happens everytime I run a recipe. Whether its an override or not.
"Expecting value: line 2 column 1 (char 1)
Failed."

**Comment by nmcspadden** [comment]
You're going to need to provide significantly more information. Please use the issue template and provide some context.

**Comment by jgstew** [comment]
Are you attempting to run a YAML formatted recipe?

If so, please check the recipe using YAMLint to validate that the YAML is validly formatted.

I have seen a similar error when the YAML was not valid.

That said, as stated, really need to know what commands you are using, what version of autopkg you are using, what operating system you are using, what version of python you are using, and what recipes specifically you are running, and all the other things spelled out in the issue templates.
