### ISSUE TITLE
Archive vmule-recipes repository

### ISSUE THREAD

**Issue by homebysix** [autopkg/autopkg#912]
Per this issue, vmule-recipes can be archived: https://github.com/autopkg/vmule-recipes/issues/4

I'll plan to add DeprecationNotice to the recipes for 30+ days, then remove the recipes and archive the GitHub repo, as we've done in the past with other unused repos.

**Comment by vmule** [comment]
Thanks

**Comment by homebysix** [comment]
Still working on this — forgot to push the deprecation message upstream, so I'll wait 30 days from now to let people see the deprecation message.

**Comment by homebysix** [comment]
Repo is archived.
