### ISSUE TITLE
Add repo pandemicus-recipes

### ISSUE THREAD

**Issue by pandemicus** [autopkg/autopkg#935]
Hi. Please add my repo [pandemicus-recipes](https://github.com/pandemicus/pandemicus-recipes) to autopkg. 

More recipes are coming soon!

**Comment by homebysix** [comment]
There are some minor issues flagged by my pre-commit hooks:

```
Tropy/tropy.download.recipe: Use actual app name instead of %NAME%.app in CodeSignatureVerifier processor argument.
Tropy/tropy.download.recipe: GitHubReleasesInfoProvider processor requires minimum AutoPkg version 0.5.0
Tropy/tropy.pkg.recipe: Use actual app name instead of %NAME%.app in Copier processor argument.
Tropy/tropy.pkg.recipe: Use actual app name instead of %NAME%.app in Copier processor argument.
```

But nothing that would block fork creation. Repo created here: https://github.com/autopkg/pandemicus-recipes
