### ISSUE TITLE
Add repo ccaviness-recipes

### ISSUE THREAD

**Issue by ccaviness** [autopkg/autopkg#944]
Hello - I'd ilke my repo [ccaviness-recipes](https://github.com/ccaviness/ccaviness-recipes/) forked and added to autopkg.

Thanks!

**Comment by homebysix** [comment]
Hi @ccaviness — Thanks for the submission!

I see the only recipe so far is ChatGPT, and there's [already one](https://github.com/autopkg/Lotusshaney-recipes/blob/d38bf9260ce27722f3de4ce09fcc2f3b5fc6cfce/OpenAI/ChatGPT.download.recipe) in the autopkg org. We discourage duplication of existing recipes whenever possible. Does your recipe do something differently than that one? Are there other recipes on deck that aren't duplicates?

**Comment by ccaviness** [comment]
Ah, those recipes wasn't submitted when I created mine. I will have other recipes coming, however.

**Comment by homebysix** [comment]
OK — I'll create the repo, but I do recommend deprecating the ChatGPT recipes in favor of the existing ones, if there are no differences worth pointing out.

Here's the new repo: https://github.com/autopkg/ccaviness-recipes

Thanks!
