### ISSUE TITLE
Trouble adding new recipes

### ISSUE THREAD

**Issue by thetornad0** [autopkg/autopkg#945]
Hello! I hope you're doing well. I [made a recipe fork request last year](https://github.com/autopkg/autopkg/issues/858) which worked well (thank you), but I'm trying to add a new one and am receiving the following error when trying to push my changes: `Permission to autopkg/thetornad0-recipes.git denied to thetornad0.
fatal: Could not read from remote repository. Please make sure you have the correct access rights`

And when I go to the **Security** section of my repo, I see: You’re making changes in a project you don’t have write access to.

Is there a chance I don't have write access to the repo now? Or am I missing a step? Thank you!

**Comment by gregneagle** [comment]
For some reason you were not a member of the "thetornad0-recipes" team for the that recipe repo. I've invited you to join that team, which should give you write access.

**Comment by thetornad0** [comment]
Ah, no problem! Thanks for the quick help - I'm able to push now.
