### ISSUE TITLE
Add users to the AutoPkg Org

### ISSUE THREAD

**Issue by paul-cossey** [autopkg/autopkg#954]
Hi, Folks 

Please can you add the following users to the AutoPkg Org so that I can then add them to the [dataJAR Recipes](https://github.com/autopkg/dataJAR-recipes) Repo.

Sorry can't seem to @ the user accounts so I've added a link to the profiles. Let me know if you need anything else. 

@duncan-mccracken (https://github.com/duncan-mccracken)
@johnduvaljamf (https://github.com/johnduvaljamf) 
@Patryk-Ab (https://github.com/Patryk-Ab) 

Thanks!

**Comment by homebysix** [comment]
I've invited all 3 to join the GitHub team that grants access to the dataJAR-recipes repo. Thanks!

**Comment by paul-cossey** [comment]
Thanks, @homebysix appreciate the swift response!
