### ISSUE TITLE
Repo Add Request

### ISSUE THREAD

**Issue by wu-wenqing** [autopkg/autopkg#958]
Hi there!

I'm requesting my [recipe repo](https://github.com/wu-wenqing/autopkg-recipes) to be forked. If there's anything to be fixed or adjusted, please let me know.

Thanks!

**Comment by wu-wenqing** [comment]
Hi! I believe I just fixed those issues you mentioned. I did forget to add the parent recipe and I removed that specific version of Jellyfish Connect. Please review these changes and let me know if they are accurate!
Thanks :)

**Comment by homebysix** [comment]
Are LaunchAtLoginHelper and JellyfishConnect two different software products, or the same?

The Jellyfish Connect munki recipe uses identifier `com.github.wu-wenqing.munki.LaunchAtLoginHelper`, but the description says `Downloads the latest version of Jellyfish Connect and imports it into Munki.`

**Comment by wu-wenqing** [comment]
Fixed with better naming conventions! Yes, they are the same software (sorry about that...)!

**Comment by homebysix** [comment]
Repo created: https://github.com/autopkg/wu-wenqing-recipes
