### ISSUE TITLE
Add support for custom pre processor

### ISSUE THREAD

**Issue by ygini** [autopkg/autopkg#98]
Like many autopkg user I have the big problem linked to wrong munki catalog set by different recipes.

I've read the autopkg code to understand how it work and what kind of fix should be done to allow proper handling of this problem without having a specific munki related fix in the autopkg core system.

The problem's root is not linked to autopkg behavior or error in the recipe. 

The main problem is simple: we need a way to do advanced override (especially for complex data type like dictionary and array) without having to override every single recipe used.

Converted into a spec list:
* must not add a munki specific --catalog option to the run command ;
* must be usable for other purpose ;
* must be on demand, nothing run by default, only named call when needed ;
* must allow complex analysis and override of the recipe.

So, looking at that and the current code, I think a preprocessor system should be a good idea.

At autopkg:1180, the system do a autopackager.process(recipe). Before this instruction, it's possible to insert a call to a custom preprocessor system allowed to edit the content of the recipe object.

The preprocessor can be constructed like recipe, simple name in specific folder with specific protocols to implement like a preprocess function with take the current recipe in argument and return the updated one.

In the preprocess function, third part developer can do what ever they want to the recipe, like change the target catalog, translate the description via Google Translate, or anything else.

The preprocessor used for the current run can be set via a argument specific to the run verb (and should also be supported by the info one for troubleshooting purpose).

What do you think? Any pro / cons?

**Comment by timsutton** [comment]
This functionality was merged in 0.4.2, so this can be closed.
